import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render } from '@testing-library/react';
import type { Element } from '@bim-ai/core';
import { InspectorPropertiesFor } from './InspectorContent';
import i18n from '../../i18n';

const t = i18n.t.bind(i18n);

afterEach(() => {
  cleanup();
});

const targetDoor: Extract<Element, { kind: 'door' }> = {
  kind: 'door',
  id: 'door-abc-123',
  name: 'Front Door',
  wallId: 'wall-1',
  alongT: 0.5,
  widthMm: 900,
};

const tag: Extract<Element, { kind: 'placed_tag' }> = {
  kind: 'placed_tag',
  id: 'auto-tag-door-abc-123',
  hostElementId: targetDoor.id,
  hostViewId: 'pv-1',
  positionMm: { xMm: 1000, yMm: 400 },
  autoGenerated: true,
  categoryKind: 'door',
  fields: {
    mark: 'D1',
    typeName: 'Single Door 900',
    widthMm: 900,
    heightMm: null,
  },
};

const elementsById: Record<string, Element> = {
  [targetDoor.id]: targetDoor,
  [tag.id]: tag,
};

describe('tag inspector — §4.11.2', () => {
  it('renders inspector-tag-mark input with current mark value', () => {
    const { getByTestId } = render(InspectorPropertiesFor(tag, t, { elementsById }));
    const input = getByTestId('inspector-tag-mark') as HTMLInputElement;
    expect(input).toBeTruthy();
    expect(input.defaultValue).toBe('D1');
  });

  it('mark input change dispatches update_element_property', () => {
    const onPropertyChange = vi.fn();
    const { getByTestId } = render(
      InspectorPropertiesFor(tag, t, { elementsById, onPropertyChange }),
    );
    const input = getByTestId('inspector-tag-mark') as HTMLInputElement;
    fireEvent.blur(input, { target: { value: 'D2' } });
    expect(onPropertyChange).toHaveBeenCalledWith(
      'fields',
      expect.objectContaining({ mark: 'D2' }),
    );
  });

  it('renders inspector-tag-target read-only display', () => {
    const { getByTestId } = render(InspectorPropertiesFor(tag, t, { elementsById }));
    const targetEl = getByTestId('inspector-tag-target');
    expect(targetEl).toBeTruthy();
    expect(targetEl.textContent).toContain('Front Door');
  });

  it('renders inspector-tag-type display', () => {
    const { getByTestId } = render(InspectorPropertiesFor(tag, t, { elementsById }));
    const typeEl = getByTestId('inspector-tag-type');
    expect(typeEl).toBeTruthy();
    expect(typeEl.textContent).toContain('Single Door 900');
  });

  it('mark input is empty when fields.mark is null', () => {
    const tagNoMark: Extract<Element, { kind: 'placed_tag' }> = {
      ...tag,
      id: 'auto-tag-no-mark',
      fields: { ...tag.fields, mark: null },
    };
    const { getByTestId } = render(InspectorPropertiesFor(tagNoMark, t, { elementsById }));
    const input = getByTestId('inspector-tag-mark') as HTMLInputElement;
    expect(input.defaultValue).toBe('');
  });

  it('target falls back to hostElementId when host not in elementsById', () => {
    const { getByTestId } = render(InspectorPropertiesFor(tag, t, { elementsById: {} }));
    const targetEl = getByTestId('inspector-tag-target');
    expect(targetEl.textContent).toContain(targetDoor.id);
  });
});
