import type { Element, XY } from '@bim-ai/core';
import type { JSX } from 'react';

import { generateAutoDimensionChain } from './autoDimension';
import { clearAutoAnnotationsCommand, generateAutoTags } from './autoTags';

/**
 * PLN-01 / ANN-01 — Annotate ribbon for the active plan view.
 *
 * Surfaces the auto-dimension / auto-tag generators (PLN-01) and the
 * detail-component creators (ANN-01) as a small inline toolbar. Each
 * button packages a sequence of semantic commands and dispatches them
 * via `onSemanticCommand`. Auto buttons are idempotent — they emit a
 * `clearAutoGeneratedAnnotations` command first, so re-running clears
 * the previous output before regenerating.
 */
export type AnnotateRibbonProps = {
  planViewId: string;
  levelId: string;
  elementsById: Record<string, Element>;
  cropMinMm?: XY | null;
  cropMaxMm?: XY | null;
  onSemanticCommand: (cmd: Record<string, unknown>) => void;
};

function viewCenter(
  elementsById: Record<string, Element>,
  cropMinMm: XY | null | undefined,
  cropMaxMm: XY | null | undefined,
): XY {
  if (cropMinMm && cropMaxMm) {
    return {
      xMm: (cropMinMm.xMm + cropMaxMm.xMm) / 2,
      yMm: (cropMinMm.yMm + cropMaxMm.yMm) / 2,
    };
  }
  // Otherwise drop near origin — model bounds are computed elsewhere.
  void elementsById;
  return { xMm: 0, yMm: 0 };
}

export function AnnotateRibbon({
  planViewId,
  levelId,
  elementsById,
  cropMinMm,
  cropMaxMm,
  onSemanticCommand,
}: AnnotateRibbonProps): JSX.Element {
  const ctx = { planViewId, levelId, cropMinMm, cropMaxMm } as const;

  const handleAutoDim = (axis: 'x' | 'y') => {
    onSemanticCommand(clearAutoAnnotationsCommand(planViewId, 'dimensions'));
    const cmds = generateAutoDimensionChain(elementsById, ctx, axis);
    for (const c of cmds) onSemanticCommand(c);
  };

  const handleAutoTag = (kind: 'room' | 'door' | 'window') => {
    onSemanticCommand(clearAutoAnnotationsCommand(planViewId, 'tags'));
    const cmds = generateAutoTags(elementsById, ctx, kind);
    for (const c of cmds) onSemanticCommand(c);
  };

  const placeDetailLine = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDetailLine',
      hostViewId: planViewId,
      pointsMm: [
        { xMm: c.xMm - 500, yMm: c.yMm },
        { xMm: c.xMm + 500, yMm: c.yMm },
      ],
      strokeMm: 1.5,
      style: 'solid',
    });
  };

  const placeDetailRegion = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDetailRegion',
      hostViewId: planViewId,
      boundaryMm: [
        { xMm: c.xMm - 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm + 400 },
        { xMm: c.xMm - 400, yMm: c.yMm + 400 },
      ],
      fillPattern: 'hatch_45',
      fillColour: '#cccccc',
    });
  };

  const placeMaskingRegion = () => {
    // KRN-10 — drop a square masking region at the view centre. Sketch-based
    // boundary authoring is propagated by Agent 4; until then the click-polygon
    // fallback is the load-bearing path.
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createMaskingRegion',
      hostViewId: planViewId,
      boundaryMm: [
        { xMm: c.xMm - 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm + 400 },
        { xMm: c.xMm - 400, yMm: c.yMm + 400 },
      ],
      fillColor: '#ffffff',
    });
  };

  const placeTextNote = () => {
    const text = window.prompt('Text note', 'Note');
    if (!text) return;
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createTextNote',
      hostViewId: planViewId,
      positionMm: c,
      text,
      fontSizeMm: 200,
      anchor: 'tl',
    });
  };

  return (
    <div
      data-testid="plan-annotate-ribbon"
      className="pointer-events-auto absolute right-3 top-3 z-10 flex flex-col gap-1 rounded border border-border bg-surface/90 px-2 py-2 text-[10px] text-muted backdrop-blur"
    >
      <div className="font-semibold text-foreground">Annotate</div>
      <button
        type="button"
        data-testid="plan-annotate-auto-dim-x"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoDim('x')}
        title="Generates a horizontal dimension chain. Run again to regenerate."
      >
        Auto Dim X
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-dim-y"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoDim('y')}
        title="Generates a vertical dimension chain. Run again to regenerate."
      >
        Auto Dim Y
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-tag-rooms"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoTag('room')}
        title="Tags every room at its centroid. Run again to regenerate."
      >
        Auto Tag — Rooms
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-tag-doors"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoTag('door')}
        title="Tags every door. Run again to regenerate."
      >
        Auto Tag — Doors
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-tag-windows"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoTag('window')}
        title="Tags every window. Run again to regenerate."
      >
        Auto Tag — Windows
      </button>
      <div className="mt-1 border-t border-border pt-1" />
      <button
        type="button"
        data-testid="plan-annotate-detail-line"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDetailLine}
        title="Drop a 1m detail line at the view centre."
      >
        Detail Line
      </button>
      <button
        type="button"
        data-testid="plan-annotate-detail-region"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDetailRegion}
        title="Drop an 800×800mm hatched region at the view centre."
      >
        Detail Region (Sketch)
      </button>
      <button
        type="button"
        data-testid="plan-annotate-masking-region"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeMaskingRegion}
        title="Drop an 800×800mm opaque masking region that occludes underlying linework."
      >
        Masking Region
      </button>
      <button
        type="button"
        data-testid="plan-annotate-text-note"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeTextNote}
        title="Place a text note at the view centre."
      >
        Text Note
      </button>
    </div>
  );
}
