/* eslint-disable bim-ai/no-hex-in-chrome -- pre-v3 hex literals; remove when this file is migrated in B4 Phase 2 */
import { useRef, useState } from 'react';
import type { Element, XY } from '@bim-ai/core';
import type { JSX } from 'react';

import { generateAutoDimensionChain } from './autoDimension';
import { clearAutoAnnotationsCommand, generateAutoTags } from './autoTags';

/**
 * PLN-01 / ANN-01 — Annotate ribbon for the active plan view.
 *
 * Surfaces the auto-dimension / auto-tag generators (PLN-01) and the
 * detail-component creators (ANN-01) as a small inline toolbar. Each
 * button packages a sequence of semantic commands and dispatches them
 * via `onSemanticCommand`. Auto buttons are idempotent — they emit a
 * `clearAutoGeneratedAnnotations` command first, so re-running clears
 * the previous output before regenerating.
 */
export type AnnotateRibbonProps = {
  planViewId: string;
  levelId: string;
  elementsById: Record<string, Element>;
  cropMinMm?: XY | null;
  cropMaxMm?: XY | null;
  onSemanticCommand: (cmd: Record<string, unknown>) => void;
};

function viewCenter(
  elementsById: Record<string, Element>,
  cropMinMm: XY | null | undefined,
  cropMaxMm: XY | null | undefined,
): XY {
  if (cropMinMm && cropMaxMm) {
    return {
      xMm: (cropMinMm.xMm + cropMaxMm.xMm) / 2,
      yMm: (cropMinMm.yMm + cropMaxMm.yMm) / 2,
    };
  }
  // Otherwise drop near origin — model bounds are computed elsewhere.
  void elementsById;
  return { xMm: 0, yMm: 0 };
}

export function AnnotateRibbon({
  planViewId,
  levelId,
  elementsById,
  cropMinMm,
  cropMaxMm,
  onSemanticCommand,
}: AnnotateRibbonProps): JSX.Element {
  const ctx = { planViewId, levelId, cropMinMm, cropMaxMm } as const;
  const [textNoteInput, setTextNoteInput] = useState(false);
  const [textNoteDraft, setTextNoteDraft] = useState('');
  const textNoteRef = useRef<HTMLInputElement>(null);

  const handleAutoDim = (axis: 'x' | 'y') => {
    onSemanticCommand(clearAutoAnnotationsCommand(planViewId, 'dimensions'));
    const cmds = generateAutoDimensionChain(elementsById, ctx, axis);
    for (const c of cmds) onSemanticCommand(c);
  };

  const handleAutoTag = (kind: 'room' | 'door' | 'window') => {
    onSemanticCommand(clearAutoAnnotationsCommand(planViewId, 'tags'));
    const cmds = generateAutoTags(elementsById, ctx, kind);
    for (const c of cmds) onSemanticCommand(c);
  };

  const placeDetailLine = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDetailLine',
      hostViewId: planViewId,
      pointsMm: [
        { xMm: c.xMm - 500, yMm: c.yMm },
        { xMm: c.xMm + 500, yMm: c.yMm },
      ],
      strokeMm: 1.5,
      style: 'solid',
    });
  };

  const placeDetailRegion = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDetailRegion',
      hostViewId: planViewId,
      boundaryMm: [
        { xMm: c.xMm - 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm + 400 },
        { xMm: c.xMm - 400, yMm: c.yMm + 400 },
      ],
      fillPattern: 'hatch_45',
      fillColour: '#cccccc',
    });
  };

  const placeMaskingRegion = () => {
    // KRN-10 — drop a square masking region at the view centre. Sketch-based
    // boundary authoring is propagated by Agent 4; until then the click-polygon
    // fallback is the load-bearing path.
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createMaskingRegion',
      hostViewId: planViewId,
      boundaryMm: [
        { xMm: c.xMm - 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm - 400 },
        { xMm: c.xMm + 400, yMm: c.yMm + 400 },
        { xMm: c.xMm - 400, yMm: c.yMm + 400 },
      ],
      fillColor: '#ffffff',
    });
  };

  const placeSpotElevation = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createSpotElevation',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
      elevationMm: 0,
    });
  };

  const placeRadialDimension = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createRadialDimension',
      hostViewId: planViewId,
      centerMm: { xMm: c.xMm, yMm: c.yMm },
      arcPointMm: { xMm: c.xMm + 500, yMm: c.yMm },
    });
  };

  const placeDiameterDimension = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDiameterDimension',
      hostViewId: planViewId,
      centerMm: { xMm: c.xMm, yMm: c.yMm },
      arcPointMm: { xMm: c.xMm + 500, yMm: c.yMm },
    });
  };

  const placeArcLengthDimension = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createArcLengthDimension',
      hostViewId: planViewId,
      centerMm: { xMm: c.xMm, yMm: c.yMm },
      radiusMm: 500,
      startAngleDeg: 0,
      endAngleDeg: 90,
    });
  };

  const placeMaterialTag = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createMaterialTag',
      hostViewId: planViewId,
      hostElementId: '',
      layerIndex: 0,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
    });
  };

  const placeMultiCategoryTag = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createMultiCategoryTag',
      hostViewId: planViewId,
      hostElementId: '',
      positionMm: { xMm: c.xMm, yMm: c.yMm },
    });
  };

  const placeTreadNumber = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    void c;
    onSemanticCommand({
      type: 'createTreadNumber',
      hostViewId: planViewId,
      stairElementId: '',
    });
  };

  const placeKeynote = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createKeynote',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
      keynoteKey: 'A1',
      keynoteText: '',
    });
  };

  const placeSpanDirection = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createSpanDirection',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
      directionDeg: 0,
    });
  };

  const placePipeLegend = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createPipeLegend',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
      title: 'Pipe Legend',
      entries: [
        { systemType: 'domestic_cold_water', label: 'Cold Water', colour: '#0066cc' },
        { systemType: 'domestic_hot_water', label: 'Hot Water', colour: '#cc3300' },
        { systemType: 'sanitary', label: 'Sanitary', colour: '#996633' },
        { systemType: 'fire_protection', label: 'Fire Protection', colour: '#cc0000' },
      ],
    });
  };

  const placeDuctLegend = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDuctLegend',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
      title: 'Duct Legend',
      entries: [
        { systemType: 'supply_air', label: 'Supply Air', colour: '#0099cc' },
        { systemType: 'return_air', label: 'Return Air', colour: '#66aacc' },
        { systemType: 'exhaust_air', label: 'Exhaust Air', colour: '#999999' },
      ],
    });
  };

  const placeDetailComponent = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createDetailComponent',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm, yMm: c.yMm },
      componentShape: 'bolt',
    });
  };

  const placeRepeatingDetail = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createRepeatingDetail',
      hostViewId: planViewId,
      startMm: { xMm: c.xMm - 500, yMm: c.yMm },
      endMm: { xMm: c.xMm + 500, yMm: c.yMm },
      componentShape: 'break_line',
      spacingMm: 200,
    });
  };

  const placeDetailGroup = () => {
    onSemanticCommand({
      type: 'createDetailGroup',
      hostViewId: planViewId,
      name: 'Group 1',
      memberIds: [],
    });
  };

  const placeColorFillLegend = () => {
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createColorFillLegend',
      hostViewId: planViewId,
      positionMm: { xMm: c.xMm + 800, yMm: c.yMm + 800 },
    });
  };

  const commitTextNote = () => {
    const text = textNoteDraft.trim();
    if (!text) {
      setTextNoteInput(false);
      setTextNoteDraft('');
      return;
    }
    const c = viewCenter(elementsById, cropMinMm, cropMaxMm);
    onSemanticCommand({
      type: 'createTextNote',
      hostViewId: planViewId,
      positionMm: c,
      text,
      fontSizeMm: 200,
      anchor: 'tl',
    });
    setTextNoteInput(false);
    setTextNoteDraft('');
  };

  return (
    <div
      data-testid="plan-annotate-ribbon"
      className="pointer-events-auto absolute right-3 top-3 z-10 flex flex-col gap-1 rounded border border-border bg-surface/90 px-2 py-2 text-[10px] text-muted backdrop-blur"
    >
      <div className="font-semibold text-foreground">Annotate</div>
      <button
        type="button"
        data-testid="plan-annotate-auto-dim-x"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoDim('x')}
        title="Generates a horizontal dimension chain. Run again to regenerate."
      >
        Auto Dim X
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-dim-y"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoDim('y')}
        title="Generates a vertical dimension chain. Run again to regenerate."
      >
        Auto Dim Y
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-tag-rooms"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoTag('room')}
        title="Tags every room at its centroid. Run again to regenerate."
      >
        Auto Tag — Rooms
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-tag-doors"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoTag('door')}
        title="Tags every door. Run again to regenerate."
      >
        Auto Tag — Doors
      </button>
      <button
        type="button"
        data-testid="plan-annotate-auto-tag-windows"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={() => handleAutoTag('window')}
        title="Tags every window. Run again to regenerate."
      >
        Auto Tag — Windows
      </button>
      <div className="mt-1 border-t border-border pt-1" />
      <button
        type="button"
        data-testid="plan-annotate-detail-line"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDetailLine}
        title="Drop a 1m detail line at the view centre."
      >
        Detail Line
      </button>
      <button
        type="button"
        data-testid="plan-annotate-detail-region"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDetailRegion}
        title="Drop an 800×800mm hatched region at the view centre."
      >
        Detail Region (Sketch)
      </button>
      <button
        type="button"
        data-testid="plan-annotate-masking-region"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeMaskingRegion}
        title="Drop an 800×800mm opaque masking region that occludes underlying linework."
      >
        Masking Region
      </button>
      <button
        type="button"
        data-testid="plan-annotate-spot-elevation"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeSpotElevation}
        title="Place a spot elevation annotation at the view centre."
      >
        Spot Elev.
      </button>
      <button
        type="button"
        data-testid="plan-annotate-radial-dimension"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeRadialDimension}
        title="Place a radial dimension (center to arc point 500mm right)."
      >
        Radial Dim
      </button>
      <button
        type="button"
        data-testid="plan-annotate-diameter-dimension"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDiameterDimension}
        title="Place a diameter dimension (center to arc point 500mm right)."
      >
        Dia. Dim
      </button>
      <button
        type="button"
        data-testid="plan-annotate-arc-length-dimension"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeArcLengthDimension}
        title="Place an arc length dimension (r=500mm, 0°→90°)."
      >
        Arc Len.
      </button>
      {textNoteInput ? (
        <div className="flex flex-col gap-1">
          <input
            ref={textNoteRef}
            autoFocus
            type="text"
            aria-label="Text note content"
            value={textNoteDraft}
            onChange={(e) => setTextNoteDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') commitTextNote();
              if (e.key === 'Escape') {
                setTextNoteInput(false);
                setTextNoteDraft('');
              }
            }}
            className="rounded border border-border bg-background px-2 py-0.5 text-[10px] text-foreground"
            placeholder="Note text…"
          />
          <div className="flex gap-1">
            <button
              type="button"
              data-testid="plan-annotate-text-note-commit"
              className="flex-1 rounded border border-border px-2 py-0.5 text-left text-[10px] hover:bg-accent/20 hover:text-foreground"
              onClick={commitTextNote}
            >
              Place
            </button>
            <button
              type="button"
              className="rounded border border-border px-2 py-0.5 text-[10px] text-muted hover:bg-accent/20"
              onClick={() => {
                setTextNoteInput(false);
                setTextNoteDraft('');
              }}
            >
              ✕
            </button>
          </div>
        </div>
      ) : (
        <button
          type="button"
          data-testid="plan-annotate-text-note"
          className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
          onClick={() => setTextNoteInput(true)}
          title="Place a text note at the view centre."
        >
          Text Note
        </button>
      )}
      <button
        type="button"
        data-testid="plan-annotate-material-tag"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeMaterialTag}
        title="Place a material layer tag at the view centre."
      >
        Material Tag
      </button>
      <button
        type="button"
        data-testid="plan-annotate-multi-category-tag"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeMultiCategoryTag}
        title="Place a multi-category tag at the view centre."
      >
        Multi-Category Tag
      </button>
      <button
        type="button"
        data-testid="plan-annotate-tread-number"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeTreadNumber}
        title="Place tread number annotations on a stair."
      >
        Tread Number
      </button>
      <button
        type="button"
        data-testid="plan-annotate-keynote"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeKeynote}
        title="Place a keynote annotation at the view centre."
      >
        Keynote
      </button>
      <button
        type="button"
        data-testid="plan-annotate-span-direction"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeSpanDirection}
        title="Place a span direction arrow at the view centre."
      >
        Span Direction
      </button>
      <button
        type="button"
        data-testid="plan-annotate-pipe-legend"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placePipeLegend}
        title="Place a pipe system legend at the view centre."
      >
        Pipe Legend
      </button>
      <button
        type="button"
        data-testid="plan-annotate-duct-legend"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDuctLegend}
        title="Place a duct system legend at the view centre."
      >
        Duct Legend
      </button>
      <button
        type="button"
        data-testid="plan-annotate-detail-component"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDetailComponent}
        title="Place a 2D detail component (bolt) at the view centre."
      >
        Detail Component
      </button>
      <button
        type="button"
        data-testid="plan-annotate-repeating-detail"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeRepeatingDetail}
        title="Place a repeating detail component pattern 1000mm across the view centre."
      >
        Repeating Detail
      </button>
      <button
        type="button"
        data-testid="plan-annotate-detail-group"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeDetailGroup}
        title="Create a named detail group."
      >
        Detail Group
      </button>
      <button
        type="button"
        data-testid="plan-annotate-color-fill-legend"
        className="rounded border border-border px-2 py-0.5 text-left hover:bg-accent/20 hover:text-foreground"
        onClick={placeColorFillLegend}
        title="Place a color fill legend at the view centre offset."
      >
        Color Fill Legend
      </button>
    </div>
  );
}
