/**
 * PLN-01 — auto-tag helpers.
 *
 * `generateAutoTags(view, kind)` walks the active level for elements of
 * the requested kind ('room' | 'door' | 'window'), computes a centroid
 * for each, and returns one `placeTag` command per element with
 * `autoGenerated: true`.
 *
 * Doors and windows are positioned along their host wall using the
 * `alongT` parameter; rooms use the polygon centroid.
 */
import type { Element, XY } from '@bim-ai/core';

import { roomAreaM2 } from './roomArea';

export type AutoTagKind = 'room' | 'door' | 'window';

export type AutoTagViewContext = {
  planViewId: string;
  levelId: string;
  cropMinMm?: XY | null;
  cropMaxMm?: XY | null;
};

export type PlaceTagCmd = {
  type: 'placeTag';
  hostElementId: string;
  hostViewId: string;
  positionMm: XY;
  autoGenerated: true;
};

function pointInsideCrop(ctx: AutoTagViewContext, x: number, y: number): boolean {
  if (!ctx.cropMinMm || !ctx.cropMaxMm) return true;
  return (
    x >= ctx.cropMinMm.xMm &&
    x <= ctx.cropMaxMm.xMm &&
    y >= ctx.cropMinMm.yMm &&
    y <= ctx.cropMaxMm.yMm
  );
}

/** Polygon centroid (signed-area formula). Falls back to vertex
 * average for degenerate / zero-area outlines. */
export function polygonCentroid(points: XY[]): XY {
  if (points.length === 0) return { xMm: 0, yMm: 0 };
  if (points.length === 1) return points[0]!;
  let area = 0;
  let cx = 0;
  let cy = 0;
  for (let i = 0; i < points.length; i++) {
    const a = points[i]!;
    const b = points[(i + 1) % points.length]!;
    const cross = a.xMm * b.yMm - b.xMm * a.yMm;
    area += cross;
    cx += (a.xMm + b.xMm) * cross;
    cy += (a.yMm + b.yMm) * cross;
  }
  area *= 0.5;
  if (Math.abs(area) < 1e-6) {
    let sx = 0,
      sy = 0;
    for (const p of points) {
      sx += p.xMm;
      sy += p.yMm;
    }
    return { xMm: sx / points.length, yMm: sy / points.length };
  }
  return { xMm: cx / (6 * area), yMm: cy / (6 * area) };
}

function openingPosition(
  elementsById: Record<string, Element>,
  hostWallId: string,
  alongT: number,
): XY | null {
  const wall = elementsById[hostWallId];
  if (!wall || wall.kind !== 'wall') return null;
  const t = Math.max(0, Math.min(1, alongT));
  return {
    xMm: wall.start.xMm + (wall.end.xMm - wall.start.xMm) * t,
    yMm: wall.start.yMm + (wall.end.yMm - wall.start.yMm) * t,
  };
}

export function generateAutoTags(
  elementsById: Record<string, Element>,
  ctx: AutoTagViewContext,
  kind: AutoTagKind,
): PlaceTagCmd[] {
  const cmds: PlaceTagCmd[] = [];
  for (const el of Object.values(elementsById)) {
    if (el.kind !== kind) continue;
    let pos: XY | null = null;
    if (el.kind === 'room') {
      if (el.levelId !== ctx.levelId) continue;
      pos = polygonCentroid(el.outlineMm);
    } else if (el.kind === 'door' || el.kind === 'window') {
      const wall = elementsById[el.wallId];
      if (!wall || wall.kind !== 'wall' || wall.levelId !== ctx.levelId) continue;
      pos = openingPosition(elementsById, el.wallId, el.alongT);
    }
    if (!pos) continue;
    if (!pointInsideCrop(ctx, pos.xMm, pos.yMm)) continue;
    cmds.push({
      type: 'placeTag',
      hostElementId: el.id,
      hostViewId: ctx.planViewId,
      positionMm: pos,
      autoGenerated: true,
    });
  }
  return cmds;
}

// ---------------------------------------------------------------------------
// §4.11 — autoTagElements: enriched tag generation
// ---------------------------------------------------------------------------

export type AutoTagResult = {
  id: string;
  targetElementId: string;
  categoryKind: string;
  positionMm: XY;
  leaderEndMm: XY | null;
  fields: {
    mark?: string | null;
    typeName?: string | null;
    widthMm?: number | null;
    heightMm?: number | null;
    roomName?: string | null;
    roomNumber?: string | null;
    roomArea?: number | null; // area in mm²
  };
};

function lookupTypeName(
  typeId: string | null | undefined,
  elementsById: Record<string, Element>,
): string | null {
  if (!typeId) return null;
  const el = elementsById[typeId];
  if (!el) return null;
  return (el as { name?: string }).name?.trim() || null;
}

function wallPerpendicularOffset(wall: Extract<Element, { kind: 'wall' }>, offsetMm: number): XY {
  const dx = wall.end.xMm - wall.start.xMm;
  const dy = wall.end.yMm - wall.start.yMm;
  const len = Math.hypot(dx, dy) || 1;
  return { xMm: (-dy / len) * offsetMm, yMm: (dx / len) * offsetMm };
}

/**
 * §4.11.1 — generate enriched auto-tags for all taggable elements on the
 * active level. Each result has a stable `id` derived from the target element
 * so re-running never creates duplicates (caller checks by id).
 */
export function autoTagElements(elements: Element[], activeLevelId: string): AutoTagResult[] {
  const elementsById: Record<string, Element> = {};
  for (const el of elements) {
    elementsById[el.id] = el;
  }

  const results: AutoTagResult[] = [];

  for (const el of elements) {
    if (el.kind === 'door') {
      const wall = elementsById[el.wallId];
      if (!wall || wall.kind !== 'wall' || wall.levelId !== activeLevelId) continue;
      const onWall = openingPosition(elementsById, el.wallId, el.alongT);
      if (!onWall) continue;
      const perp = wallPerpendicularOffset(wall, 400);
      results.push({
        id: `auto-tag-${el.id}`,
        targetElementId: el.id,
        categoryKind: 'door',
        positionMm: { xMm: onWall.xMm + perp.xMm, yMm: onWall.yMm + perp.yMm },
        leaderEndMm: onWall,
        fields: {
          mark: el.id.slice(-3),
          typeName: lookupTypeName(el.familyTypeId, elementsById),
          widthMm: el.widthMm,
          heightMm: null,
        },
      });
    } else if (el.kind === 'window') {
      const wall = elementsById[el.wallId];
      if (!wall || wall.kind !== 'wall' || wall.levelId !== activeLevelId) continue;
      const onWall = openingPosition(elementsById, el.wallId, el.alongT);
      if (!onWall) continue;
      const perp = wallPerpendicularOffset(wall, 400);
      results.push({
        id: `auto-tag-${el.id}`,
        targetElementId: el.id,
        categoryKind: 'window',
        positionMm: { xMm: onWall.xMm + perp.xMm, yMm: onWall.yMm + perp.yMm },
        leaderEndMm: onWall,
        fields: {
          mark: el.id.slice(-3),
          typeName: lookupTypeName(el.familyTypeId, elementsById),
          widthMm: el.widthMm,
          heightMm: el.heightMm,
        },
      });
    } else if (el.kind === 'room') {
      if (el.levelId !== activeLevelId) continue;
      const pos = polygonCentroid(el.outlineMm);
      results.push({
        id: `auto-tag-${el.id}`,
        targetElementId: el.id,
        categoryKind: 'room',
        positionMm: pos,
        leaderEndMm: null,
        fields: {
          roomName: el.name || null,
          roomNumber: el.numberLabel ?? null,
          roomArea: roomAreaM2(el.outlineMm) * 1_000_000,
        },
      });
    } else if (el.kind === 'wall') {
      if (el.levelId !== activeLevelId) continue;
      const midMm: XY = {
        xMm: (el.start.xMm + el.end.xMm) / 2,
        yMm: (el.start.yMm + el.end.yMm) / 2,
      };
      const perp = wallPerpendicularOffset(el, 300);
      results.push({
        id: `auto-tag-${el.id}`,
        targetElementId: el.id,
        categoryKind: 'wall',
        positionMm: { xMm: midMm.xMm + perp.xMm, yMm: midMm.yMm + perp.yMm },
        leaderEndMm: midMm,
        fields: {
          typeName: lookupTypeName(el.wallTypeId, elementsById),
        },
      });
    }
  }

  return results;
}

/** Returns the single `clearAutoGeneratedAnnotations` command that wipes
 * existing auto-generated tags / dimensions for a given view. */
export function clearAutoAnnotationsCommand(
  planViewId: string,
  scope: 'dimensions' | 'tags' | 'both',
): { type: 'clearAutoGeneratedAnnotations'; hostViewId: string; scope: typeof scope } {
  return {
    type: 'clearAutoGeneratedAnnotations',
    hostViewId: planViewId,
    scope,
  };
}
