import { describe, expect, it } from 'vitest';
import type { Element } from '@bim-ai/core';

import { generateAutoDimensionChain } from './autoDimension';

function makeWall(
  id: string,
  start: { xMm: number; yMm: number },
  end: { xMm: number; yMm: number },
  levelId = 'lvl-1',
): Extract<Element, { kind: 'wall' }> {
  return {
    kind: 'wall',
    id,
    name: id,
    levelId,
    start,
    end,
    thicknessMm: 200,
    heightMm: 2800,
  };
}

describe('PLN-01 — generateAutoDimensionChain', () => {
  it('returns no commands when no perpendicular walls exist', () => {
    const elementsById: Record<string, Element> = {
      'w-1': makeWall('w-1', { xMm: 0, yMm: 0 }, { xMm: 5000, yMm: 0 }),
    };
    const cmds = generateAutoDimensionChain(
      elementsById,
      { planViewId: 'pv', levelId: 'lvl-1' },
      'x',
    );
    // The wall is horizontal (parallel to x), so it is NOT perpendicular
    // to the x-axis — chain along x finds no positions.
    expect(cmds).toEqual([]);
  });

  it('generates a chain along x for a rectangular room', () => {
    // Walls at x=0 and x=5000 (vertical), running y=0..3000.
    const elementsById: Record<string, Element> = {
      'w-w': makeWall('w-w', { xMm: 0, yMm: 0 }, { xMm: 0, yMm: 3000 }),
      'w-e': makeWall('w-e', { xMm: 5000, yMm: 0 }, { xMm: 5000, yMm: 3000 }),
      'w-mid': makeWall('w-mid', { xMm: 2000, yMm: 0 }, { xMm: 2000, yMm: 3000 }),
    };
    const cmds = generateAutoDimensionChain(
      elementsById,
      { planViewId: 'pv', levelId: 'lvl-1' },
      'x',
    );
    expect(cmds).toHaveLength(2);
    expect(cmds[0]!.type).toBe('createDimension');
    expect(cmds[0]!.autoGenerated).toBe(true);
    expect(cmds[0]!.aMm.xMm).toBe(0);
    expect(cmds[0]!.bMm.xMm).toBe(2000);
    expect(cmds[1]!.aMm.xMm).toBe(2000);
    expect(cmds[1]!.bMm.xMm).toBe(5000);
  });

  it('generates a chain along y for horizontal walls', () => {
    const elementsById: Record<string, Element> = {
      'w-s': makeWall('w-s', { xMm: 0, yMm: 0 }, { xMm: 5000, yMm: 0 }),
      'w-mid': makeWall('w-mid', { xMm: 0, yMm: 1500 }, { xMm: 5000, yMm: 1500 }),
      'w-n': makeWall('w-n', { xMm: 0, yMm: 3000 }, { xMm: 5000, yMm: 3000 }),
    };
    const cmds = generateAutoDimensionChain(
      elementsById,
      { planViewId: 'pv', levelId: 'lvl-1' },
      'y',
    );
    expect(cmds).toHaveLength(2);
    expect(cmds[0]!.aMm.yMm).toBe(0);
    expect(cmds[0]!.bMm.yMm).toBe(1500);
    expect(cmds[1]!.bMm.yMm).toBe(3000);
  });

  it('skips walls on other levels', () => {
    const elementsById: Record<string, Element> = {
      'w-w': makeWall('w-w', { xMm: 0, yMm: 0 }, { xMm: 0, yMm: 3000 }, 'lvl-1'),
      'w-other': makeWall('w-other', { xMm: 1000, yMm: 0 }, { xMm: 1000, yMm: 3000 }, 'lvl-2'),
      'w-e': makeWall('w-e', { xMm: 5000, yMm: 0 }, { xMm: 5000, yMm: 3000 }, 'lvl-1'),
    };
    const cmds = generateAutoDimensionChain(
      elementsById,
      { planViewId: 'pv', levelId: 'lvl-1' },
      'x',
    );
    // Only x=0 and x=5000 should remain.
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.aMm.xMm).toBe(0);
    expect(cmds[0]!.bMm.xMm).toBe(5000);
  });

  it('respects crop bounds when supplied', () => {
    const elementsById: Record<string, Element> = {
      'w-w': makeWall('w-w', { xMm: 0, yMm: 0 }, { xMm: 0, yMm: 3000 }),
      'w-e': makeWall('w-e', { xMm: 5000, yMm: 0 }, { xMm: 5000, yMm: 3000 }),
      'w-far': makeWall('w-far', { xMm: 99_000, yMm: 0 }, { xMm: 99_000, yMm: 3000 }),
    };
    const cmds = generateAutoDimensionChain(
      elementsById,
      {
        planViewId: 'pv',
        levelId: 'lvl-1',
        cropMinMm: { xMm: -100, yMm: -100 },
        cropMaxMm: { xMm: 6000, yMm: 4000 },
      },
      'x',
    );
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.bMm.xMm).toBe(5000);
  });

  it('marks each emitted dimension as autoGenerated for safe re-runs', () => {
    const elementsById: Record<string, Element> = {
      'w-w': makeWall('w-w', { xMm: 0, yMm: 0 }, { xMm: 0, yMm: 3000 }),
      'w-e': makeWall('w-e', { xMm: 5000, yMm: 0 }, { xMm: 5000, yMm: 3000 }),
    };
    const cmds = generateAutoDimensionChain(
      elementsById,
      { planViewId: 'pv', levelId: 'lvl-1' },
      'x',
    );
    for (const c of cmds) {
      expect(c.autoGenerated).toBe(true);
      expect(c.levelId).toBe('lvl-1');
    }
  });
});
