/**
 * PLN-01 — auto-dimension chain helpers.
 *
 * `generateAutoDimensionChain(view, axis)` finds every wall on the
 * active level whose run is roughly perpendicular to `axis`, projects
 * each endpoint onto that axis, sorts the resulting positions, and
 * emits a chain of `createDimension` commands between consecutive
 * unique positions.
 *
 * The dimension chain is offset to one edge of the model bounding box
 * (south for axis='x', west for axis='y') so it does not overlap the
 * geometry. All produced commands carry `autoGenerated: true` so a
 * follow-up `clearAutoGeneratedAnnotations` can wipe them on re-run.
 */
import type { Element, XY } from '@bim-ai/core';

export type AutoDimensionAxis = 'x' | 'y';

export type AutoDimensionViewContext = {
  /** plan_view id (used so callers can scope clear-and-regenerate). */
  planViewId: string;
  /** Active level on the plan view — restricts the wall sweep. */
  levelId: string;
  /** Optional crop bounds; when provided, walls fully outside the crop
   * are excluded. */
  cropMinMm?: XY | null;
  cropMaxMm?: XY | null;
};

export type CreateDimensionCmd = {
  type: 'createDimension';
  levelId: string;
  aMm: XY;
  bMm: XY;
  offsetMm: XY;
  autoGenerated: true;
  name: string;
};

const PERPENDICULAR_TOLERANCE_DEG = 15;
const DUPLICATE_TOLERANCE_MM = 1;
const CHAIN_OFFSET_MM = 800;

/** Returns walls whose run direction is within ±tolerance of perpendicular
 * to the supplied axis. For axis='x' (chain along x), perpendicular walls
 * are those running primarily in y. */
function isWallPerpendicularToAxis(
  wall: Extract<Element, { kind: 'wall' }>,
  axis: AutoDimensionAxis,
): boolean {
  const dx = wall.end.xMm - wall.start.xMm;
  const dy = wall.end.yMm - wall.start.yMm;
  if (Math.abs(dx) < 1 && Math.abs(dy) < 1) return false;
  const angleDeg = (Math.atan2(dy, dx) * 180) / Math.PI;
  // For axis='x' we want a wall perpendicular to x = parallel to y =
  // angle near ±90.  For axis='y', angle near 0 / 180.
  const target = axis === 'x' ? 90 : 0;
  const norm = Math.abs(((((angleDeg - target) % 180) + 180) % 180) - 0);
  const wrapped = norm > 90 ? 180 - norm : norm;
  return wrapped <= PERPENDICULAR_TOLERANCE_DEG;
}

function dedupeSorted(values: number[], tolMm = DUPLICATE_TOLERANCE_MM): number[] {
  const sorted = [...values].sort((a, b) => a - b);
  const out: number[] = [];
  for (const v of sorted) {
    if (out.length === 0 || Math.abs(v - out[out.length - 1]!) > tolMm) {
      out.push(v);
    }
  }
  return out;
}

function modelBoundsMm(
  walls: Array<Extract<Element, { kind: 'wall' }>>,
): { minXmm: number; maxXmm: number; minYmm: number; maxYmm: number } | null {
  if (walls.length === 0) return null;
  let minX = Infinity,
    maxX = -Infinity,
    minY = Infinity,
    maxY = -Infinity;
  for (const w of walls) {
    minX = Math.min(minX, w.start.xMm, w.end.xMm);
    maxX = Math.max(maxX, w.start.xMm, w.end.xMm);
    minY = Math.min(minY, w.start.yMm, w.end.yMm);
    maxY = Math.max(maxY, w.start.yMm, w.end.yMm);
  }
  return { minXmm: minX, maxXmm: maxX, minYmm: minY, maxYmm: maxY };
}

function pointInsideCrop(ctx: AutoDimensionViewContext, xMm: number, yMm: number): boolean {
  if (!ctx.cropMinMm || !ctx.cropMaxMm) return true;
  return (
    xMm >= ctx.cropMinMm.xMm &&
    xMm <= ctx.cropMaxMm.xMm &&
    yMm >= ctx.cropMinMm.yMm &&
    yMm <= ctx.cropMaxMm.yMm
  );
}

export function generateAutoDimensionChain(
  elementsById: Record<string, Element>,
  ctx: AutoDimensionViewContext,
  axis: AutoDimensionAxis,
): CreateDimensionCmd[] {
  const walls: Array<Extract<Element, { kind: 'wall' }>> = [];
  for (const el of Object.values(elementsById)) {
    if (el.kind !== 'wall') continue;
    if (el.levelId !== ctx.levelId) continue;
    if (!isWallPerpendicularToAxis(el, axis)) continue;
    // Crop filter: include the wall when at least one endpoint sits
    // inside the crop frame. (Walls fully outside contribute nothing.)
    const inA = pointInsideCrop(ctx, el.start.xMm, el.start.yMm);
    const inB = pointInsideCrop(ctx, el.end.xMm, el.end.yMm);
    if (!inA && !inB) continue;
    walls.push(el);
  }
  if (walls.length === 0) return [];
  const positions: number[] = [];
  for (const w of walls) {
    if (axis === 'x') {
      positions.push(w.start.xMm, w.end.xMm);
    } else {
      positions.push(w.start.yMm, w.end.yMm);
    }
  }
  const unique = dedupeSorted(positions);
  if (unique.length < 2) return [];

  const bounds = modelBoundsMm(walls);
  if (!bounds) return [];

  // Chain offset — south for x-axis chains, west for y-axis chains.
  const offY = axis === 'x' ? bounds.minYmm - CHAIN_OFFSET_MM : 0;
  const offX = axis === 'y' ? bounds.minXmm - CHAIN_OFFSET_MM : 0;
  // The dimension's `offsetMm` is the perpendicular shift from the
  // a-b segment to the dim line. createDimension's existing convention
  // (PlanCanvas) uses {xMm: -dy/m * 450, yMm: dx/m * 450}; for an
  // axis-aligned chain we can supply that directly.
  const offsetMm: XY =
    axis === 'x' ? { xMm: 0, yMm: -CHAIN_OFFSET_MM } : { xMm: -CHAIN_OFFSET_MM, yMm: 0 };

  const cmds: CreateDimensionCmd[] = [];
  for (let i = 0; i < unique.length - 1; i++) {
    const a = unique[i]!;
    const b = unique[i + 1]!;
    if (axis === 'x') {
      cmds.push({
        type: 'createDimension',
        levelId: ctx.levelId,
        aMm: { xMm: a, yMm: bounds.minYmm },
        bMm: { xMm: b, yMm: bounds.minYmm },
        offsetMm,
        autoGenerated: true,
        name: `Auto dim X ${i + 1}`,
      });
    } else {
      cmds.push({
        type: 'createDimension',
        levelId: ctx.levelId,
        aMm: { xMm: bounds.minXmm, yMm: a },
        bMm: { xMm: bounds.minXmm, yMm: b },
        offsetMm,
        autoGenerated: true,
        name: `Auto dim Y ${i + 1}`,
      });
    }
  }
  // Reference offset shifts so the dim line sits outboard of the model.
  void offX;
  void offY;
  return cmds;
}

// ---------------------------------------------------------------------------
// §4.1 — autoDimensionWalls + tagAllRooms
// ---------------------------------------------------------------------------

const AUTO_DIM_OFFSET_MM = 1200;

/**
 * Auto-dimensions all walls on a given level.
 * Returns an array of new dimension elements (kind='dimension').
 */
export function autoDimensionWalls(
  levelId: string,
  elementsById: Record<string, Element | undefined>,
): Extract<Element, { kind: 'dimension' }>[] {
  const walls: Array<Extract<Element, { kind: 'wall' }>> = [];
  for (const el of Object.values(elementsById)) {
    if (!el || el.kind !== 'wall') continue;
    if (el.levelId !== levelId) continue;
    walls.push(el);
  }
  if (walls.length === 0) return [];

  const dims: Extract<Element, { kind: 'dimension' }>[] = [];
  for (const wall of walls) {
    const dx = wall.end.xMm - wall.start.xMm;
    const dy = wall.end.yMm - wall.start.yMm;
    const isHorizontal = Math.abs(dx) >= Math.abs(dy);

    // Offset perpendicular to the wall so the dim line doesn't overlap.
    const offsetMm = isHorizontal
      ? { xMm: 0, yMm: -AUTO_DIM_OFFSET_MM }
      : { xMm: -AUTO_DIM_OFFSET_MM, yMm: 0 };

    dims.push({
      kind: 'dimension',
      id: crypto.randomUUID(),
      name: `Auto dim ${wall.id}`,
      levelId,
      aMm: { xMm: wall.start.xMm, yMm: wall.start.yMm },
      bMm: { xMm: wall.end.xMm, yMm: wall.end.yMm },
      offsetMm,
      autoGenerated: true,
    });
  }
  return dims;
}

/**
 * Creates a text_tag (room tag) at the centroid of every room on the level.
 * Returns an array of new tag elements.
 */
export function tagAllRooms(
  levelId: string,
  elementsById: Record<string, Element | undefined>,
): Extract<Element, { kind: 'text_tag' }>[] {
  const tags: Extract<Element, { kind: 'text_tag' }>[] = [];
  for (const el of Object.values(elementsById)) {
    if (!el || el.kind !== 'room') continue;
    if (el.levelId !== levelId) continue;

    const pts = el.outlineMm;
    if (!pts || pts.length === 0) continue;

    // Centroid = average of outline points.
    let sumX = 0;
    let sumY = 0;
    for (const pt of pts) {
      sumX += pt.xMm;
      sumY += pt.yMm;
    }
    const xMm = sumX / pts.length;
    const yMm = sumY / pts.length;

    tags.push({
      kind: 'text_tag',
      id: crypto.randomUUID(),
      positionMm: { xMm, yMm },
      label: el.name || 'Room',
      levelId,
    });
  }
  return tags;
}
