import { describe, expect, it } from 'vitest';
import type { Element } from '@bim-ai/core';

import { clearAutoAnnotationsCommand, generateAutoTags, polygonCentroid } from './autoTags';

const wallId = 'w-1';
const wall: Extract<Element, { kind: 'wall' }> = {
  kind: 'wall',
  id: wallId,
  name: 'W',
  levelId: 'lvl-1',
  start: { xMm: 0, yMm: 0 },
  end: { xMm: 6000, yMm: 0 },
  thicknessMm: 200,
  heightMm: 2800,
};

const room: Extract<Element, { kind: 'room' }> = {
  kind: 'room',
  id: 'room-1',
  name: 'Living',
  levelId: 'lvl-1',
  outlineMm: [
    { xMm: 0, yMm: 0 },
    { xMm: 4000, yMm: 0 },
    { xMm: 4000, yMm: 3000 },
    { xMm: 0, yMm: 3000 },
  ],
};

const door: Extract<Element, { kind: 'door' }> = {
  kind: 'door',
  id: 'door-1',
  name: 'Door',
  wallId,
  alongT: 0.5,
  widthMm: 900,
};

const window_: Extract<Element, { kind: 'window' }> = {
  kind: 'window',
  id: 'win-1',
  name: 'Window',
  wallId,
  alongT: 0.25,
  widthMm: 1200,
  sillHeightMm: 900,
  heightMm: 1500,
};

describe('PLN-01 — polygonCentroid', () => {
  it('returns the centroid of a square', () => {
    const c = polygonCentroid([
      { xMm: 0, yMm: 0 },
      { xMm: 1000, yMm: 0 },
      { xMm: 1000, yMm: 1000 },
      { xMm: 0, yMm: 1000 },
    ]);
    expect(c.xMm).toBeCloseTo(500);
    expect(c.yMm).toBeCloseTo(500);
  });

  it('falls back to vertex average for degenerate polygons', () => {
    const c = polygonCentroid([
      { xMm: 0, yMm: 0 },
      { xMm: 1000, yMm: 0 },
    ]);
    expect(c.xMm).toBe(500);
    expect(c.yMm).toBe(0);
  });
});

describe('PLN-01 — generateAutoTags rooms', () => {
  it('emits one placeTag per room at the centroid', () => {
    const elementsById: Record<string, Element> = { [room.id]: room };
    const cmds = generateAutoTags(elementsById, { planViewId: 'pv', levelId: 'lvl-1' }, 'room');
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.type).toBe('placeTag');
    expect(cmds[0]!.hostElementId).toBe('room-1');
    expect(cmds[0]!.hostViewId).toBe('pv');
    expect(cmds[0]!.autoGenerated).toBe(true);
    expect(cmds[0]!.positionMm.xMm).toBeCloseTo(2000);
    expect(cmds[0]!.positionMm.yMm).toBeCloseTo(1500);
  });

  it('skips rooms on a different level', () => {
    const otherRoom = { ...room, id: 'room-2', levelId: 'lvl-2' };
    const elementsById: Record<string, Element> = {
      [room.id]: room,
      [otherRoom.id]: otherRoom as Element,
    };
    const cmds = generateAutoTags(elementsById, { planViewId: 'pv', levelId: 'lvl-1' }, 'room');
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.hostElementId).toBe('room-1');
  });

  it('respects crop bounds', () => {
    const elementsById: Record<string, Element> = { [room.id]: room };
    const cmds = generateAutoTags(
      elementsById,
      {
        planViewId: 'pv',
        levelId: 'lvl-1',
        cropMinMm: { xMm: 5000, yMm: 5000 },
        cropMaxMm: { xMm: 6000, yMm: 6000 },
      },
      'room',
    );
    expect(cmds).toEqual([]);
  });
});

describe('PLN-01 — generateAutoTags doors and windows', () => {
  it('positions a door tag at its alongT on the host wall', () => {
    const elementsById: Record<string, Element> = {
      [wallId]: wall,
      [door.id]: door,
    };
    const cmds = generateAutoTags(elementsById, { planViewId: 'pv', levelId: 'lvl-1' }, 'door');
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.positionMm).toEqual({ xMm: 3000, yMm: 0 });
  });

  it('positions a window tag at its alongT on the host wall', () => {
    const elementsById: Record<string, Element> = {
      [wallId]: wall,
      [window_.id]: window_,
    };
    const cmds = generateAutoTags(elementsById, { planViewId: 'pv', levelId: 'lvl-1' }, 'window');
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.positionMm).toEqual({ xMm: 1500, yMm: 0 });
  });

  it('skips openings whose host wall is on a different level', () => {
    const otherWall = { ...wall, id: 'w-2', levelId: 'lvl-2' };
    const otherDoor = { ...door, id: 'door-2', wallId: 'w-2' };
    const elementsById: Record<string, Element> = {
      [wallId]: wall,
      [door.id]: door,
      [otherWall.id]: otherWall as Element,
      [otherDoor.id]: otherDoor as Element,
    };
    const cmds = generateAutoTags(elementsById, { planViewId: 'pv', levelId: 'lvl-1' }, 'door');
    expect(cmds).toHaveLength(1);
    expect(cmds[0]!.hostElementId).toBe('door-1');
  });
});

describe('PLN-01 — clearAutoAnnotationsCommand', () => {
  it('returns the clear command scoped to the supplied view', () => {
    const cmd = clearAutoAnnotationsCommand('pv-1', 'tags');
    expect(cmd.type).toBe('clearAutoGeneratedAnnotations');
    expect(cmd.hostViewId).toBe('pv-1');
    expect(cmd.scope).toBe('tags');
  });
});
