import type { Element, XY } from '@bim-ai/core';

export type PlaceManualTagCmd = {
  type: 'placeTag';
  hostElementId: string;
  hostViewId: string;
  positionMm: XY;
  autoGenerated: false;
};

export type TaggableElement = Extract<Element, { kind: 'room' | 'door' | 'window' }>;

export function isTaggableElement(el: Element | undefined): el is TaggableElement {
  return el?.kind === 'room' || el?.kind === 'door' || el?.kind === 'window';
}

export function placeTagByCategoryCommand(
  elementsById: Record<string, Element>,
  hostViewId: string | null | undefined,
  hostElementId: string | null | undefined,
  positionMm: XY,
): PlaceManualTagCmd | null {
  if (!hostViewId || !hostElementId) return null;
  const host = elementsById[hostElementId];
  if (!isTaggableElement(host)) return null;
  return {
    type: 'placeTag',
    hostElementId,
    hostViewId,
    positionMm,
    autoGenerated: false,
  };
}

export function manualPlacedTagLabel(
  tag: Extract<Element, { kind: 'placed_tag' }>,
  elementsById: Record<string, Element>,
): string {
  const override = tag.textOverride?.trim();
  if (override) return override;

  const host = elementsById[tag.hostElementId];
  if (!host) return 'Tag';
  if (host.kind === 'room') return host.name?.trim() || 'Room';
  if (host.kind === 'door') return host.name?.trim() || 'Door';
  if (host.kind === 'window') return host.name?.trim() || 'Window';
  return 'Tag';
}
