import { describe, expect, it } from 'vitest';
import type { Element } from '@bim-ai/core';

import { manualPlacedTagLabel, placeTagByCategoryCommand } from './manualTags';

const elementsById: Record<string, Element> = {
  room: {
    kind: 'room',
    id: 'room',
    name: 'Living',
    levelId: 'lv',
    outlineMm: [
      { xMm: 0, yMm: 0 },
      { xMm: 1000, yMm: 0 },
      { xMm: 1000, yMm: 1000 },
    ],
  },
  door: {
    kind: 'door',
    id: 'door',
    name: 'D-101',
    wallId: 'wall',
    alongT: 0.5,
    widthMm: 900,
  },
  wall: {
    kind: 'wall',
    id: 'wall',
    name: 'Wall',
    levelId: 'lv',
    start: { xMm: 0, yMm: 0 },
    end: { xMm: 2000, yMm: 0 },
    thicknessMm: 200,
    heightMm: 3000,
  },
};

describe('manual Tag by Category helpers', () => {
  it('emits a manual placeTag command for taggable hosts', () => {
    expect(
      placeTagByCategoryCommand(elementsById, 'pv', 'room', { xMm: 250, yMm: 500 }),
    ).toEqual({
      type: 'placeTag',
      hostElementId: 'room',
      hostViewId: 'pv',
      positionMm: { xMm: 250, yMm: 500 },
      autoGenerated: false,
    });
  });

  it('ignores unsupported host categories before the backend rejects them', () => {
    expect(placeTagByCategoryCommand(elementsById, 'pv', 'wall', { xMm: 0, yMm: 0 })).toBeNull();
    expect(placeTagByCategoryCommand(elementsById, 'pv', 'missing', { xMm: 0, yMm: 0 })).toBeNull();
    expect(placeTagByCategoryCommand(elementsById, null, 'room', { xMm: 0, yMm: 0 })).toBeNull();
  });

  it('labels placed tags from override, then host name, then category fallback', () => {
    expect(
      manualPlacedTagLabel(
        {
          kind: 'placed_tag',
          id: 'tag-1',
          hostElementId: 'room',
          hostViewId: 'pv',
          positionMm: { xMm: 0, yMm: 0 },
          textOverride: 'Suite A',
        },
        elementsById,
      ),
    ).toBe('Suite A');
    expect(
      manualPlacedTagLabel(
        {
          kind: 'placed_tag',
          id: 'tag-2',
          hostElementId: 'door',
          hostViewId: 'pv',
          positionMm: { xMm: 0, yMm: 0 },
        },
        elementsById,
      ),
    ).toBe('D-101');
  });
});
