import type { Element, XY } from '@bim-ai/core';

import {
  familyInstanceProjectCategoryKey,
  familyTypeProjectCategoryLabel,
} from '../families/familyPlacementRuntime';

export type PlaceManualTagCmd = {
  type: 'placeTag';
  hostElementId: string;
  hostViewId: string;
  positionMm: XY;
  autoGenerated: false;
};

export type TaggableElement = Extract<
  Element,
  { kind: 'room' | 'door' | 'window' | 'family_instance' }
>;

export function isTaggableElement(
  el: Element | undefined,
  elementsById: Record<string, Element> = {},
): el is TaggableElement {
  if (el?.kind === 'room' || el?.kind === 'door' || el?.kind === 'window') return true;
  if (el?.kind !== 'family_instance') return false;
  return familyInstanceProjectCategoryKey(el, elementsById) !== 'family_instance';
}

export function placeTagByCategoryCommand(
  elementsById: Record<string, Element>,
  hostViewId: string | null | undefined,
  hostElementId: string | null | undefined,
  positionMm: XY,
): PlaceManualTagCmd | null {
  if (!hostViewId || !hostElementId) return null;
  const host = elementsById[hostElementId];
  if (!isTaggableElement(host, elementsById)) return null;
  return {
    type: 'placeTag',
    hostElementId,
    hostViewId,
    positionMm,
    autoGenerated: false,
  };
}

export function manualPlacedTagLabel(
  tag: Extract<Element, { kind: 'placed_tag' }>,
  elementsById: Record<string, Element>,
): string {
  const override = tag.textOverride?.trim();
  if (override) return override;

  const host = elementsById[tag.hostElementId];
  if (!host) return 'Tag';
  if (host.kind === 'room') return host.name?.trim() || 'Room';
  if (host.kind === 'door') return host.name?.trim() || 'Door';
  if (host.kind === 'window') return host.name?.trim() || 'Window';
  if (host.kind === 'family_instance') {
    const type = elementsById[host.familyTypeId];
    if (host.name?.trim()) return host.name.trim();
    if (type?.kind === 'family_type') {
      const typeName = type.name?.trim() || String(type.parameters.name ?? '').trim();
      if (typeName) return typeName;
      return familyTypeProjectCategoryLabel(type);
    }
  }
  return 'Tag';
}
