import {
  CAPABILITY_VIEW_MODES,
  type CommandCapabilityDraft,
} from './commandCapabilities';

export const NAVIGATION_CAPABILITIES: CommandCapabilityDraft[] = [
  {
    id: 'navigate.plan',
    label: 'Go to Plan',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.3d',
    label: 'Go to 3D',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.section',
    label: 'Go to Section',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.sheet',
    label: 'Go to Sheet',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.schedule',
    label: 'Go to Schedule',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.architecture',
    label: 'Switch lens: Architecture',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.structure',
    label: 'Switch lens: Structure',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.mep',
    label: 'Switch lens: MEP',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.coordination',
    label: 'Switch lens: Coordination',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.fire-safety',
    label: 'Switch lens: Fire Safety',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.energy',
    label: 'Switch lens: Energieberatung',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.construction-lens',
    label: 'Switch lens: Bauausfuehrung',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.sustainability',
    label: 'Switch lens: Sustainability / LCA',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'navigate.cost-quantity',
    label: 'Switch lens: Cost and Quantity',
    owner: 'cmdPalette/defaultCommands',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.phase.demolition',
    label: 'Set view phase: Demolition',
    owner: 'cmdPalette/defaultCommands',
    group: 'view',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'secondary-sidebar'],
    executionSurface: 'secondary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.phase.existing',
    label: 'Set view phase: Existing',
    owner: 'cmdPalette/defaultCommands',
    group: 'view',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'secondary-sidebar'],
    executionSurface: 'secondary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.phase.new',
    label: 'Set view phase: New Construction',
    owner: 'cmdPalette/defaultCommands',
    group: 'view',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'secondary-sidebar'],
    executionSurface: 'secondary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.plan.detail.coarse',
    label: 'Plan Detail: Coarse',
    owner: 'cmdPalette/defaultCommands',
    group: 'view',
    scope: 'view',
    intendedModes: ['plan', 'section'],
    surfaces: ['cmd-k', 'secondary-sidebar'],
    executionSurface: 'secondary-sidebar',
    preconditions: ['active-plan-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.plan.detail.medium',
    label: 'Plan Detail: Medium',
    owner: 'cmdPalette/defaultCommands',
    group: 'view',
    scope: 'view',
    intendedModes: ['plan', 'section'],
    surfaces: ['cmd-k', 'secondary-sidebar'],
    executionSurface: 'secondary-sidebar',
    preconditions: ['active-plan-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.plan.detail.fine',
    label: 'Plan Detail: Fine',
    owner: 'cmdPalette/defaultCommands',
    group: 'view',
    scope: 'view',
    intendedModes: ['plan', 'section'],
    surfaces: ['cmd-k', 'secondary-sidebar'],
    executionSurface: 'secondary-sidebar',
    preconditions: ['active-plan-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
];

export const SYSTEM_CAPABILITIES: CommandCapabilityDraft[] = [
  {
    id: 'theme.toggle',
    label: 'Toggle Theme',
    owner: 'cmdPalette/defaultCommands',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'theme.light',
    label: 'Switch Theme: Light',
    owner: 'cmdPalette/defaultCommands',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'theme.dark',
    label: 'Switch Theme: Dark',
    owner: 'cmdPalette/defaultCommands',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'settings.language.toggle',
    label: 'Toggle Language',
    owner: 'cmdPalette/defaultCommands',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'settings.language.en',
    label: 'Language: English',
    owner: 'cmdPalette/defaultCommands',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'settings.language.de',
    label: 'Language: Deutsch',
    owner: 'cmdPalette/defaultCommands',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'project.open-menu',
    label: 'Open Project Menu',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'project.open-settings',
    label: 'Open Project Setup',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'benchmark.two-storey-stair.replay-fixture',
    label: 'Replay Two-Storey Stair Fixture',
    owner: 'cmdPalette/defaultCommands',
    group: 'model',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    executionKind: 'commits-bundle',
    resultKind: 'model-elements',
    status: 'implemented',
    usabilityScore: 8,
    agentEquivalent: {
      completionKind: 'raw-command',
      toolId: 'two-storey-house-with-stair:mcp-cli-command-bundle',
      notes:
        'Submits or validates replay of the exact two-storey stair fixture payload from spec/benchmarks/two-storey-house-with-stair/mcp-cli-command-bundle.json.',
    },
    notes:
      'M3-R Cmd+K bridge: deterministic benchmark replay payload. Does not convert tool activators into completed semantic authoring.',
  },
  {
    id: 'view.create.floor-plan',
    label: 'Create Floor Plan',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'document',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: ['has-level'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.create.3d-view',
    label: 'Create 3D Saved View',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'document',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: ['3d-camera-pose'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.create.section',
    label: 'Create Section View',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'document',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.create.sheet',
    label: 'Create Sheet',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'document',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'view.create.schedule',
    label: 'Create Schedule',
    owner: 'workspace/WorkspaceLeftRail',
    group: 'document',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'primary-sidebar',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'shell.command-palette',
    label: 'Open Command Search',
    owner: 'workspace/shell/RibbonBar',
    group: 'navigate',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'ribbon', 'header'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'project.save-snapshot',
    label: 'Save Snapshot',
    owner: 'workspace/project/ProjectMenu',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'project.restore-snapshot',
    label: 'Restore Snapshot',
    owner: 'workspace/project/ProjectMenu',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'project.share-presentation',
    label: 'Share Project',
    owner: 'workspace/share/SharePresentationModal',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'header'],
    executionSurface: 'modal',
    preconditions: ['presentation-pages'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'file.link-ifc',
    label: 'Link IFC File…',
    owner: 'workspace/project/ManageLinksDialog',
    group: 'system',
    scope: 'document',
    intendedModes: ['plan', '3d'],
    surfaces: ['cmd-k'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes: '§12.1.1: opens ManageLinksDialog IFC section for client-side IFC file linking.',
  },
  {
    id: 'file.link-pdf',
    label: 'Link PDF Underlay',
    owner: 'workspace/ManageLinksDialog',
    group: 'file',
    scope: 'global',
    intendedModes: ['plan', '3d'],
    surfaces: ['cmd-k', 'dialog'],
    executionSurface: 'store',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes:
      '§12.1.1: links a PDF/image as a plan underlay; stored as link_pdf element with opacity, position, scale.',
  },
  {
    id: 'file.link-pointcloud',
    label: 'Link Point Cloud',
    owner: 'workspace/project/ManageLinksDialog',
    group: 'file',
    scope: 'global',
    intendedModes: ['plan', '3d'],
    surfaces: ['dialog', 'cmd-k'],
    executionSurface: 'store',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes:
      '§12.1.1: link_pointcloud element type + AddPointCloudCmd/RemovePointCloudCmd/TogglePointCloudCmd + ManageLinksDialog Point Clouds section with visibility toggle + remove button + add button.',
  },
  {
    id: 'view.help-search',
    label: 'In-Product Help Search',
    owner: 'workspace/HelpSearchPanel',
    group: 'view',
    scope: 'global',
    intendedModes: ['plan', '3d'],
    surfaces: ['toolbar', 'cmd-k'],
    executionSurface: 'local-state',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes:
      '§1.6.4: ? keyboard shortcut opens HelpSearchPanel with 25 indexed help topics; searchHelpTopics() filters by title/summary/keywords.',
  },
  {
    id: 'project.manage-links',
    label: 'Manage Project Links',
    owner: 'workspace/project/ManageLinksDialog',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'project.import.ifc',
    label: 'Import IFC Link',
    owner: 'workspace/project/ProjectMenu',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes: 'Cmd+K bridges to project resources where file-picker ownership lives.',
  },
  {
    id: 'project.import.dxf',
    label: 'Import DXF Underlay',
    owner: 'workspace/project/ProjectMenu',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes: 'Cmd+K bridges to project resources where DXF options and file-picker live.',
  },
  {
    id: 'file.import-dxf-terrain',
    label: 'Import Terrain from DXF…',
    owner: 'workspace/DxfImportDialog',
    group: 'document',
    scope: 'model',
    intendedModes: ['plan', '3d'],
    surfaces: ['cmd-k'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes: '§12.2.2: import DXF contour lines as a toposolid terrain element.',
  },
  {
    id: 'file.print-current-view',
    label: 'Print Current View',
    owner: 'workspace/sheets/PrintPlotDialog',
    group: 'document',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes: 'Opens the browser Print/Plot dialog for the active view.',
  },
  {
    id: 'file.import-ifc',
    label: 'Import IFC…',
    owner: 'import/IfcImportDialog',
    group: 'document',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes:
      'Opens the IFC STEP import dialog to convert IFC entities into bim-ai elements (§12.1.2).',
  },
  {
    id: 'library.open-family',
    label: 'Open Family Library',
    owner: 'families/FamilyLibraryPanel',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'ribbon', 'secondary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'library.open-material-browser',
    label: 'Open Material Browser',
    owner: 'familyEditor/MaterialBrowserDialog',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar', 'element-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'library.open-appearance-asset-browser',
    label: 'Open Appearance Asset Browser',
    owner: 'familyEditor/AppearanceAssetBrowserDialog',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar', 'element-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'help.keyboard-shortcuts',
    label: 'Open Keyboard Shortcuts',
    owner: 'cmd/CheatsheetModal',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'help.replay-onboarding-tour',
    label: 'Replay Onboarding Tour',
    owner: 'onboarding/OnboardingTour',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'tabs.close-inactive',
    label: 'Close Inactive Views',
    owner: 'workspace/shell/TabBar',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'header'],
    executionSurface: 'global',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
    notes: 'Header tab overflow menu plus Cmd+K fallback.',
  },
  {
    id: 'tabs.split.left',
    label: 'Split Active View Left',
    owner: 'workspace/Workspace',
    group: 'system',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['active-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'tabs.split.right',
    label: 'Split Active View Right',
    owner: 'workspace/Workspace',
    group: 'system',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['active-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'tabs.split.top',
    label: 'Split Active View Top',
    owner: 'workspace/Workspace',
    group: 'system',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['active-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'tabs.split.bottom',
    label: 'Split Active View Bottom',
    owner: 'workspace/Workspace',
    group: 'system',
    scope: 'view',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['active-view'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'shell.toggle-primary-sidebar',
    label: 'Toggle Primary Sidebar',
    owner: 'workspace/Workspace',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'header'],
    executionSurface: 'header',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'shell.toggle-element-sidebar',
    label: 'Toggle Element Sidebar',
    owner: 'workspace/Workspace',
    group: 'system',
    scope: 'universal',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'element-sidebar'],
    executionSurface: 'element-sidebar',
    preconditions: ['has-selection'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'advisor.open',
    label: 'Open Advisor',
    owner: 'workspace/shell/StatusBar',
    group: 'review',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'footer'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'jobs.open',
    label: 'Open Jobs',
    owner: 'jobs/JobsPanel',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'footer'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'milestone.open',
    label: 'Open Milestone Dialog',
    owner: 'workspace/project/ProjectMenu',
    group: 'system',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'primary-sidebar'],
    executionSurface: 'modal',
    preconditions: [],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'advisor.apply-first-fix',
    label: 'Apply First Advisor Fix',
    owner: 'advisor/AdvisorPanel',
    group: 'review',
    scope: 'model',
    intendedModes: [...CAPABILITY_VIEW_MODES],
    surfaces: ['cmd-k', 'dialog'],
    executionSurface: 'modal',
    preconditions: ['advisor-finding-with-quick-fix'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'structural.delete-duplicate-wall',
    label: 'Delete Duplicate Wall',
    owner: 'advisor/structuralAdvisorViolations',
    group: 'review',
    scope: 'model',
    intendedModes: ['plan', '3d'],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['advisor-finding-with-quick-fix'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'structural.detach-orphan',
    label: 'Detach Orphaned Hosted Element',
    owner: 'advisor/structuralAdvisorViolations',
    group: 'review',
    scope: 'model',
    intendedModes: ['plan', '3d'],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['advisor-finding-with-quick-fix'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'tool.roof-from-walls',
    label: 'Roof by Footprint from Selected Walls',
    owner: 'cmdPalette/defaultCommands',
    group: 'create',
    scope: 'selection',
    intendedModes: ['plan'],
    surfaces: ['cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['3-or-more-walls-selected'],
    status: 'implemented',
    usabilityScore: 8,
  },
  {
    id: 'wall.create-parts',
    label: 'Create Parts',
    owner: 'workspace/shell/RibbonBar',
    group: 'edit',
    scope: 'selection',
    intendedModes: ['plan', '3d'],
    surfaces: ['ribbon', 'cmd-k'],
    executionSurface: 'canvas',
    preconditions: ['wall-selected'],
    status: 'implemented',
    usabilityScore: 8,
  },
];

