import type { DisciplineTag, Text3dFontFamily, XY, XYZ } from '../index';
import type { AgentTrace } from '../modelContracts';

/** PLN-01 / ANN-01 — view-local placed tag (room / door / window).
 * `autoGenerated:true` marks tags emitted by the Auto-Tag tools so a
 * re-run can remove them before regenerating. */
export type PlacedTagElement = {
  kind: 'placed_tag';
  id: string;
  hostElementId: string;
  hostViewId: string;
  positionMm: XY;
  tagDefinitionId?: string | null;
  textOverride?: string | null;
  autoGenerated?: boolean;
  /** §4.11 — element kind being tagged ('door' | 'window' | 'room' | 'wall'). */
  categoryKind?: string | null;
  /** §4.11 — leader line tip pointing at the tagged element in plan view. */
  leaderEndMm?: XY | null;
  /** §13.1.2 — which fields are shown in the room tag label. */
  showRoomName?: boolean | null;
  showRoomNumber?: boolean | null;
  showRoomArea?: boolean | null;
  /** §4.11 — display fields derived from the tagged element. */
  fields?: {
    mark?: string | null;
    typeName?: string | null;
    widthMm?: number | null;
    heightMm?: number | null;
    roomName?: string | null;
    roomNumber?: string | null;
    roomArea?: number | null;
  } | null;
};

/** ANN-01 — view-local 2D polyline (annotation only; not visible in 3D). */
export type DetailLineElement = {
  kind: 'detail_line';
  id: string;
  hostViewId: string;
  pointsMm: XY[];
  strokeMm?: number;
  colour?: string;
  style?: 'solid' | 'dashed' | 'dotted';
  /** §6.4.2 drafting fields */
  lineWeightPx?: number;
  colorHex?: string;
  lineStyle?: 'solid' | 'dashed' | 'dotted' | 'center';
  viewId?: string | null;
  levelId?: string | null;
};

/** §6.4.2 — view-local 2D arc (drafting element, not visible in 3D). */
export type DetailArcElement = {
  kind: 'detail_arc';
  id: string;
  centerMm: { xMm: number; yMm: number };
  radiusMm: number;
  startAngleDeg: number;
  endAngleDeg: number;
  lineWeightPx?: number;
  colorHex?: string;
  viewId?: string | null;
  levelId?: string | null;
};

/** §6.4.2 — view-local 2D filled region (drafting element, not visible in 3D). */
export type DetailFilledRegionElement = {
  kind: 'detail_filled_region';
  id: string;
  /** Closed polygon boundary. */
  perimeterMm: { xMm: number; yMm: number }[];
  /** Alias for perimeterMm — §6.4.2 drafting fields. */
  boundaryMm?: { xMm: number; yMm: number }[];
  /** Fill pattern: solid | hatch-45 | hatch-90 | cross | diagonal. */
  fillPattern?: 'solid' | 'hatch-45' | 'hatch-90' | 'cross' | 'diagonal';
  fillPatternId?: string | null;
  /** Fill color hex. */
  colorHex?: string;
  viewId?: string | null;
  levelId?: string | null;
};

/** ANN-01 / ANN-V3-01 — view-local 2D filled region (annotation only). */
export type DetailRegionElement = {
  kind: 'detail_region';
  id: string;
  // v2 fields (ANN-01)
  hostViewId?: string;
  boundaryMm?: XY[];
  fillColour?: string;
  fillPattern?: 'solid' | 'hatch_45' | 'hatch_90' | 'crosshatch' | 'dots';
  strokeMm?: number;
  strokeColour?: string;
  // v3 fields (ANN-V3-01)
  viewId?: string | null;
  vertices?: Array<{ x: number; y: number }> | null;
  closed?: boolean | null;
  hatchId?: string | null;
  lineweightOverride?: number | null;
  phaseCreated?: string | null;
  phaseDemolished?: string | null;
};

/** ANN-01 — view-local text note (annotation only). */
export type TextNoteElement = {
  kind: 'text_note';
  id: string;
  hostViewId: string;
  positionMm: XY;
  text: string;
  fontSizeMm: number;
  anchor?: 'tl' | 'tc' | 'tr' | 'cl' | 'c' | 'cr' | 'bl' | 'bc' | 'br';
  rotationDeg?: number;
  colour?: string;
  bold?: boolean | null;
  italic?: boolean | null;
  underline?: boolean | null;
  fontFamily?: string | null;
  colorHex?: string | null;
  horizontalAlign?: 'left' | 'center' | 'right' | null;
};

/** ANN-05 — view-local graphical symbol (North Arrow, Stair Path, Centerline). */
export type AnnotationSymbolElement = {
  kind: 'annotation_symbol';
  id: string;
  hostViewId: string;
  positionMm: XY;
  symbolType: 'north_arrow' | 'stair_up' | 'stair_down' | 'centerline';
  rotationDeg?: number;
  scale?: number;
  colour?: string;
};

/** ANN-16 — view-local leader annotation: arrow line + optional elbow + text block. */
export type LeaderTextElement = {
  kind: 'leader_text';
  id: string;
  hostViewId: string;
  anchorMm: XY;
  elbowMm?: XY;
  textMm: XY;
  content: string;
  arrowStyle?: 'arrow' | 'dot' | 'none';
  colour?: string;
  bold?: boolean | null;
  italic?: boolean | null;
  underline?: boolean | null;
  fontFamily?: string | null;
  colorHex?: string | null;
  horizontalAlign?: 'left' | 'center' | 'right' | null;
};

export type ColorFillLegendElement = {
  kind: 'color_fill_legend';
  id: string;
  hostViewId: string;
  positionMm: XY;
  schemeParameter: string;
  title: string;
};

export type Text3dElement = {
  kind: 'text_3d';
  id: string;
  text: string;
  fontFamily: Text3dFontFamily;
  fontSizeMm: number;
  depthMm: number;
  positionMm: XYZ;
  rotationDeg: number;
  materialKey?: string | null;
};

export type TextTagElement = {
  kind: 'text_tag';
  id: string;
  positionMm: XY;
  label: string;
  levelId: string;
  hostViewId?: string | null;
  discipline?: DisciplineTag | null;
  agentTrace?: AgentTrace;
  optionSetId?: string | null;
  optionId?: string | null;
};
