import type { ComponentType, SVGAttributes } from 'react';
import {
  AgentIcon,
  AlignIcon,
  AlertTriangleIcon,
  // Phase 1 — drawing tools
  WallIcon,
  DoorIcon,
  WindowIcon,
  FloorIcon,
  RoofIcon,
  StairIcon,
  RailingIcon,
  RoomIcon,
  DimensionIcon,
  SectionIcon,
  TagIcon,
  CurtainWallIcon,
  ColumnIcon,
  BeamIcon,
  CeilingIcon,
  CableTrayIcon,
  CameraIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ClockIcon,
  CloseIcon,
  CollaboratorsIcon,
  CommandPaletteIcon,
  CopyIcon,
  DuctRectIcon,
  DuctRoundIcon,
  // Phase 2 — views & annotations
  PlanViewIcon,
  SectionViewIcon,
  ElevationViewIcon,
  OrbitViewIcon,
  SheetIcon,
  ScheduleViewIcon,
  CalloutIcon,
  ViewpointIcon,
  SectionBoxIcon,
  GridLineIcon,
  LevelIcon,
  DetailLineIcon,
  DownloadIcon,
  EvidenceIcon,
  ExternalLinkIcon,
  // Phase 3 — organization & coordination
  FamilyIcon,
  FamilyTypeIcon,
  GroupIcon,
  AssemblyIcon,
  LinkedModelIcon,
  MaterialIcon,
  WallLayerIcon,
  PhaseIcon,
  TopoIcon,
  PropertyLineIcon,
  NorthArrowIcon,
  IssueIcon,
  ClashIcon,
  ValidationRuleIcon,
  DeviationIcon,
  RFIIcon,
  RevisionCloudIcon,
  TextAnnotationIcon,
  AngularDimensionIcon,
  RadialDimensionIcon,
  ArcLengthDimensionIcon,
  SpotElevationIcon,
  SpotCoordinateIcon,
  SlopeArrowIcon,
  FilledRegionIcon,
  MaskingRegionIcon,
  MaterialTagIcon,
  PanelScheduleViewIcon,
  GraphicalColumnScheduleIcon,
  FocusIcon,
  GridIcon,
  HomeIcon,
  LinkIcon,
  MeasureBetweenIcon,
  MenuIcon,
  MirrorIcon,
  MoonIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MoveIcon,
  OnlineIcon,
  ScaleIcon,
  OpeningIcon,
  AreaLabelIcon,
  AreaPlanIcon,
  AreaBoundaryIcon,
  ReferencePlaneIcon,
  RoomSeparatorIcon,
  RampIcon,
  MassIcon,
  ModelLineIcon,
  ModelTextIcon,
  WallSweepIcon,
  DormerOpeningIcon,
  PipeIcon,
  MechanicalEquipmentIcon,
  PlumbingFixtureIcon,
  LightingFixtureIcon,
  DiffuserIcon,
  HVACZoneIcon,
  QuantityTakeoffIcon,
  EnergyModelIcon,
  BraceIcon,
  BeamSystemIcon,
  StructuralConnectionIcon,
  RedoIcon,
  RefreshIcon,
  RotateIcon,
  SearchIcon,
  SelectIcon,
  SettingsIcon,
  ShaftOpeningIcon,
  SnapIcon,
  SplitIcon,
  SunIcon,
  ThinLineIcon,
  TrimExtendIcon,
  UndoIcon,
  ArrayLinearIcon,
  OffsetIcon,
  UnjoinGeometryIcon,
  PaintMaterialIcon,
  WalkthroughIcon,
  VisibilityOffIcon,
  VisibilityOnIcon,
  WallJoinsIcon,
} from '@bim-ai/icons';

/**
 * BIM AI chrome icon set — the single import surface for icon usage outside
 * the canvas. BIM-specific and generic chrome icons both come from
 * `@bim-ai/icons`.
 *
 * Default visual rules (spec §10):
 *   - Default size 16 px in dense chrome; 18 px in tool palette; 20 px in
 *     TopBar. Pass `size` prop to override.
 *   - Default stroke width 1.5; selected state 2.0.
 *   - Color inherits `currentColor` so theme tokens drive it.
 *
 * Every icon-only button must pair its icon with `aria-label` (spec §22).
 */

export type BimIconComponent = ComponentType<
  SVGAttributes<SVGSVGElement> & {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }
>;

const AreaIcon = AreaLabelIcon;
const SiteIcon = TopoIcon;
const SiteOriginIcon = GridLineIcon;
const ToposolidSubdivisionIcon = TopoIcon;
const TerrainPointIcon = TopoIcon;
const TerrainPadIcon = TopoIcon;
const TerrainSplitIcon = TopoIcon;
const GradedRegionIcon = TopoIcon;
const ProjectBasePointIcon = GridLineIcon;
const LeaderTextIcon = TextAnnotationIcon;
const DiameterDimensionIcon = RadialDimensionIcon;
const PlanRegionIcon = AreaPlanIcon;
const MassBoxIcon = MassIcon;
const MassExtrusionIcon = MassIcon;
const MassRevolutionIcon = MassIcon;
const FamilyBlendIcon = FamilyIcon;
const FamilySweepIcon = WallSweepIcon;
const FamilySweptBlendIcon = WallSweepIcon;
const UValueIcon = EnergyModelIcon;
const ThermalBridgeIcon = EnergyModelIcon;
const FireCompartmentIcon = AlertTriangleIcon;
const EscapeRouteIcon = AlertTriangleIcon;
const FireRatingIcon = AlertTriangleIcon;
const TravelDistanceIcon = DimensionIcon;
const PenetrationIcon = OpeningIcon;
const PenetrationRequestIcon = OpeningIcon;
const EPDIcon = MaterialIcon;
const CarbonImpactIcon = EnergyModelIcon;
const LCAExportIcon = EnergyModelIcon;
const DIN276Icon = QuantityTakeoffIcon;
const BOQIcon = QuantityTakeoffIcon;
const UnitRateIcon = QuantityTakeoffIcon;
const PackageIcon = AssemblyIcon;
const LogisticsIcon = LinkedModelIcon;
const ProgressIcon = ClockIcon;
const QAChecklistIcon = CheckIcon;
const SelectionSetIcon = GroupIcon;
const ReviewStatusIcon = IssueIcon;
const PrecastColumnIcon = ColumnIcon;
const PrecastBeamIcon = BeamIcon;
const PrecastSlabIcon = FloorIcon;
const AttachIcon = LinkIcon;
const DetachIcon = LinkIcon;
const LineworkIcon = DetailLineIcon;
const CutGeometryIcon = SplitIcon;
const CreatePartsIcon = AssemblyIcon;

/** @deprecated use StairIcon from @bim-ai/icons. Kept for test backwards compat. */
export { StairIcon as StairsIcon } from '@bim-ai/icons';

/** Spec §10.1 "concept → icon" registry. Single source of truth for chrome
 * icons. Tools / shell / dialogs read from here so the assignments can be
 * audited as a unit. */
export const Icons: Record<string, BimIconComponent> = {
  // Selection & manipulation
  select: SelectIcon,

  // Modify tools
  align: AlignIcon,
  copy: CopyIcon,
  measure: MeasureBetweenIcon,
  split: SplitIcon,
  trim: TrimExtendIcon,
  offset: OffsetIcon,
  'wall-join': WallJoinsIcon,
  unjoin: UnjoinGeometryIcon,
  attach: AttachIcon,
  detach: DetachIcon,
  array: ArrayLinearIcon,
  'wall-opening': OpeningIcon,
  openingRequest: PenetrationRequestIcon,
  penetrationRequest: PenetrationRequestIcon,
  shaft: ShaftOpeningIcon,
  mirror: MirrorIcon,
  move: MoveIcon,
  rotate: RotateIcon,
  scale: ScaleIcon,
  paint: PaintMaterialIcon,
  linework: LineworkIcon,
  cutGeometry: CutGeometryIcon,
  createParts: CreatePartsIcon,

  // Drawing tools — all now BIM-native from @bim-ai/icons
  wall: WallIcon,
  door: DoorIcon,
  window: WindowIcon,
  floor: FloorIcon,
  roof: RoofIcon,
  stair: StairIcon,
  railing: RailingIcon,
  room: RoomIcon,
  area: AreaIcon,
  areaBoundary: AreaBoundaryIcon,
  roomSeparator: RoomSeparatorIcon,
  dimension: DimensionIcon,
  angularDimension: AngularDimensionIcon,
  radialDimension: RadialDimensionIcon,
  diameterDimension: DiameterDimensionIcon,
  arcLengthDimension: ArcLengthDimensionIcon,
  section: SectionIcon,
  tag: TagIcon,
  materialTag: MaterialTagIcon,
  curtainWall: CurtainWallIcon,
  column: ColumnIcon,
  beam: BeamIcon,
  brace: BraceIcon,
  beamSystem: BeamSystemIcon,
  steelConnection: StructuralConnectionIcon,
  precastColumn: PrecastColumnIcon,
  precastBeam: PrecastBeamIcon,
  precastSlab: PrecastSlabIcon,
  ceiling: CeilingIcon,
  duct: DuctRectIcon,
  ductRound: DuctRoundIcon,
  pipe: PipeIcon,
  cableTray: CableTrayIcon,
  mepEquipment: MechanicalEquipmentIcon,
  fixture: PlumbingFixtureIcon,
  mepTerminal: LightingFixtureIcon,
  diffuser: DiffuserIcon,
  thermalZone: HVACZoneIcon,
  uValue: UValueIcon,
  thermalBridge: ThermalBridgeIcon,
  fireCompartment: FireCompartmentIcon,
  escapeRoute: EscapeRouteIcon,
  fireRating: FireRatingIcon,
  travelDistance: TravelDistanceIcon,
  penetration: PenetrationIcon,
  ramp: RampIcon,
  mass: MassIcon,
  massBox: MassBoxIcon,
  massExtrusion: MassExtrusionIcon,
  massRevolution: MassRevolutionIcon,
  familyBlend: FamilyBlendIcon,
  familySweep: FamilySweepIcon,
  familySweptBlend: FamilySweptBlendIcon,

  // Views & documentation — BIM-native
  planView: PlanViewIcon,
  sectionView: SectionViewIcon,
  elevationView: ElevationViewIcon,
  orbitView: OrbitViewIcon,
  sheet: SheetIcon,
  schedule: ScheduleViewIcon,
  callout: CalloutIcon,
  viewpoint: ViewpointIcon,
  sectionBox: SectionBoxIcon,
  gridLine: GridLineIcon,
  referencePlane: ReferencePlaneIcon,
  level: LevelIcon,
  detailLine: DetailLineIcon,
  modelLine: ModelLineIcon,
  modelText: ModelTextIcon,
  filledRegion: FilledRegionIcon,
  maskingRegion: MaskingRegionIcon,
  planRegion: PlanRegionIcon,
  spotElevation: SpotElevationIcon,
  spotCoordinate: SpotCoordinateIcon,
  slopeAnnotation: SlopeArrowIcon,
  leaderText: LeaderTextIcon,
  northArrow: NorthArrowIcon,
  walkthrough: WalkthroughIcon,
  revisionCloud: RevisionCloudIcon,

  // Organization & data — BIM-native
  family: FamilyIcon,
  familyType: FamilyTypeIcon,
  group: GroupIcon,
  assembly: AssemblyIcon,
  linkedModel: LinkedModelIcon,
  material: MaterialIcon,
  wallLayer: WallLayerIcon,
  phase: PhaseIcon,
  topography: TopoIcon,
  site: SiteIcon,
  siteOrigin: SiteOriginIcon,
  propertyLine: PropertyLineIcon,
  topoSubdivision: ToposolidSubdivisionIcon,
  terrainPoint: TerrainPointIcon,
  terrainPad: TerrainPadIcon,
  terrainSplit: TerrainSplitIcon,
  gradedRegion: GradedRegionIcon,
  projectBasePoint: ProjectBasePointIcon,
  wallSweep: WallSweepIcon,
  dormerOpening: DormerOpeningIcon,
  quantityTakeoff: QuantityTakeoffIcon,
  energyModel: EnergyModelIcon,
  epd: EPDIcon,
  carbonImpact: CarbonImpactIcon,
  lcaExport: LCAExportIcon,
  din276: DIN276Icon,
  boq: BOQIcon,
  unitRate: UnitRateIcon,
  package: PackageIcon,
  logistics: LogisticsIcon,
  progress: ProgressIcon,
  qaChecklist: QAChecklistIcon,
  selectionSet: SelectionSetIcon,
  reviewStatus: ReviewStatusIcon,

  // Coordination — BIM-native
  issue: IssueIcon,
  bcf: IssueIcon,
  clash: ClashIcon,
  validationRule: ValidationRuleIcon,
  deviation: DeviationIcon,
  comment: RFIIcon,
  check: CheckIcon,

  // Camera / view
  saveViewpoint: CameraIcon,
  layerOn: VisibilityOnIcon,
  layerOff: VisibilityOffIcon,
  viewCubeReset: HomeIcon,

  // History
  undo: UndoIcon,
  redo: RedoIcon,

  // F-006: QAT buttons
  thinLines: ThinLineIcon,

  // Theme
  themeLight: SunIcon,
  themeDark: MoonIcon,

  // Navigation / global chrome
  commandPalette: CommandPaletteIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  hamburger: MenuIcon,
  collaborators: CollaboratorsIcon,
  close: CloseIcon,
  externalLink: ExternalLinkIcon,
  proportional: LinkIcon,

  // Disclosure
  disclosureClosed: ChevronRightIcon,
  disclosureOpen: ChevronDownIcon,

  // Status / signals
  agent: AgentIcon,
  evidence: EvidenceIcon,
  advisorWarning: AlertTriangleIcon,
  online: OnlineIcon,
  snap: SnapIcon,
  grid: GridIcon,
  activity: ClockIcon,
  download: DownloadIcon,
  focus: FocusIcon,
  refresh: RefreshIcon,
  moreHorizontal: MoreHorizontalIcon,
  moreVertical: MoreVerticalIcon,

  // Sheet markup and schedule editing — BIM-native
  annotation: DetailLineIcon,
  pen: DetailLineIcon,
  arrowRight: DetailLineIcon,
  draftingCloud: RevisionCloudIcon,
  text: TextAnnotationIcon,
  tableRows: PanelScheduleViewIcon,
  tableColumns: GraphicalColumnScheduleIcon,
};

/** Human-readable default labels for `aria-label` on icon-only buttons. */
export const IconLabels: Record<keyof typeof Icons, string> = {
  select: 'Select',
  align: 'Align',
  copy: 'Copy',
  measure: 'Measure',
  split: 'Split element',
  trim: 'Trim / Extend',
  offset: 'Offset',
  'wall-join': 'Wall Join',
  unjoin: 'Unjoin geometry',
  attach: 'Attach',
  detach: 'Detach',
  'wall-opening': 'Wall Opening',
  openingRequest: 'Opening request',
  penetrationRequest: 'Penetration request',
  shaft: 'Shaft',
  mirror: 'Mirror',
  move: 'Move',
  rotate: 'Rotate',
  scale: 'Scale',
  paint: 'Paint material',
  linework: 'Linework override',
  cutGeometry: 'Cut geometry',
  createParts: 'Create parts',
  array: 'Array',
  wall: 'Wall',
  door: 'Door',
  window: 'Window',
  floor: 'Floor',
  roof: 'Roof',
  stair: 'Stair',
  railing: 'Railing',
  room: 'Room',
  area: 'Area',
  areaBoundary: 'Area boundary',
  roomSeparator: 'Room separator',
  dimension: 'Dimension',
  angularDimension: 'Angular dimension',
  radialDimension: 'Radial dimension',
  diameterDimension: 'Diameter dimension',
  arcLengthDimension: 'Arc length dimension',
  section: 'Section',
  tag: 'Tag',
  materialTag: 'Material tag',
  curtainWall: 'Curtain wall',
  column: 'Column',
  beam: 'Beam',
  brace: 'Brace',
  beamSystem: 'Beam system',
  steelConnection: 'Steel connection',
  precastColumn: 'Precast column',
  precastBeam: 'Precast beam',
  precastSlab: 'Precast slab',
  ceiling: 'Ceiling',
  duct: 'Duct',
  ductRound: 'Round duct',
  pipe: 'Pipe',
  cableTray: 'Cable tray',
  mepEquipment: 'MEP equipment',
  fixture: 'Fixture',
  mepTerminal: 'MEP terminal',
  diffuser: 'Diffuser',
  thermalZone: 'Thermal zone',
  uValue: 'U-value',
  thermalBridge: 'Thermal bridge',
  fireCompartment: 'Fire compartment',
  escapeRoute: 'Escape route',
  fireRating: 'Fire rating',
  travelDistance: 'Travel distance',
  penetration: 'Penetration',
  ramp: 'Ramp',
  mass: 'Mass',
  massBox: 'Mass box',
  massExtrusion: 'Mass extrusion',
  massRevolution: 'Mass revolution',
  familyBlend: 'Family blend',
  familySweep: 'Family sweep',
  familySweptBlend: 'Family swept blend',
  planView: 'Plan view',
  sectionView: 'Section view',
  elevationView: 'Elevation view',
  orbitView: '3D view',
  sheet: 'Sheet',
  schedule: 'Schedule',
  callout: 'Callout',
  viewpoint: 'Viewpoint',
  sectionBox: 'Section box',
  gridLine: 'Grid line',
  referencePlane: 'Reference plane',
  level: 'Level',
  detailLine: 'Detail line',
  modelLine: 'Model line',
  modelText: 'Model text',
  filledRegion: 'Filled region',
  maskingRegion: 'Masking region',
  planRegion: 'Plan region',
  spotElevation: 'Spot elevation',
  spotCoordinate: 'Spot coordinate',
  slopeAnnotation: 'Slope annotation',
  leaderText: 'Leader text',
  northArrow: 'North arrow',
  walkthrough: 'Walkthrough',
  revisionCloud: 'Revision cloud',
  family: 'Family',
  familyType: 'Family type',
  group: 'Group',
  assembly: 'Assembly',
  linkedModel: 'Linked model',
  material: 'Material',
  wallLayer: 'Wall layer',
  phase: 'Phase',
  topography: 'Topography',
  site: 'Site',
  siteOrigin: 'Site origin',
  propertyLine: 'Property line',
  topoSubdivision: 'Toposolid subdivision',
  terrainPoint: 'Terrain point',
  terrainPad: 'Terrain pad',
  terrainSplit: 'Terrain split',
  gradedRegion: 'Graded region',
  projectBasePoint: 'Project base point',
  wallSweep: 'Wall sweep',
  dormerOpening: 'Dormer opening',
  quantityTakeoff: 'Quantity takeoff',
  energyModel: 'Energy model',
  epd: 'EPD',
  carbonImpact: 'Carbon impact',
  lcaExport: 'LCA export',
  din276: 'DIN 276',
  boq: 'BOQ',
  unitRate: 'Unit rate',
  package: 'Package',
  logistics: 'Logistics',
  progress: 'Progress',
  qaChecklist: 'QA checklist',
  selectionSet: 'Selection set',
  reviewStatus: 'Review status',
  issue: 'Issue',
  bcf: 'BCF issue',
  clash: 'Clash',
  validationRule: 'Validation rule',
  deviation: 'Deviation',
  comment: 'Comment',
  check: 'Resolve',
  saveViewpoint: 'Save viewpoint',
  layerOn: 'Show layer',
  layerOff: 'Hide layer',
  viewCubeReset: 'Reset view',
  undo: 'Undo',
  redo: 'Redo',
  thinLines: 'Thin Lines',
  themeLight: 'Light theme',
  themeDark: 'Dark theme',
  commandPalette: 'Command palette',
  search: 'Search',
  settings: 'Settings',
  hamburger: 'Toggle navigation',
  collaborators: 'Collaborators',
  close: 'Close',
  externalLink: 'Open in new context',
  proportional: 'Link proportional',
  disclosureClosed: 'Expand',
  disclosureOpen: 'Collapse',
  agent: 'Agent',
  evidence: 'Evidence',
  advisorWarning: 'Advisor warning',
  online: 'Online',
  snap: 'Snap',
  grid: 'Grid',
  activity: 'Activity',
  download: 'Download',
  focus: 'Focus selection',
  refresh: 'Refresh',
  moreHorizontal: 'More options',
  moreVertical: 'More options',
  annotation: 'Annotation',
  pen: 'Freehand markup',
  arrowRight: 'Arrow markup',
  draftingCloud: 'Revision cloud',
  text: 'Text annotation',
  tableRows: 'Schedule rows',
  tableColumns: 'Schedule columns',
};

export type IconName = keyof typeof Icons;

/** Default icon sizes per spec §10. */
export const ICON_SIZE = {
  chrome: 16,
  toolPalette: 18,
  topbar: 20,
} as const;

// Re-export all BIM icons so consumers can import them from @bim-ai/ui without
// adding a direct dependency on @bim-ai/icons.
export {
  WallIcon,
  DoorIcon,
  WindowIcon,
  FloorIcon,
  RoofIcon,
  StairIcon,
  RailingIcon,
  RoomIcon,
  DimensionIcon,
  SectionIcon,
  TagIcon,
  CurtainWallIcon,
  ColumnIcon,
  BeamIcon,
  CeilingIcon,
  PlanViewIcon,
  SectionViewIcon,
  ElevationViewIcon,
  OrbitViewIcon,
  SheetIcon,
  ScheduleViewIcon,
  CalloutIcon,
  ViewpointIcon,
  SectionBoxIcon,
  GridLineIcon,
  LevelIcon,
  DetailLineIcon,
  FamilyIcon,
  FamilyTypeIcon,
  GroupIcon,
  AssemblyIcon,
  LinkedModelIcon,
  MaterialIcon,
  WallLayerIcon,
  PhaseIcon,
  IssueIcon,
  ClashIcon,
  ValidationRuleIcon,
  DeviationIcon,
  RFIIcon,
  RevisionCloudIcon,
  TextAnnotationIcon,
  PanelScheduleViewIcon,
  GraphicalColumnScheduleIcon,
} from '@bim-ai/icons';
