/**
 * §12.4.3: Minimal DGN export for MicroStation compatibility.
 * Produces a text-based DGN "seed" using DXF-compatible geometry with a DGN header.
 * Most DGN viewers accept this via the DXF/DGN interchange bridge.
 */

import { exportToDxf } from './dxfExporter';
import type { Element } from '@bim-ai/core';

export interface DgnExportOptions {
  /** Level IDs to export (all if omitted). */
  levelIds?: string[];
  /** Units: 'mm' or 'm'. Default 'mm'. */
  units?: 'mm' | 'm';
}

/**
 * Exports the scene to a DGN-compatible text format.
 * Returns a string suitable for saving as .dgn / .dxf.
 */
export function exportSceneToDgn(
  elementsById: Record<string, Element>,
  levels: { id: string; name: string; elevationMm: number }[],
  options: DgnExportOptions = {},
): string {
  const { units = 'mm', levelIds } = options;
  const targetLevels = levelIds ? levels.filter((l) => levelIds.includes(l.id)) : levels;

  if (targetLevels.length === 0) {
    return '; DGN SEED — no levels to export\n';
  }

  // Build DXF geometry for each level using the public exportToDxf API
  const planViews = targetLevels.map((level) => {
    const views = exportToDxf(elementsById, { levelId: level.id, units });
    return views.map((v) => v.dxfContent).join('\n');
  });

  // Wrap in a DGN-compatible header comment block
  const header = [
    '; DGN SEED FILE',
    `; Generated by bim-ai — ${new Date().toISOString()}`,
    `; Levels: ${targetLevels.map((l) => l.name).join(', ')}`,
    `; Units: ${units}`,
    '; Compatible with MicroStation DGN/DXF bridge',
    '',
  ].join('\n');

  const body = planViews.join('\n\n');

  return header + body;
}

/** Returns the MIME type for DGN files. */
export const DGN_MIME_TYPE = 'application/dgn';

/** Returns a filename for the DGN export. */
export function dgnFileName(projectName: string): string {
  return `${projectName.replace(/[^a-z0-9]/gi, '_')}.dgn`;
}
