"""Annotation, dimension, and tag command schemas extracted from commands.py."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from bim_ai.elements import Vec2Mm


class CreateDimensionCmd(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createDimension"] = "createDimension"
    id: str | None = None
    name: str = "Dimension"
    level_id: str = Field(alias="levelId")
    a_mm: Vec2Mm = Field(alias="aMm")
    b_mm: Vec2Mm = Field(alias="bMm")
    offset_mm: Vec2Mm = Field(alias="offsetMm")
    anchor_a: dict[str, Any] | None = Field(default=None, alias="anchorA")
    anchor_b: dict[str, Any] | None = Field(default=None, alias="anchorB")
    state: Literal["linked", "partial", "unlinked"] | None = None
    ref_element_id_a: str | None = Field(default=None, alias="refElementIdA")
    ref_element_id_b: str | None = Field(default=None, alias="refElementIdB")
    tag_definition_id: str | None = Field(default=None, alias="tagDefinitionId")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


class CreateAngularDimensionCmd(BaseModel):
    """ANN-04 — angular dimension between two rays from a shared vertex."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createAngularDimension"] = "createAngularDimension"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    vertex_mm: Vec2Mm = Field(alias="vertexMm")
    ray_a_mm: Vec2Mm = Field(alias="rayAMm")
    ray_b_mm: Vec2Mm = Field(alias="rayBMm")
    arc_radius_mm: float = Field(default=500.0, alias="arcRadiusMm")
    colour: str = Field(default="#202020")


class PlaceTagCmd(BaseModel):
    """PLN-01 / ANN-01 — view-local placed tag (room/door/window)."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["placeTag"] = "placeTag"
    id: str | None = None
    host_element_id: str = Field(alias="hostElementId")
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    tag_definition_id: str | None = Field(default=None, alias="tagDefinitionId")
    text_override: str | None = Field(default=None, alias="textOverride")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


class ClearAutoGeneratedAnnotationsCmd(BaseModel):
    """PLN-01 — remove all auto-generated dimensions and placed_tags hosted
    on the supplied plan_view (or globally when host_view_id is None)."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["clearAutoGeneratedAnnotations"] = "clearAutoGeneratedAnnotations"
    host_view_id: str | None = Field(default=None, alias="hostViewId")
    scope: Literal["dimensions", "tags", "both"] = "both"


class CreateDetailLineCmd(BaseModel):
    """ANN-01 — view-local 2D polyline."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createDetailLine"] = "createDetailLine"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    points_mm: list[Vec2Mm] = Field(alias="pointsMm")
    stroke_mm: float = Field(default=1.0, alias="strokeMm")
    colour: str = Field(default="#202020")
    style: Literal["solid", "dashed", "dotted"] = Field(default="solid")


class CreateDetailRegionCmd(BaseModel):
    """ANN-01 — view-local 2D filled region."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createDetailRegion"] = "createDetailRegion"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    boundary_mm: list[Vec2Mm] = Field(alias="boundaryMm")
    fill_colour: str = Field(default="#cccccc", alias="fillColour")
    fill_pattern: Literal["solid", "hatch_45", "hatch_90", "crosshatch", "dots"] = Field(
        default="solid", alias="fillPattern"
    )
    stroke_mm: float = Field(default=0.5, alias="strokeMm")
    stroke_colour: str = Field(default="#202020", alias="strokeColour")


class CreateTextNoteCmd(BaseModel):
    """ANN-01 — view-local text note."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createTextNote"] = "createTextNote"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    text: str
    font_size_mm: float = Field(alias="fontSizeMm")
    anchor: Literal["tl", "tc", "tr", "cl", "c", "cr", "bl", "bc", "br"] = Field(default="tl")
    rotation_deg: float = Field(default=0.0, alias="rotationDeg")
    colour: str = Field(default="#202020")


class CreateAnnotationSymbolCmd(BaseModel):
    """ANN-05 — place a view-local annotation symbol (North Arrow, Stair Path, Centerline)."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createAnnotationSymbol"] = "createAnnotationSymbol"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    symbol_type: Literal["north_arrow", "stair_up", "stair_down", "centerline"] = Field(
        alias="symbolType"
    )
    rotation_deg: float = Field(default=0.0, alias="rotationDeg")
    scale: float = Field(default=1.0)
    colour: str = Field(default="#202020")


class CreateSpotElevationCmd(BaseModel):
    """ANN-02 — view-local spot elevation at a picked point."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createSpotElevation"] = "createSpotElevation"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    elevation_mm: float = Field(alias="elevationMm")
    prefix: str = Field(default="")
    suffix: str = Field(default="")
    colour: str = Field(default="#202020")


class CreateSpotCoordinateCmd(BaseModel):
    """ANN-09 — view-local spot coordinate."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createSpotCoordinate"] = "createSpotCoordinate"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    north_mm: float = Field(alias="northMm")
    east_mm: float = Field(alias="eastMm")
    colour: str = Field(default="#202020")


class CreateSpotSlopeCmd(BaseModel):
    """ANN-10 — view-local spot slope."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createSpotSlope"] = "createSpotSlope"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    slope_pct: float = Field(alias="slopePct")
    slope_format: Literal["percent", "ratio", "degree"] = Field(
        default="percent", alias="slopeFormat"
    )
    colour: str = Field(default="#202020")


class CreateInsulationAnnotationCmd(BaseModel):
    """ANN-11 — view-local insulation annotation."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createInsulationAnnotation"] = "createInsulationAnnotation"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    start_mm: Vec2Mm = Field(alias="startMm")
    end_mm: Vec2Mm = Field(alias="endMm")
    width_mm: float = Field(default=200.0, alias="widthMm")
    colour: str = Field(default="#202020")


class CreateRadialDimensionCmd(BaseModel):
    """ANN-06 — radial dimension."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createRadialDimension"] = "createRadialDimension"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    center_mm: Vec2Mm = Field(alias="centerMm")
    arc_point_mm: Vec2Mm = Field(alias="arcPointMm")
    colour: str = Field(default="#202020")


class CreateDiameterDimensionCmd(BaseModel):
    """ANN-07 — diameter dimension."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createDiameterDimension"] = "createDiameterDimension"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    center_mm: Vec2Mm = Field(alias="centerMm")
    arc_point_mm: Vec2Mm = Field(alias="arcPointMm")
    colour: str = Field(default="#202020")


class CreateArcLengthDimensionCmd(BaseModel):
    """ANN-08 — arc length dimension."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createArcLengthDimension"] = "createArcLengthDimension"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    center_mm: Vec2Mm = Field(alias="centerMm")
    radius_mm: float = Field(alias="radiusMm")
    start_angle_deg: float = Field(alias="startAngleDeg")
    end_angle_deg: float = Field(alias="endAngleDeg")
    colour: str = Field(default="#202020")


class CreateMaterialTagCmd(BaseModel):
    """ANN-12 — place a material layer tag."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createMaterialTag"] = "createMaterialTag"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    host_element_id: str = Field(alias="hostElementId")
    layer_index: int = Field(default=0, alias="layerIndex")
    position_mm: Vec2Mm = Field(alias="positionMm")
    text_override: str | None = Field(default=None, alias="textOverride")
    leader_end_mm: Vec2Mm | None = Field(default=None, alias="leaderEndMm")
    colour: str = Field(default="#202020")


class CreateMultiCategoryTagCmd(BaseModel):
    """ANN-13 — place a multi-category tag."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createMultiCategoryTag"] = "createMultiCategoryTag"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    host_element_id: str = Field(alias="hostElementId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    parameter_name: str = Field(default="Type Mark", alias="parameterName")
    text_override: str | None = Field(default=None, alias="textOverride")
    colour: str = Field(default="#202020")


class CreateTreadNumberCmd(BaseModel):
    """ANN-14 — place tread number annotations on a stair."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createTreadNumber"] = "createTreadNumber"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    stair_element_id: str = Field(alias="stairElementId")
    start_number: int = Field(default=1, alias="startNumber")
    colour: str = Field(default="#202020")


class CreateKeynoteCmd(BaseModel):
    """ANN-15 — place a keynote annotation."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createKeynote"] = "createKeynote"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    keynote_key: str = Field(alias="keynoteKey")
    keynote_text: str = Field(default="", alias="keynoteText")
    target: Literal["element", "material", "user"] = Field(default="user")
    host_element_id: str | None = Field(default=None, alias="hostElementId")
    colour: str = Field(default="#202020")


class CreateSpanDirectionCmd(BaseModel):
    """ANN-16 — place a span direction arrow."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createSpanDirection"] = "createSpanDirection"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    direction_deg: float = Field(default=0.0, alias="directionDeg")
    length_mm: float = Field(default=800.0, alias="lengthMm")
    colour: str = Field(default="#202020")


class CreateDetailComponentCmd(BaseModel):
    """ANN-17 — place a 2D detail component."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createDetailComponent"] = "createDetailComponent"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    component_shape: Literal[
        "us_wide_flange_beam",
        "concrete_column_square",
        "concrete_column_round",
        "steel_angle",
        "steel_channel",
        "bolt",
        "weld_symbol",
        "break_line",
        "centerline_end",
    ] = Field(alias="componentShape")
    rotation_deg: float = Field(default=0.0, alias="rotationDeg")
    scale: float = Field(default=1.0)
    colour: str = Field(default="#202020")


class CreateRepeatingDetailCmd(BaseModel):
    """ANN-18 — create a repeating detail component pattern."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createRepeatingDetail"] = "createRepeatingDetail"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    start_mm: Vec2Mm = Field(alias="startMm")
    end_mm: Vec2Mm = Field(alias="endMm")
    component_shape: Literal[
        "us_wide_flange_beam",
        "concrete_column_square",
        "concrete_column_round",
        "steel_angle",
        "steel_channel",
        "bolt",
        "weld_symbol",
        "break_line",
        "centerline_end",
    ] = Field(alias="componentShape")
    spacing_mm: float = Field(default=200.0, alias="spacingMm")
    colour: str = Field(default="#202020")


class CreateDetailGroupCmd(BaseModel):
    """ANN-19 — create a named group of detail elements."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createDetailGroup"] = "createDetailGroup"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    name: str = Field(default="Group")
    member_ids: list[str] = Field(alias="memberIds")


class CreateColorFillLegendCmd(BaseModel):
    """ANN-20 — place a color fill legend in a view."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")
    type: Literal["createColorFillLegend"] = "createColorFillLegend"
    id: str | None = None
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    scheme_parameter: str = Field(default="Name", alias="schemeParameter")
    title: str = Field(default="Color Fill Legend")


