"""Annotation, dimension, tag, and detail element models extracted from elements.py.

Kept as a sibling module that is re-imported by ``bim_ai.elements`` so the
existing wildcard public surface stays available.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from bim_ai.element_primitives import Vec2Mm


class DimensionElem(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["dimension"] = "dimension"
    id: str
    name: str = "Dimension"
    level_id: str = Field(alias="levelId")
    a_mm: Vec2Mm = Field(alias="aMm")
    b_mm: Vec2Mm = Field(alias="bMm")
    offset_mm: Vec2Mm = Field(alias="offsetMm")
    text_offset_mm: Vec2Mm | None = Field(default=None, alias="textOffsetMm")
    anchor_a: dict[str, Any] | None = Field(default=None, alias="anchorA")
    anchor_b: dict[str, Any] | None = Field(default=None, alias="anchorB")
    state: Literal["linked", "partial", "unlinked"] = "unlinked"
    ref_element_id_a: str | None = Field(default=None, alias="refElementIdA")
    ref_element_id_b: str | None = Field(default=None, alias="refElementIdB")
    tag_definition_id: str | None = Field(default=None, alias="tagDefinitionId")
    auto_generated: bool = Field(default=False, alias="autoGenerated")
    pinned: bool = Field(default=False)


class AngularDimensionElem(BaseModel):
    """ANN-04 — view-local angular dimension between two rays from a shared vertex."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["angular_dimension"] = "angular_dimension"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    vertex_mm: Vec2Mm = Field(alias="vertexMm")
    ray_a_mm: Vec2Mm = Field(alias="rayAMm")
    ray_b_mm: Vec2Mm = Field(alias="rayBMm")
    arc_radius_mm: float = Field(default=500.0, alias="arcRadiusMm", gt=0)
    colour: str = Field(default="#202020")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


class PlacedTagElem(BaseModel):
    """PLN-01 / ANN-01 — view-local placed tag (room / door / window)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["placed_tag"] = "placed_tag"
    id: str
    host_element_id: str = Field(alias="hostElementId")
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    tag_definition_id: str | None = Field(default=None, alias="tagDefinitionId")
    text_override: str | None = Field(default=None, alias="textOverride")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


DetailLineStyle = Literal["solid", "dashed", "dotted"]


class DetailLineElem(BaseModel):
    """ANN-01 — view-local 2D polyline annotation."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["detail_line"] = "detail_line"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    points_mm: list[Vec2Mm] = Field(alias="pointsMm")
    stroke_mm: float = Field(default=1.0, alias="strokeMm", gt=0)
    colour: str = Field(default="#202020")
    style: DetailLineStyle = Field(default="solid")


DetailRegionFillPattern = Literal["solid", "hatch_45", "hatch_90", "crosshatch", "dots"]


class DetailRegionElem(BaseModel):
    """ANN-01 / ANN-V3-01 — view-local 2D filled region annotation."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["detail_region"] = "detail_region"
    id: str
    # v2 fields (ANN-01) — kept for backward compat
    host_view_id: str = Field(default="", alias="hostViewId")
    boundary_mm: list[Vec2Mm] = Field(default_factory=list, alias="boundaryMm")
    fill_colour: str = Field(default="#cccccc", alias="fillColour")
    fill_pattern: DetailRegionFillPattern = Field(default="solid", alias="fillPattern")
    stroke_mm: float = Field(default=0.5, alias="strokeMm", ge=0)
    stroke_colour: str = Field(default="#202020", alias="strokeColour")
    # v3 fields (ANN-V3-01)
    view_id: str | None = Field(default=None, alias="viewId")
    vertices: list[dict] | None = None
    closed: bool | None = None
    hatch_id: str | None = Field(default=None, alias="hatchId")
    lineweight_override: float | None = Field(default=None, alias="lineweightOverride")
    phase_created: str | None = Field(default=None, alias="phaseCreated")
    phase_demolished: str | None = Field(default=None, alias="phaseDemolished")


TextNoteAnchor = Literal["tl", "tc", "tr", "cl", "c", "cr", "bl", "bc", "br"]


class TextNoteElem(BaseModel):
    """ANN-01 — view-local text note annotation."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["text_note"] = "text_note"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    text: str
    font_size_mm: float = Field(alias="fontSizeMm", gt=0)
    anchor: TextNoteAnchor = Field(default="tl")
    rotation_deg: float = Field(default=0.0, alias="rotationDeg")
    colour: str = Field(default="#202020")


AnnotationSymbolType = Literal["north_arrow", "stair_up", "stair_down", "centerline"]


class AnnotationSymbolElem(BaseModel):
    """ANN-05 — view-local graphical symbol (North Arrow, Stair Path, Centerline)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["annotation_symbol"] = "annotation_symbol"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    symbol_type: AnnotationSymbolType = Field(alias="symbolType")
    rotation_deg: float = Field(default=0.0, alias="rotationDeg")
    scale: float = Field(default=1.0, gt=0)
    colour: str = Field(default="#202020")


class SpotElevationElem(BaseModel):
    """ANN-02 — view-local spot elevation annotation (diamond symbol + text)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["spot_elevation"] = "spot_elevation"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    elevation_mm: float = Field(alias="elevationMm")
    prefix: str = Field(default="")
    suffix: str = Field(default="")
    colour: str = Field(default="#202020")


class SpotCoordinateElem(BaseModel):
    """ANN-09 — view-local spot coordinate annotation (N/E at a point)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["spot_coordinate"] = "spot_coordinate"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    north_mm: float = Field(alias="northMm")
    east_mm: float = Field(alias="eastMm")
    colour: str = Field(default="#202020")


SpotSlopeFormat = Literal["percent", "ratio", "degree"]


class SpotSlopeElem(BaseModel):
    """ANN-10 — view-local spot slope annotation."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["spot_slope"] = "spot_slope"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    slope_pct: float = Field(alias="slopePct")
    slope_format: SpotSlopeFormat = Field(default="percent", alias="slopeFormat")
    colour: str = Field(default="#202020")


class InsulationAnnotationElem(BaseModel):
    """ANN-11 — view-local insulation annotation (zigzag line)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["insulation_annotation"] = "insulation_annotation"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    start_mm: Vec2Mm = Field(alias="startMm")
    end_mm: Vec2Mm = Field(alias="endMm")
    width_mm: float = Field(default=200.0, alias="widthMm", gt=0)
    colour: str = Field(default="#202020")


class RadialDimensionElem(BaseModel):
    """ANN-06 — radial dimension from arc center to arc point."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["radial_dimension"] = "radial_dimension"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    center_mm: Vec2Mm = Field(alias="centerMm")
    arc_point_mm: Vec2Mm = Field(alias="arcPointMm")
    colour: str = Field(default="#202020")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


class DiameterDimensionElem(BaseModel):
    """ANN-07 — diameter dimension across a circle."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["diameter_dimension"] = "diameter_dimension"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    center_mm: Vec2Mm = Field(alias="centerMm")
    arc_point_mm: Vec2Mm = Field(alias="arcPointMm")
    colour: str = Field(default="#202020")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


class ArcLengthDimensionElem(BaseModel):
    """ANN-08 — arc length dimension on a curved segment."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["arc_length_dimension"] = "arc_length_dimension"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    center_mm: Vec2Mm = Field(alias="centerMm")
    radius_mm: float = Field(alias="radiusMm", gt=0)
    start_angle_deg: float = Field(alias="startAngleDeg")
    end_angle_deg: float = Field(alias="endAngleDeg")
    colour: str = Field(default="#202020")
    auto_generated: bool = Field(default=False, alias="autoGenerated")


class MaterialTagElem(BaseModel):
    """ANN-12 — view-local material layer tag."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["material_tag"] = "material_tag"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    host_element_id: str = Field(alias="hostElementId")
    layer_index: int = Field(default=0, alias="layerIndex", ge=0)
    position_mm: Vec2Mm = Field(alias="positionMm")
    text_override: str | None = Field(default=None, alias="textOverride")
    leader_end_mm: Vec2Mm | None = Field(default=None, alias="leaderEndMm")
    colour: str = Field(default="#202020")


class MultiCategoryTagElem(BaseModel):
    """ANN-13 — view-local multi-category tag (type mark)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["multi_category_tag"] = "multi_category_tag"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    host_element_id: str = Field(alias="hostElementId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    parameter_name: str = Field(default="Type Mark", alias="parameterName")
    text_override: str | None = Field(default=None, alias="textOverride")
    colour: str = Field(default="#202020")


class TreadNumberElem(BaseModel):
    """ANN-14 — auto-numbered tread annotation for a stair."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["tread_number"] = "tread_number"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    stair_element_id: str = Field(alias="stairElementId")
    start_number: int = Field(default=1, alias="startNumber", ge=1)
    colour: str = Field(default="#202020")


KeynoteTarget = Literal["element", "material", "user"]


class KeynoteElem(BaseModel):
    """ANN-15 — view-local keynote annotation linking to a key/description."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["keynote"] = "keynote"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    keynote_key: str = Field(alias="keynoteKey")
    keynote_text: str = Field(default="", alias="keynoteText")
    target: KeynoteTarget = Field(default="user")
    host_element_id: str | None = Field(default=None, alias="hostElementId")
    colour: str = Field(default="#202020")


class SpanDirectionElem(BaseModel):
    """ANN-16 — floor slab span direction arrow annotation."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["span_direction"] = "span_direction"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    direction_deg: float = Field(default=0.0, alias="directionDeg")
    length_mm: float = Field(default=800.0, alias="lengthMm", gt=0)
    colour: str = Field(default="#202020")


DetailComponentShape = Literal[
    "us_wide_flange_beam",
    "concrete_column_square",
    "concrete_column_round",
    "steel_angle",
    "steel_channel",
    "bolt",
    "weld_symbol",
    "break_line",
    "centerline_end",
]


class DetailComponentElem(BaseModel):
    """ANN-17 — view-local 2D detail component (predefined shape)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["detail_component"] = "detail_component"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    component_shape: DetailComponentShape = Field(alias="componentShape")
    rotation_deg: float = Field(default=0.0, alias="rotationDeg")
    scale: float = Field(default=1.0, gt=0)
    colour: str = Field(default="#202020")


class RepeatingDetailElem(BaseModel):
    """ANN-18 — view-local repeating detail component pattern along a line."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["repeating_detail"] = "repeating_detail"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    start_mm: Vec2Mm = Field(alias="startMm")
    end_mm: Vec2Mm = Field(alias="endMm")
    component_shape: DetailComponentShape = Field(alias="componentShape")
    spacing_mm: float = Field(default=200.0, alias="spacingMm", gt=0)
    colour: str = Field(default="#202020")


class DetailGroupElem(BaseModel):
    """ANN-19 — named group of view-local detail elements."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["detail_group"] = "detail_group"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    name: str = Field(default="Group")
    member_ids: list[str] = Field(alias="memberIds")


class ColorFillLegendElem(BaseModel):
    """ANN-20 — view-local color fill legend box (room colour scheme legend)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    kind: Literal["color_fill_legend"] = "color_fill_legend"
    id: str
    host_view_id: str = Field(alias="hostViewId")
    position_mm: Vec2Mm = Field(alias="positionMm")
    scheme_parameter: str = Field(default="Name", alias="schemeParameter")
    title: str = Field(default="Color Fill Legend")

