# ruff: noqa: I001

from bim_ai.engine import (
    Any,
    AnnotationSymbolElem,
    ApplyPlanViewTemplateCmd,
    CalloutElem,
    ClearAutoGeneratedAnnotationsCmd,
    CreateAnnotationSymbolCmd,
    CreateCalloutCmd,
    CreateDetailLineCmd,
    CreateDetailRegionCmd,
    CreateElevationViewCmd,
    CreateJoinGeometryCmd,
    CreatePlanRegionCmd,
    CreatePropertyDefinitionCmd,
    CreatePropertyLineCmd,
    CreateReferencePlaneCmd,
    CreateScheduleViewCmd,
    CreateSectionCutCmd,
    CreateTextNoteCmd,
    DeletePlanRegionCmd,
    DeletePropertyLineCmd,
    DeleteReferencePlaneCmd,
    DetailLineElem,
    DetailRegionElem,
    DimensionElem,
    ElevationViewElem,
    JoinGeometryElem,
    LevelElem,
    PlaceTagCmd,
    PlacedTagElem,
    PlanCategoryGraphicRow,
    PlanRegionElem,
    PlanTagStyleElem,
    PlanViewElem,
    PropertyDefinitionElem,
    PropertyLineElem,
    ReferencePlaneElem,
    RoomElem,
    ScheduleElem,
    SectionCutElem,
    SetElementPropCmd,
    SheetElem,
    TagDefinitionElem,
    TextNoteElem,
    UpdatePlanRegionCmd,
    UpdatePlanViewCropCmd,
    UpdatePlanViewRangeCmd,
    UpdatePropertyLineCmd,
    UpdateReferencePlaneCmd,
    UpsertPlanTagStyleCmd,
    UpsertPlanViewCmd,
    UpsertPlanViewTemplateCmd,
    UpsertRoomVolumeCmd,
    UpsertScheduleCmd,
    UpsertScheduleFiltersCmd,
    UpsertSheetCmd,
    UpsertSheetViewportsCmd,
    UpsertTagDefinitionCmd,
    UpsertViewTemplateCmd,
    ViewTemplateElem,
    _clamp_unit_interval,
    _normalize_plan_tag_label_fields,
    _optional_plan_detail_override,
    _optional_room_fill_scale,
    _plan_detail_default_medium,
    _validate_plan_tag_style_ref,
    new_id,
    normalize_plan_category_graphics_rows,
)


def try_apply_documentation_command(doc, cmd, *, source_provider=None) -> bool:
    els = doc.elements
    match cmd:
        case CreatePlanRegionCmd():
            pid = cmd.id or new_id()
            if pid in els:
                raise ValueError(f"duplicate element id '{pid}'")
            if cmd.level_id not in els or not isinstance(els[cmd.level_id], LevelElem):
                raise ValueError("createPlanRegion.levelId must reference Level")
            if len(cmd.outline_mm) < 3:
                raise ValueError("createPlanRegion outline requires ≥3 vertices")
            els[pid] = PlanRegionElem(
                kind="plan_region",
                id=pid,
                name=cmd.name,
                level_id=cmd.level_id,
                outline_mm=cmd.outline_mm,
                cut_plane_offset_mm=cmd.cut_plane_offset_mm,
            )

        case UpdatePlanRegionCmd():
            pr = els.get(cmd.id)
            if not isinstance(pr, PlanRegionElem):
                raise ValueError("updatePlanRegion.id must reference an existing plan_region")
            updates_pr: dict[str, Any] = {}
            if cmd.name is not None:
                updates_pr["name"] = cmd.name
            if cmd.outline_mm is not None:
                if len(cmd.outline_mm) < 3:
                    raise ValueError("updatePlanRegion.outlineMm requires ≥3 vertices")
                updates_pr["outline_mm"] = list(cmd.outline_mm)
            if cmd.cut_plane_offset_mm is not None:
                updates_pr["cut_plane_offset_mm"] = cmd.cut_plane_offset_mm
            els[cmd.id] = pr.model_copy(update=updates_pr)

        case DeletePlanRegionCmd():
            pr = els.get(cmd.id)
            if not isinstance(pr, PlanRegionElem):
                raise ValueError("deletePlanRegion.id must reference an existing plan_region")
            del els[cmd.id]

        case UpsertTagDefinitionCmd():
            tid_cmd = cmd.id or new_id()
            tag_kind_literal = (
                cmd.tag_kind
                if cmd.tag_kind in {"room", "sill", "slab_finish", "custom"}
                else "custom"
            )
            els[tid_cmd] = TagDefinitionElem(
                kind="tag_definition",
                id=tid_cmd,
                name=cmd.name,
                tag_kind=tag_kind_literal,  # type: ignore[arg-type]
                discipline=cmd.discipline,
            )

        case CreateJoinGeometryCmd():
            jid = cmd.id or new_id()
            if jid in els:
                raise ValueError(f"duplicate element id '{jid}'")
            for jid_ref in cmd.joined_element_ids:
                if jid_ref not in els:
                    raise ValueError(f"join_geometry joinedElementIds unknown '{jid_ref}'")
            els[jid] = JoinGeometryElem(
                kind="join_geometry",
                id=jid,
                joined_element_ids=cmd.joined_element_ids,
                notes=cmd.notes,
            )

        case CreateSectionCutCmd():
            scid = cmd.id or new_id()
            if scid in els:
                raise ValueError(f"duplicate element id '{scid}'")
            els[scid] = SectionCutElem(
                kind="section_cut",
                id=scid,
                name=cmd.name,
                line_start_mm=cmd.line_start_mm,
                line_end_mm=cmd.line_end_mm,
                crop_depth_mm=cmd.crop_depth_mm,
            )

        case CreateElevationViewCmd():
            evid = cmd.id or new_id()
            if evid in els:
                raise ValueError(f"duplicate element id '{evid}'")
            if cmd.direction == "custom" and cmd.custom_angle_deg is None:
                raise ValueError(
                    "createElevationView.customAngleDeg required when direction=custom"
                )
            els[evid] = ElevationViewElem(
                kind="elevation_view",
                id=evid,
                name=cmd.name,
                direction=cmd.direction,
                custom_angle_deg=cmd.custom_angle_deg,
                crop_min_mm=cmd.crop_min_mm,
                crop_max_mm=cmd.crop_max_mm,
                scale=cmd.scale,
                plan_detail_level=cmd.plan_detail_level,
            )

        case PlaceTagCmd():
            tid = cmd.id or new_id()
            if tid in els:
                raise ValueError(f"duplicate element id '{tid}'")
            host = els.get(cmd.host_element_id)
            if host is None:
                raise ValueError("placeTag.hostElementId references unknown element")
            if host.kind not in {"room", "door", "window"}:
                raise ValueError("placeTag.hostElementId must reference room/door/window")
            view = els.get(cmd.host_view_id)
            if view is None or view.kind not in {"plan_view", "section_cut", "elevation_view"}:
                raise ValueError(
                    "placeTag.hostViewId must reference plan_view/section_cut/elevation_view"
                )
            els[tid] = PlacedTagElem(
                kind="placed_tag",
                id=tid,
                host_element_id=cmd.host_element_id,
                host_view_id=cmd.host_view_id,
                position_mm=cmd.position_mm,
                tag_definition_id=cmd.tag_definition_id,
                text_override=cmd.text_override,
                auto_generated=cmd.auto_generated,
            )

        case ClearAutoGeneratedAnnotationsCmd():
            scope = cmd.scope
            host_view_id = cmd.host_view_id
            to_delete: list[str] = []
            for eid, el in els.items():
                if scope in {"dimensions", "both"} and isinstance(el, DimensionElem):
                    if el.auto_generated:
                        to_delete.append(eid)
                if scope in {"tags", "both"} and isinstance(el, PlacedTagElem):
                    if el.auto_generated and (
                        host_view_id is None or el.host_view_id == host_view_id
                    ):
                        to_delete.append(eid)
            for eid in to_delete:
                del els[eid]

        case CreateDetailLineCmd():
            did = cmd.id or new_id()
            if did in els:
                raise ValueError(f"duplicate element id '{did}'")
            view = els.get(cmd.host_view_id)
            if view is None or view.kind not in {"plan_view", "section_cut", "elevation_view"}:
                raise ValueError(
                    "createDetailLine.hostViewId must reference plan_view/section_cut/elevation_view"
                )
            if len(cmd.points_mm) < 2:
                raise ValueError("createDetailLine.pointsMm must contain at least 2 points")
            els[did] = DetailLineElem(
                kind="detail_line",
                id=did,
                host_view_id=cmd.host_view_id,
                points_mm=list(cmd.points_mm),
                stroke_mm=cmd.stroke_mm,
                colour=cmd.colour,
                style=cmd.style,
            )

        case CreateDetailRegionCmd():
            did = cmd.id or new_id()
            if did in els:
                raise ValueError(f"duplicate element id '{did}'")
            view = els.get(cmd.host_view_id)
            if view is None or view.kind not in {"plan_view", "section_cut", "elevation_view"}:
                raise ValueError(
                    "createDetailRegion.hostViewId must reference plan_view/section_cut/elevation_view"
                )
            if len(cmd.boundary_mm) < 3:
                raise ValueError("createDetailRegion.boundaryMm must contain at least 3 points")
            els[did] = DetailRegionElem(
                kind="detail_region",
                id=did,
                host_view_id=cmd.host_view_id,
                boundary_mm=list(cmd.boundary_mm),
                fill_colour=cmd.fill_colour,
                fill_pattern=cmd.fill_pattern,
                stroke_mm=cmd.stroke_mm,
                stroke_colour=cmd.stroke_colour,
            )

        case CreateTextNoteCmd():
            tid = cmd.id or new_id()
            if tid in els:
                raise ValueError(f"duplicate element id '{tid}'")
            view = els.get(cmd.host_view_id)
            if view is None or view.kind not in {"plan_view", "section_cut", "elevation_view"}:
                raise ValueError(
                    "createTextNote.hostViewId must reference plan_view/section_cut/elevation_view"
                )
            if not cmd.text:
                raise ValueError("createTextNote.text must be non-empty")
            els[tid] = TextNoteElem(
                kind="text_note",
                id=tid,
                host_view_id=cmd.host_view_id,
                position_mm=cmd.position_mm,
                text=cmd.text,
                font_size_mm=cmd.font_size_mm,
                anchor=cmd.anchor,
                rotation_deg=cmd.rotation_deg,
                colour=cmd.colour,
            )

        case CreateAnnotationSymbolCmd():
            sid = cmd.id or new_id()
            if sid in els:
                raise ValueError(f"duplicate element id '{sid}'")
            view = els.get(cmd.host_view_id)
            if view is None or view.kind not in {"plan_view", "section_cut", "elevation_view"}:
                raise ValueError(
                    "createAnnotationSymbol.hostViewId must reference plan_view/section_cut/elevation_view"
                )
            els[sid] = AnnotationSymbolElem(
                kind="annotation_symbol",
                id=sid,
                host_view_id=cmd.host_view_id,
                position_mm=cmd.position_mm,
                symbol_type=cmd.symbol_type,
                rotation_deg=cmd.rotation_deg,
                scale=cmd.scale,
                colour=cmd.colour,
            )

        case CreateReferencePlaneCmd():
            rpid = cmd.id or new_id()
            if rpid in els:
                raise ValueError(f"duplicate element id '{rpid}'")
            lvl = els.get(cmd.level_id)
            if not isinstance(lvl, LevelElem):
                raise ValueError("createReferencePlane.levelId must reference an existing Level")
            if cmd.start_mm.x_mm == cmd.end_mm.x_mm and cmd.start_mm.y_mm == cmd.end_mm.y_mm:
                raise ValueError("createReferencePlane.startMm and endMm must differ")
            if cmd.is_work_plane:
                # Only one ref plane per level may be the active work plane.
                for other_id, other in list(els.items()):
                    if (
                        isinstance(other, ReferencePlaneElem)
                        and other.level_id == cmd.level_id
                        and other.is_work_plane
                    ):
                        els[other_id] = other.model_copy(update={"is_work_plane": False})
            els[rpid] = ReferencePlaneElem(
                kind="reference_plane",
                id=rpid,
                name=cmd.name,
                level_id=cmd.level_id,
                start_mm=cmd.start_mm,
                end_mm=cmd.end_mm,
                is_work_plane=cmd.is_work_plane,
            )

        case UpdateReferencePlaneCmd():
            rp = els.get(cmd.reference_plane_id)
            if not isinstance(rp, ReferencePlaneElem):
                raise ValueError(
                    "updateReferencePlane.referencePlaneId must reference a reference_plane"
                )
            new_start = cmd.start_mm if cmd.start_mm is not None else rp.start_mm
            new_end = cmd.end_mm if cmd.end_mm is not None else rp.end_mm
            if new_start.x_mm == new_end.x_mm and new_start.y_mm == new_end.y_mm:
                raise ValueError("updateReferencePlane: startMm and endMm must differ")
            updates: dict[str, Any] = {"start_mm": new_start, "end_mm": new_end}
            if cmd.name is not None:
                updates["name"] = cmd.name
            if cmd.is_work_plane is not None:
                updates["is_work_plane"] = cmd.is_work_plane
                if cmd.is_work_plane:
                    for other_id, other in list(els.items()):
                        if (
                            other_id != cmd.reference_plane_id
                            and isinstance(other, ReferencePlaneElem)
                            and other.level_id == rp.level_id
                            and other.is_work_plane
                        ):
                            els[other_id] = other.model_copy(update={"is_work_plane": False})
            els[cmd.reference_plane_id] = rp.model_copy(update=updates)

        case DeleteReferencePlaneCmd():
            rp = els.get(cmd.reference_plane_id)
            if not isinstance(rp, ReferencePlaneElem):
                raise ValueError(
                    "deleteReferencePlane.referencePlaneId must reference a reference_plane"
                )
            del els[cmd.reference_plane_id]

        case CreatePropertyLineCmd():
            plid = cmd.id or new_id()
            if plid in els:
                raise ValueError(f"duplicate element id '{plid}'")
            if cmd.start_mm.x_mm == cmd.end_mm.x_mm and cmd.start_mm.y_mm == cmd.end_mm.y_mm:
                raise ValueError("createPropertyLine.startMm and endMm must differ")
            els[plid] = PropertyLineElem(
                kind="property_line",
                id=plid,
                name=cmd.name,
                start_mm=cmd.start_mm,
                end_mm=cmd.end_mm,
                setback_mm=cmd.setback_mm,
                classification=cmd.classification,
            )

        case UpdatePropertyLineCmd():
            pl = els.get(cmd.property_line_id)
            if not isinstance(pl, PropertyLineElem):
                raise ValueError("updatePropertyLine.propertyLineId must reference a property_line")
            new_start = cmd.start_mm if cmd.start_mm is not None else pl.start_mm
            new_end = cmd.end_mm if cmd.end_mm is not None else pl.end_mm
            if new_start.x_mm == new_end.x_mm and new_start.y_mm == new_end.y_mm:
                raise ValueError("updatePropertyLine: startMm and endMm must differ")
            updates: dict[str, Any] = {"start_mm": new_start, "end_mm": new_end}
            if cmd.name is not None:
                updates["name"] = cmd.name
            if "setback_mm" in cmd.model_fields_set:
                updates["setback_mm"] = cmd.setback_mm
            if "classification" in cmd.model_fields_set:
                updates["classification"] = cmd.classification
            els[cmd.property_line_id] = pl.model_copy(update=updates)

        case DeletePropertyLineCmd():
            pl = els.get(cmd.property_line_id)
            if not isinstance(pl, PropertyLineElem):
                raise ValueError("deletePropertyLine.propertyLineId must reference a property_line")
            del els[cmd.property_line_id]

        case UpsertViewTemplateCmd():
            vt = cmd.id or new_id()
            prior_tmpl = els.get(vt) if isinstance(els.get(vt), ViewTemplateElem) else None
            d_open = cmd.default_plan_opening_tag_style_id
            if (
                prior_tmpl is not None
                and "default_plan_opening_tag_style_id" not in cmd.model_fields_set
            ):
                d_open = prior_tmpl.default_plan_opening_tag_style_id
            if d_open is not None:
                _validate_plan_tag_style_ref(els, d_open, "opening")
            d_room = cmd.default_plan_room_tag_style_id
            if (
                prior_tmpl is not None
                and "default_plan_room_tag_style_id" not in cmd.model_fields_set
            ):
                d_room = prior_tmpl.default_plan_room_tag_style_id
            if d_room is not None:
                _validate_plan_tag_style_ref(els, d_room, "room")
            scale = (
                cmd.scale if cmd.scale in {"scale_50", "scale_100", "scale_200"} else "scale_100"
            )
            pdl = _plan_detail_default_medium(cmd.plan_detail_level)
            pfo = _clamp_unit_interval(cmd.plan_room_fill_opacity_scale, 1.0)
            pcg_t: list[PlanCategoryGraphicRow] = []
            if "plan_category_graphics" in cmd.model_fields_set:
                pcg_t = normalize_plan_category_graphics_rows(cmd.plan_category_graphics or [])
            elif prior_tmpl is not None:
                pcg_t = list(prior_tmpl.plan_category_graphics)
            els[vt] = ViewTemplateElem(
                kind="view_template",
                id=vt,
                name=cmd.name,
                scale=scale,
                disciplines_visible=list(cmd.disciplines_visible or []),
                hidden_categories=list(cmd.hidden_categories or []),
                plan_detail_level=pdl,
                plan_room_fill_opacity_scale=pfo,
                plan_show_opening_tags=cmd.plan_show_opening_tags is True,
                plan_show_room_labels=cmd.plan_show_room_labels is True,
                default_plan_opening_tag_style_id=d_open,
                default_plan_room_tag_style_id=d_room,
                plan_category_graphics=pcg_t,
            )

        case UpsertPlanViewTemplateCmd():
            vt = cmd.id or new_id()
            prior_tmpl = els.get(vt) if isinstance(els.get(vt), ViewTemplateElem) else None
            d_open = cmd.default_plan_opening_tag_style_id
            if (
                prior_tmpl is not None
                and "default_plan_opening_tag_style_id" not in cmd.model_fields_set
            ):
                d_open = prior_tmpl.default_plan_opening_tag_style_id
            if d_open is not None:
                _validate_plan_tag_style_ref(els, d_open, "opening")
            d_room = cmd.default_plan_room_tag_style_id
            if (
                prior_tmpl is not None
                and "default_plan_room_tag_style_id" not in cmd.model_fields_set
            ):
                d_room = prior_tmpl.default_plan_room_tag_style_id
            if d_room is not None:
                _validate_plan_tag_style_ref(els, d_room, "room")
            scale = (
                cmd.scale if cmd.scale in {"scale_50", "scale_100", "scale_200"} else "scale_100"
            )
            pdl = _plan_detail_default_medium(cmd.plan_detail_level)
            pfo = _clamp_unit_interval(cmd.plan_room_fill_opacity_scale, 1.0)
            pcg_t: list[PlanCategoryGraphicRow] = []
            if "plan_category_graphics" in cmd.model_fields_set:
                pcg_t = normalize_plan_category_graphics_rows(cmd.plan_category_graphics or [])
            elif prior_tmpl is not None:
                pcg_t = list(prior_tmpl.plan_category_graphics)
            vrb: float | None = cmd.view_range_bottom_mm
            if prior_tmpl is not None and "view_range_bottom_mm" not in cmd.model_fields_set:
                vrb = prior_tmpl.view_range_bottom_mm
            vrt: float | None = cmd.view_range_top_mm
            if prior_tmpl is not None and "view_range_top_mm" not in cmd.model_fields_set:
                vrt = prior_tmpl.view_range_top_mm
            els[vt] = ViewTemplateElem(
                kind="view_template",
                id=vt,
                name=cmd.name,
                scale=scale,
                disciplines_visible=list(cmd.disciplines_visible or []),
                hidden_categories=list(cmd.hidden_categories or []),
                plan_detail_level=pdl,
                plan_room_fill_opacity_scale=pfo,
                plan_show_opening_tags=cmd.plan_show_opening_tags is True,
                plan_show_room_labels=cmd.plan_show_room_labels is True,
                default_plan_opening_tag_style_id=d_open,
                default_plan_room_tag_style_id=d_room,
                plan_category_graphics=pcg_t,
                view_range_bottom_mm=vrb,
                view_range_top_mm=vrt,
            )

        case ApplyPlanViewTemplateCmd():
            pv_el = els.get(cmd.plan_view_id)
            if not isinstance(pv_el, PlanViewElem):
                raise ValueError("applyPlanViewTemplate.planViewId must reference plan_view")
            tmpl_el = els.get(cmd.template_id)
            if not isinstance(tmpl_el, ViewTemplateElem):
                raise ValueError("applyPlanViewTemplate.templateId must reference view_template")
            update: dict[str, Any] = {
                "view_template_id": cmd.template_id,
                "crop_min_mm": None,
                "crop_max_mm": None,
                "view_range_bottom_mm": tmpl_el.view_range_bottom_mm,
                "view_range_top_mm": tmpl_el.view_range_top_mm,
                "categories_hidden": list(tmpl_el.hidden_categories),
                "plan_category_graphics": list(tmpl_el.plan_category_graphics),
            }
            if tmpl_el.default_plan_opening_tag_style_id is not None:
                update["plan_opening_tag_style_id"] = tmpl_el.default_plan_opening_tag_style_id
            if tmpl_el.default_plan_room_tag_style_id is not None:
                update["plan_room_tag_style_id"] = tmpl_el.default_plan_room_tag_style_id
            els[cmd.plan_view_id] = pv_el.model_copy(update=update)

        case UpdatePlanViewCropCmd():
            pv_el = els.get(cmd.plan_view_id)
            if not isinstance(pv_el, PlanViewElem):
                raise ValueError("updatePlanViewCrop.planViewId must reference plan_view")
            els[cmd.plan_view_id] = pv_el.model_copy(
                update={
                    "crop_min_mm": cmd.crop_min_mm,
                    "crop_max_mm": cmd.crop_max_mm,
                }
            )

        case UpdatePlanViewRangeCmd():
            pv_el = els.get(cmd.plan_view_id)
            if not isinstance(pv_el, PlanViewElem):
                raise ValueError("updatePlanViewRange.planViewId must reference plan_view")
            els[cmd.plan_view_id] = pv_el.model_copy(
                update={
                    "view_range_bottom_mm": cmd.view_range_bottom_mm,
                    "view_range_top_mm": cmd.view_range_top_mm,
                }
            )

        case UpsertSheetCmd():
            sh = cmd.id or new_id()
            prior = els.get(sh)
            viewports: list[dict[str, Any]] = []
            if isinstance(prior, SheetElem):
                viewports = list(prior.viewports_mm)
            els[sh] = SheetElem(
                kind="sheet",
                id=sh,
                name=cmd.name,
                title_block=cmd.title_block,
                viewports_mm=viewports,
                paper_width_mm=float(cmd.paper_width_mm)
                if cmd.paper_width_mm is not None
                else (prior.paper_width_mm if isinstance(prior, SheetElem) else 42_000),
                paper_height_mm=float(cmd.paper_height_mm)
                if cmd.paper_height_mm is not None
                else (prior.paper_height_mm if isinstance(prior, SheetElem) else 29_700),
                titleblock_parameters=dict(cmd.titleblock_parameters or {})
                if cmd.titleblock_parameters is not None
                else (dict(prior.titleblock_parameters) if isinstance(prior, SheetElem) else {}),
            )

        case UpsertSheetViewportsCmd():
            sh_el = els.get(cmd.sheet_id)
            if not isinstance(sh_el, SheetElem):
                raise ValueError("upsertSheetViewports.sheetId must reference Sheet")
            els[cmd.sheet_id] = sh_el.model_copy(update={"viewports_mm": list(cmd.viewports_mm)})

        case UpsertScheduleCmd():
            sc = cmd.id or new_id()
            els[sc] = ScheduleElem(
                kind="schedule",
                id=sc,
                name=cmd.name,
                sheet_id=cmd.sheet_id,
                filters=dict(cmd.filters or {}),
                grouping=dict(cmd.grouping or {}),
            )

        case UpsertScheduleFiltersCmd():
            sc_el = els.get(cmd.schedule_id)
            if not isinstance(sc_el, ScheduleElem):
                raise ValueError("upsertScheduleFilters.scheduleId must reference schedule")
            merged = dict(sc_el.filters)
            merged.update(cmd.filters)
            gnext = dict(sc_el.grouping or {})
            if cmd.grouping:
                gnext.update(cmd.grouping)
            els[cmd.schedule_id] = sc_el.model_copy(update={"filters": merged, "grouping": gnext})

        case CreatePropertyDefinitionCmd():
            els[cmd.id] = PropertyDefinitionElem(
                kind="property_definition",
                id=cmd.id,
                key=cmd.key,
                label=cmd.label,
                propKind=cmd.prop_kind,
                enumValues=cmd.enum_values,
                defaultValue=cmd.default_value,
                appliesTo=cmd.applies_to,
                showInSchedule=cmd.show_in_schedule,
            )

        case SetElementPropCmd():
            target = els.get(cmd.element_id)
            if target is None:
                raise ValueError(
                    f"set_element_prop.elementId '{cmd.element_id}' not found in document"
                )
            existing_props: dict = dict(getattr(target, "props", None) or {})
            existing_props[cmd.key] = cmd.value
            els[cmd.element_id] = target.model_copy(update={"props": existing_props})

        case CreateScheduleViewCmd():
            els[cmd.id] = ScheduleElem(
                kind="schedule",
                id=cmd.id,
                name=cmd.name,
                category=cmd.category,
                columns=cmd.columns,
                filterExpr=cmd.filter_expr,
                sortKey=cmd.sort_key,
                sortDir=cmd.sort_dir,
            )

        case UpsertRoomVolumeCmd():
            r = els.get(cmd.room_id)
            if not isinstance(r, RoomElem):
                raise ValueError("upsertRoomVolume.roomId must reference Room")
            els[cmd.room_id] = r.model_copy(
                update={
                    "upper_limit_level_id": cmd.upper_limit_level_id,
                    "volume_ceiling_offset_mm": cmd.volume_ceiling_offset_mm,
                }
            )

        case UpsertPlanViewCmd():
            pvid = cmd.id or new_id()
            lvl = els.get(cmd.level_id)
            if not isinstance(lvl, LevelElem):
                raise ValueError("upsertPlanView.levelId must reference Level")
            vt_id = cmd.view_template_id
            if vt_id is not None:
                vt_el = els.get(vt_id)
                if not isinstance(vt_el, ViewTemplateElem):
                    raise ValueError("upsertPlanView.viewTemplateId must reference view_template")
            uli = cmd.underlay_level_id
            if uli is not None and uli not in els:
                raise ValueError(f"upsertPlanView underlay unknown level '{uli}'")
            pres = (
                cmd.plan_presentation
                if cmd.plan_presentation
                in {
                    "default",
                    "opening_focus",
                    "room_scheme",
                }
                else "default"
            )
            pdl_override = _optional_plan_detail_override(cmd.plan_detail_level)
            pfo_override = _optional_room_fill_scale(cmd.plan_room_fill_opacity_scale)
            prior_pv = els.get(pvid) if isinstance(els.get(pvid), PlanViewElem) else None
            open_style = cmd.plan_opening_tag_style_id
            if prior_pv is not None and "plan_opening_tag_style_id" not in cmd.model_fields_set:
                open_style = prior_pv.plan_opening_tag_style_id
            if open_style is not None:
                _validate_plan_tag_style_ref(els, open_style, "opening")
            room_style = cmd.plan_room_tag_style_id
            if prior_pv is not None and "plan_room_tag_style_id" not in cmd.model_fields_set:
                room_style = prior_pv.plan_room_tag_style_id
            if room_style is not None:
                _validate_plan_tag_style_ref(els, room_style, "room")
            pcg_pv: list[PlanCategoryGraphicRow] = []
            if "plan_category_graphics" in cmd.model_fields_set:
                pcg_pv = normalize_plan_category_graphics_rows(cmd.plan_category_graphics or [])
            elif prior_pv is not None:
                pcg_pv = list(prior_pv.plan_category_graphics)
            els[pvid] = PlanViewElem(
                kind="plan_view",
                id=pvid,
                name=cmd.name,
                level_id=cmd.level_id,
                view_template_id=cmd.view_template_id,
                plan_presentation=pres,
                underlay_level_id=cmd.underlay_level_id,
                discipline=cmd.discipline or "architecture",
                phase_id=cmd.phase_id,
                crop_min_mm=cmd.crop_min_mm,
                crop_max_mm=cmd.crop_max_mm,
                view_range_bottom_mm=cmd.view_range_bottom_mm,
                view_range_top_mm=cmd.view_range_top_mm,
                cut_plane_offset_mm=cmd.cut_plane_offset_mm,
                categories_hidden=list(cmd.categories_hidden or []),
                plan_detail_level=pdl_override,
                plan_room_fill_opacity_scale=pfo_override,
                plan_show_opening_tags=cmd.plan_show_opening_tags,
                plan_show_room_labels=cmd.plan_show_room_labels,
                plan_opening_tag_style_id=open_style,
                plan_room_tag_style_id=room_style,
                plan_category_graphics=pcg_pv,
            )

        case UpsertPlanTagStyleCmd():
            sid = cmd.id or new_id()
            prior = els.get(sid)
            if prior is not None and not isinstance(prior, PlanTagStyleElem):
                raise ValueError(
                    "upsertPlanTagStyle.id must reference plan_tag_style when element exists"
                )
            tt = cmd.tag_target
            if tt not in ("opening", "room"):
                raise ValueError("upsertPlanTagStyle.tagTarget must be opening|room")
            lf = _normalize_plan_tag_label_fields(tt, list(cmd.label_fields or []))
            els[sid] = PlanTagStyleElem(
                kind="plan_tag_style",
                id=sid,
                name=cmd.name,
                tag_target=tt,
                label_fields=lf,
                text_size_pt=float(cmd.text_size_pt),
                leader_visible=bool(cmd.leader_visible),
                badge_style=cmd.badge_style,
                color_token=str(cmd.color_token or "default"),
                sort_key=int(cmd.sort_key),
            )

        case CreateCalloutCmd():
            cid = cmd.id or new_id()
            if cid in els:
                raise ValueError(f"duplicate element id '{cid}'")
            if cmd.parent_sheet_id not in els or not isinstance(
                els[cmd.parent_sheet_id], SheetElem
            ):
                raise ValueError("createCallout.parentSheetId must reference Sheet")
            if len(cmd.outline_mm) < 3:
                raise ValueError("createCallout outline requires ≥3 vertices")
            els[cid] = CalloutElem(
                kind="callout",
                id=cid,
                name=cmd.name,
                parent_sheet_id=cmd.parent_sheet_id,
                outline_mm=cmd.outline_mm,
            )
        case _:
            return False
    return True
