from __future__ import annotations

# ruff: noqa: F401,I001

import json
import math
import uuid
from datetime import UTC, datetime
from typing import Any, Literal, cast

from pydantic import TypeAdapter

from bim_ai.clash_engine import run_clash_test
from bim_ai.commands import (
    _ALLOWED_IMAGE_PREFIXES,
    _MAX_SRC_BYTES,
    AddOptionCmd,
    AddViewBreakCmd,
    AlignElementToReferenceCmd,
    ApplyPlanViewTemplateCmd,
    ApplyViewTemplateCmd,
    AssignElementToOptionCmd,
    AssignOpeningFamilyCmd,
    AssignWallDatumConstraintsCmd,
    AttachWallTopToRoofCmd,
    BumpMonitoredRevisionsCmd,
    ClearAutoGeneratedAnnotationsCmd,
    Command,
    CommitConceptSeedCmd,
    ConsumeConceptSeedCmd,
    CreateAgentAssumptionCmd,
    CreateAgentDeviationCmd,
    CreateAreaCmd,
    CreateBalconyCmd,
    CreateBcfTopicCmd,
    CreateBeamCmd,
    CreateBrandTemplateCmd,
    CreateCalloutCmd,
    CreateCeilingCmd,
    CreateColumnCmd,
    CreateConceptSeedCmd,
    CreateConstraintCmd,
    CreateDecalCmd,
    CreateDetailLineCmd,
    CreateDetailRegionCmd,
    CreateDimensionCmd,
    CreateDormerCmd,
    CreateDraftingViewCmd,
    CreateEdgeProfileRunCmd,
    CreateElevationViewCmd,
    CreateFloorCmd,
    CreateFrameCmd,
    CreateGradedRegionCmd,
    CreateGridLineCmd,
    CreateIssueFromViolationCmd,
    CreateJoinGeometryCmd,
    CreateLevelCmd,
    CreateLinkDxfCmd,
    CreateLinkModelCmd,
    CreateMaskingRegionCmd,
    CreateMassCmd,
    CreateOptionSetCmd,
    CreatePhaseCmd,
    CreatePlanRegionCmd,
    CreatePresentationCanvasCmd,
    CreateProjectBasePointCmd,
    CreatePropertyDefinitionCmd,
    CreatePropertyLineCmd,
    CreateRailingCmd,
    CreateReferencePlaneCmd,
    CreateRoofCmd,
    CreateRoofJoinCmd,
    CreateRoofOpeningCmd,
    CreateRoomOutlineCmd,
    CreateRoomPolyCmd,
    CreateRoomRectangleCmd,
    CreateRoomSeparationCmd,
    CreateSavedViewCmd,
    CreateScheduleViewCmd,
    CreateSectionCutCmd,
    CreateSheetCmd,
    CreateSlabOpeningCmd,
    CreateSoffitCmd,
    CreateStairCmd,
    CreateSunSettingsCmd,
    CreateSurveyPointCmd,
    CreateSweepCmd,
    CreateText3dCmd,
    CreateTextNoteCmd,
    CreateToposolidCmd,
    CreateToposolidSubdivisionCmd,
    CreateViewCalloutCmd,
    CreateViewTemplateCmd,
    CreateVoidCutCmd,
    CreateWallChainCmd,
    CreateWallCmd,
    CreateWallOpeningCmd,
    CreateWallTypeCmd,
    CreateWindowLegendViewCmd,
    DeleteAreaCmd,
    DeleteBrandTemplateCmd,
    DeleteElementCmd,
    DeleteElementsCmd,
    DeleteExternalLinkCmd,
    DeleteFrameCmd,
    DeleteGradedRegionCmd,
    DeleteImageUnderlayCmd,
    DeleteLinkModelCmd,
    DeleteMaskingRegionCmd,
    DeletePhaseCmd,
    DeletePlanRegionCmd,
    DeletePropertyLineCmd,
    DeleteReferencePlaneCmd,
    DeleteSavedViewCmd,
    DeleteToposolidCmd,
    DeleteToposolidSubdivisionCmd,
    DeleteViewTemplateCmd,
    DrawDetailRegionCmd,
    ExtendFloorInsulationCmd,
    HideElementInViewCmd,
    ImportImageUnderlayCmd,
    IndexAssetCmd,
    InsertDoorOnWallCmd,
    InsertWindowOnWallCmd,
    MaterializeMassToWallsCmd,
    MirrorElementsCmd,
    MoveAssetDeltaCmd,
    MoveBeamEndpointsCmd,
    MoveColumnDeltaCmd,
    MoveElementCmd,
    MoveElementsDeltaCmd,
    MoveGridLineEndpointsCmd,
    MoveImageUnderlayCmd,
    MoveLevelElevationCmd,
    MoveProjectBasePointCmd,
    MoveSurveyPointCmd,
    MoveViewOnSheetCmd,
    MoveWallDeltaCmd,
    MoveWallEndpointsCmd,
    PinElementCmd,
    PlaceAssetCmd,
    PlaceKitCmd,
    PlaceRoomAtPointCmd,
    PlaceTagCmd,
    PlaceViewOnSheetCmd,
    ReconcileMonitoredElementCmd,
    RemoveOptionCmd,
    RemoveViewBreakCmd,
    RemoveViewFromSheetCmd,
    RenamePhaseCmd,
    ReorderFrameCmd,
    ReorderPhaseCmd,
    ReorderViewCmd,
    RestoreElementCmd,
    RotateElementsCmd,
    RotateImageUnderlayCmd,
    RotateProjectBasePointCmd,
    RunClashTestCmd,
    SaveViewpointCmd,
    ScaleImageUnderlayCmd,
    SetCurtainPanelOverrideCmd,
    SetEdgeProfileRunModeCmd,
    SetElementDisciplineCmd,
    SetElementOverrideCmd,
    SetElementPhaseCmd,
    SetElementPropCmd,
    SetPrimaryOptionCmd,
    SetRailingBalusterPatternCmd,
    SetRailingHandrailSupportsCmd,
    SetSheetTitleblockCmd,
    SetStairSubKindCmd,
    SetToolPrefCmd,
    SetViewLensCmd,
    SetViewOptionLockCmd,
    SetViewPhaseCmd,
    SetViewPhaseFilterCmd,
    SetWallJoinDisallowCmd,
    SetWallJoinVariantCmd,
    SetWallLeanTaperCmd,
    SetWallRecessZonesCmd,
    SetWallStackCmd,
    SplitWallAtCmd,
    TraceImageCmd,
    TrimElementToReferenceCmd,
    TrimExtendToCornerCmd,
    UnbindViewTemplateCmd,
    UnhideElementInViewCmd,
    UnpinElementCmd,
    UpdateAreaCmd,
    UpdateBrandTemplateCmd,
    UpdateColumnCmd,
    UpdateDetailRegionCmd,
    UpdateDoorCmd,
    UpdateElementPropertyCmd,
    UpdateExternalLinkCmd,
    UpdateFrameCmd,
    UpdateGradedRegionCmd,
    UpdateKitComponentCmd,
    UpdateLinkDxfCmd,
    UpdateLinkModelCmd,
    UpdateMaskingRegionCmd,
    UpdateMaterialPbrCmd,
    UpdateOpeningCleanroomCmd,
    UpdatePlanRegionCmd,
    UpdatePlanViewCropCmd,
    UpdatePlanViewRangeCmd,
    UpdatePresentationCanvasCmd,
    UpdatePropertyLineCmd,
    UpdateReferencePlaneCmd,
    UpdateSavedViewCmd,
    UpdateSheetMetadataCmd,
    UpdateStairTreadsCmd,
    UpdateSunSettingsCmd,
    UpdateToposolidCmd,
    UpdateToposolidSubdivisionCmd,
    UpdateViewTemplateCmd,
    UpdateWallCmd,
    UpdateWallOpeningCmd,
    UpdateWindowCmd,
    UpsertClashTestCmd,
    UpsertFamilyTypeCmd,
    UpsertFloorTypeCmd,
    UpsertPlanTagStyleCmd,
    UpsertPlanViewCmd,
    UpsertPlanViewTemplateCmd,
    UpsertProjectSettingsCmd,
    UpsertRoofTypeCmd,
    UpsertRoomColorSchemeCmd,
    UpsertRoomVolumeCmd,
    UpsertScheduleCmd,
    UpsertScheduleFiltersCmd,
    UpsertSelectionSetCmd,
    UpsertSheetCmd,
    UpsertSheetViewportsCmd,
    UpsertSiteCmd,
    UpsertTagDefinitionCmd,
    UpsertValidationRuleCmd,
    UpsertViewTemplateCmd,
    UpsertWallTypeCmd,
)
from bim_ai.constraints import Violation, evaluate
from bim_ai.datum_levels import (
    expected_level_elevation_from_parent,
    propagate_dependent_level_elevations,
)
from bim_ai.document import Document
from bim_ai.elements import (
    DEFAULT_DISCIPLINE_BY_KIND,
    DEFAULT_TITLEBLOCK_TYPE,
    INTERNAL_ORIGIN_ID,
    SUN_SETTINGS_ID,
    AgentAssumptionElem,
    AgentDeviationElem,
    AreaElem,
    AssetLibraryEntryElem,
    AssetParamEntry,
    BalconyElem,
    BalusterPattern,
    BcfElem,
    BeamElem,
    BrandTemplateElem,
    CalloutElem,
    CeilingElem,
    ClashResultSpec,
    ClashTestElem,
    ColumnElem,
    ConceptSeedElem,
    ConstraintElem,
    ConstraintRefRow,
    DecalElem,
    DetailLineElem,
    DetailRegionElem,
    DimensionElem,
    DoorElem,
    DormerElem,
    EdgeProfileRunElem,
    Element,
    ElementOverrideSpec,
    ElevationViewElem,
    FamilyCatalogSource,
    FamilyKitInstanceElem,
    FamilyTypeElem,
    FloorElem,
    FloorTypeElem,
    FrameElem,
    GradedRegionElem,
    GridLineElem,
    HandrailSupport,
    HatchPatternDefElem,
    ImageUnderlayElem,
    InternalOriginElem,
    IssueElem,
    JoinGeometryElem,
    KitComponent,
    LevelElem,
    LinkDxfElem,
    LinkModelElem,
    MaskingRegionElem,
    MassElem,
    MaterialElem,
    PhaseElem,
    PhaseFilter,
    PlacedAssetElem,
    PlacedTagElem,
    PlanCategoryGraphicRow,
    PlanDetailLevelPlan,
    PlanRegionElem,
    PlanTagStyleElem,
    PlanViewElem,
    PresentationCanvasElem,
    ProjectBasePointElem,
    ProjectSettingsElem,
    PropertyDefinitionElem,
    PropertyLineElem,
    RailingElem,
    ReferencePlaneElem,
    RoofElem,
    RoofJoinElem,
    RoofOpeningElem,
    RoofTypeElem,
    RoomColorSchemeElem,
    RoomColorSchemeRow,
    RoomElem,
    RoomSeparationElem,
    SavedViewElem,
    ScheduleElem,
    SectionCutElem,
    SelectionSetElem,
    SelectionSetRuleSpec,
    SheetElem,
    SheetMetadata,
    SheetXY,
    SiteContextObjectRow,
    SiteElem,
    SlabOpeningElem,
    SoffitElem,
    StairElem,
    StairLanding,
    StairRun,
    StairTreadLine,
    SunSettingsElem,
    SunSettingsTimeOfDay,
    SurveyPointElem,
    SweepElem,
    TagDefinitionElem,
    Text3dElem,
    TextNoteElem,
    ToposolidElem,
    ToposolidSubdivisionElem,
    ValidationRuleElem,
    Vec2Mm,
    ViewBreakSpec,
    ViewElem,
    ViewPlacement,
    ViewpointElem,
    ViewTemplateElem,
    VoidCutElem,
    WallBasisLine,
    WallEdgeFixed,
    WallEdgeSpan,
    WallEdgeSpec,
    WallElem,
    WallOpeningElem,
    WallStack,
    WallStackComponent,
    WallTypeElem,
    WindowElem,
    WindowLegendViewElem,
)
from bim_ai.engine_mirror import (
    _mirror_one as _mirror_one,
)
from bim_ai.engine_mirror import (
    _mirror_polygon as _mirror_polygon,
)
from bim_ai.engine_mirror import (
    _mirror_wall as _mirror_wall,
)
from bim_ai.engine_mirror import (
    _reflect_point_xy_mm as _reflect_point_xy_mm,
)
from bim_ai.engine_mirror import (
    _reflect_vec2_mm as _reflect_vec2_mm,
)
from bim_ai.engine_mirror import (
    apply_mirror_elements as _apply_mirror_elements_impl,
)
from bim_ai.engine_mirror import (
    mirror_advisories_for_command as mirror_advisories_for_command,
)
from bim_ai.engine_plan_mesh import (
    LineSegment as LineSegment,
)
from bim_ai.engine_plan_mesh import (
    planDoorMesh as planDoorMesh,
)
from bim_ai.engine_plan_mesh import (
    planFamilyInstanceMesh as planFamilyInstanceMesh,
)
from bim_ai.engine_plan_mesh import (
    planStairMesh as planStairMesh,
)
from bim_ai.engine_plan_mesh import (
    planWindowMesh as planWindowMesh,
)
from bim_ai.engine_replay_diagnostics import (
    AGENT_LARGE_BUNDLE_ADVISORY_TEXT_V1 as AGENT_LARGE_BUNDLE_ADVISORY_TEXT_V1,
)
from bim_ai.engine_replay_diagnostics import (
    REPLAY_DIAGNOSTICS_BUDGET_MS_CI as REPLAY_DIAGNOSTICS_BUDGET_MS_CI,
)
from bim_ai.engine_replay_diagnostics import (
    REPLAY_DIAGNOSTICS_BUDGET_MS_LOCAL as REPLAY_DIAGNOSTICS_BUDGET_MS_LOCAL,
)
from bim_ai.engine_replay_diagnostics import (
    REPLAY_LARGE_BUNDLE_WARN_COMMAND_COUNT as REPLAY_LARGE_BUNDLE_WARN_COMMAND_COUNT,
)
from bim_ai.engine_replay_diagnostics import (
    bundle_replay_diagnostics as bundle_replay_diagnostics,
)
from bim_ai.engine_replay_diagnostics import (
    replay_performance_budget_v1 as replay_performance_budget_v1,
)
from bim_ai.engine_visibility import (
    element_passes_lens as element_passes_lens,
)
from bim_ai.engine_visibility import (
    element_passes_phase_filter as element_passes_phase_filter,
)
from bim_ai.engine_visibility import (
    is_element_pinned as is_element_pinned,
)
from bim_ai.engine_visibility import (
    phase_render_style as phase_render_style,
)
from bim_ai.engine_visibility import (
    resolve_visible_elements as resolve_visible_elements,
)
from bim_ai.engine_visibility import (
    supports_pin as _supports_pin,
)
from bim_ai.engine_wall_helpers import (
    resolve_stack_wall_type_at_cut as resolve_stack_wall_type_at_cut,
)
from bim_ai.engine_wall_helpers import (
    resolve_wall_face_offset_at_cut as resolve_wall_face_offset_at_cut,
)
from bim_ai.engine_wall_helpers import (
    schedule_stacked_components as schedule_stacked_components,
)
from bim_ai.export_ifc import (
    AUTHORITATIVE_REPLAY_KIND_V0,
    KERNEL_IFC_AUTHORITATIVE_REPLAY_SCHEMA_VERSION,
)
from bim_ai.link_expansion import SourceDocProvider
from bim_ai.material_catalog import resolve_material
from bim_ai.monitored import (
    bump_monitored_revisions,
    reconcile_monitored_element,
)
from bim_ai.plan_category_graphics import (
    normalize_plan_category_graphics_rows,
    parse_plan_category_graphics_property_json,
)
from bim_ai.roof_geometry import (
    RoofGeometryMode,
    assert_valid_gable_pitched_rectangle_footprint_mm,
    assert_valid_hip_footprint_mm,
    assert_valid_l_shape_footprint_mm,
    edge_profile_run_path_mm,
    outer_rect_extent,
)

_AUTHORITATIVE_REPLAY_V0_TYPES: frozenset[str] = frozenset(
    {
        "createLevel",
        "createFloor",
        "createWall",
        "createRoof",
        "createRoomOutline",
        "createStair",
        "insertDoorOnWall",
        "insertWindowOnWall",
        "createSlabOpening",
        "createRoofOpening",
    }
)

command_adapter = TypeAdapter(Command)
element_adapter = TypeAdapter(Element)


def new_id() -> str:
    return str(uuid.uuid4())


def _clamp_unit_interval(x: float | None, default: float = 1.0) -> float:
    if x is None:
        return default
    return max(0.0, min(1.0, float(x)))


def _plan_detail_default_medium(raw: str | None) -> PlanDetailLevelPlan:
    if raw == "coarse":
        return "coarse"
    if raw == "fine":
        return "fine"
    if raw == "medium":
        return "medium"
    return "medium"


def _optional_plan_detail_override(raw: str | None) -> PlanDetailLevelPlan | None:
    if raw is None:
        return None
    if raw not in {"coarse", "medium", "fine"}:
        raise ValueError("planDetailLevel must be coarse|medium|fine")
    return cast(PlanDetailLevelPlan, raw)


def _optional_room_fill_scale(raw: float | None) -> float | None:
    if raw is None:
        return None
    return max(0.0, min(1.0, float(raw)))


def _parse_plan_view_bool_override(raw: str) -> bool | None:
    s = raw.strip().lower()
    if s == "":
        return None
    if s in {"true", "1"}:
        return True
    if s in {"false", "0"}:
        return False
    raise ValueError(
        "planShowOpeningTags/planShowRoomLabels(plan_view): use true|false or empty string to inherit"
    )


def _parse_view_template_bool(raw: str) -> bool:
    s = raw.strip().lower()
    if s in {"true", "1"}:
        return True
    if s in {"false", "0"}:
        return False
    raise ValueError("planShowOpeningTags/planShowRoomLabels(view_template): must be true|false")


_OPENING_LABEL_FIELD_ORDER = (
    "name",
    "programmeCode",
    "elementId",
    "widthMm",
    "heightMm",
    "sillHeightMm",
)
_ROOM_LABEL_FIELD_ORDER = (
    "name",
    "programmeCode",
    "elementId",
    "department",
    "functionLabel",
    "finishSet",
    "targetAreaM2",
)


def _normalize_plan_tag_label_fields(
    target: Literal["opening", "room"],
    fields: list[str],
) -> list[str]:
    allowed = _OPENING_LABEL_FIELD_ORDER if target == "opening" else _ROOM_LABEL_FIELD_ORDER
    allowed_set = frozenset(allowed)
    seen: set[str] = set()
    out: list[str] = []
    for f in fields:
        if f not in allowed_set or f in seen:
            continue
        seen.add(f)
        out.append(f)
    return out


def _validate_plan_tag_style_ref(
    els: dict[str, Element],
    ref: str | None,
    lane: Literal["opening", "room"],
) -> None:
    if not ref:
        return
    el = els.get(ref)
    if not isinstance(el, PlanTagStyleElem):
        raise ValueError("plan tag style ref must reference plan_tag_style")
    if el.tag_target != lane:
        raise ValueError(
            f"plan tag style targets '{el.tag_target}' but this slot expects '{lane}' elements"
        )


def _stripped_optional_str(val: str | None) -> str | None:
    if val is None:
        return None
    t = val.strip()
    return t or None


def _validate_stair_sub_kind(
    sub_kind: str,
    floating_host_wall_id: str | None,
    floating_tread_depth_mm: float | None,
    els: dict,
) -> None:
    """Validate stair sub-kind fields against the element store."""
    if sub_kind == "floating":
        if not floating_host_wall_id:
            raise ValueError("'floating' stair requires floatingHostWallId")
        host = els.get(floating_host_wall_id)
        if not isinstance(host, WallElem):
            raise ValueError(f"floatingHostWallId '{floating_host_wall_id}' must reference a Wall")
        if floating_tread_depth_mm is not None and floating_tread_depth_mm <= 0:
            raise ValueError("floatingTreadDepthMm must be > 0")
    if sub_kind == "monolithic" and floating_host_wall_id is not None:
        raise ValueError("'monolithic' stair must not set floatingHostWallId")


def _balance_tread_risers(
    tread_lines: list[StairTreadLine],
    total_rise_mm: float,
) -> list[float]:
    """Return a riser height per tread. Lines with riserHeightMm set are
    pinned; nulls receive an equal share of the remaining rise."""
    pinned_sum = sum(tl.riser_height_mm for tl in tread_lines if tl.riser_height_mm is not None)
    null_count = sum(1 for tl in tread_lines if tl.riser_height_mm is None)
    if pinned_sum > total_rise_mm + 1e-6:
        raise ValueError(
            f"pinned riser heights sum ({pinned_sum:.1f} mm) exceeds totalRiseMm ({total_rise_mm:.1f} mm)"
        )
    remaining = total_rise_mm - pinned_sum
    null_share = remaining / null_count if null_count > 0 else 0.0
    return [
        tl.riser_height_mm if tl.riser_height_mm is not None else null_share for tl in tread_lines
    ]


def _validate_stair_boundary(points: list[Vec2Mm]) -> None:
    """Raise ValueError for invalid stair boundary polygons."""
    if len(points) < 3:
        raise ValueError("stair boundary must have ≥ 3 points")
    n = len(points)
    # Self-intersection check runs before area so bowtie shapes get the right error.
    for i in range(n):
        ax, ay = points[i].x_mm, points[i].y_mm
        bx, by = points[(i + 1) % n].x_mm, points[(i + 1) % n].y_mm
        for j in range(i + 2, n):
            if i == 0 and j == n - 1:
                continue
            cx, cy = points[j].x_mm, points[j].y_mm
            dx, dy = points[(j + 1) % n].x_mm, points[(j + 1) % n].y_mm
            rx, ry = bx - ax, by - ay
            sx, sy = dx - cx, dy - cy
            denom = rx * sy - ry * sx
            if abs(denom) < 1e-7:
                continue
            qpx, qpy = cx - ax, cy - ay
            t = (qpx * sy - qpy * sx) / denom
            u = (qpx * ry - qpy * rx) / denom
            eps = 1e-6
            if (eps < t < 1.0 - eps) and (eps < u < 1.0 - eps):
                raise ValueError(f"stair boundary is self-intersecting (edge {i} crosses edge {j})")
    area2 = 0.0
    for i in range(n):
        a = points[i]
        b = points[(i + 1) % n]
        area2 += a.x_mm * b.y_mm - b.x_mm * a.y_mm
    if abs(area2) < 1.0:
        raise ValueError("stair boundary has zero area")


def _materialize_stair_runs_and_landings(
    cmd: CreateStairCmd,
) -> tuple[list[StairRun], list[StairLanding]]:
    """KRN-07: derive runs/landings from a CreateStairCmd.

    - Explicit runs[] passed by the caller win.
    - For shape='straight' with no runs, derive a single run from runStartMm/runEndMm.
    - For shape='l_shape'/'u_shape' with caller-supplied runs but no landings,
      auto-derive a rectangular landing per gap from adjacent run endpoints + width.
    """

    runs = list(cmd.runs)
    landings = list(cmd.landings)

    if not runs and cmd.shape == "straight":
        runs = [
            StairRun(
                id=f"{cmd.id or 'stair'}-run-1",
                start_mm=cmd.run_start_mm,
                end_mm=cmd.run_end_mm,
                width_mm=cmd.width_mm,
                riser_count=8,
            )
        ]

    if cmd.shape in ("l_shape", "u_shape") and runs and not landings:
        for i in range(len(runs) - 1):
            a = runs[i]
            b = runs[i + 1]
            landings.append(_auto_landing_for_gap(f"{cmd.id or 'stair'}-landing-{i + 1}", a, b))

    if cmd.shape == "spiral" and not runs:
        assert cmd.center_mm is not None
        assert cmd.inner_radius_mm is not None
        assert cmd.outer_radius_mm is not None
        assert cmd.total_rotation_deg is not None
        assert cmd.riser_count is not None and cmd.riser_count >= 1
        polyline = _spiral_polyline(
            cmd.center_mm,
            cmd.inner_radius_mm,
            cmd.outer_radius_mm,
            cmd.total_rotation_deg,
            cmd.riser_count,
        )
        runs = [
            StairRun(
                id=f"{cmd.id or 'stair'}-run-1",
                start_mm=polyline[0],
                end_mm=polyline[-1],
                width_mm=cmd.outer_radius_mm - cmd.inner_radius_mm,
                riser_count=cmd.riser_count,
                polyline_mm=polyline,
            )
        ]

    if cmd.shape == "sketch" and not runs:
        assert cmd.sketch_path_mm is not None and len(cmd.sketch_path_mm) >= 2
        polyline = list(cmd.sketch_path_mm)
        riser_count = cmd.riser_count if cmd.riser_count else max(len(polyline) - 1, 1)
        runs = [
            StairRun(
                id=f"{cmd.id or 'stair'}-run-1",
                start_mm=polyline[0],
                end_mm=polyline[-1],
                width_mm=cmd.width_mm,
                riser_count=riser_count,
                polyline_mm=polyline,
            )
        ]

    if cmd.authoring_mode == "by_sketch" and cmd.tread_lines:
        stair_id = cmd.id or "stair"
        runs = []
        for i in range(len(cmd.tread_lines) - 1):
            tl_a = cmd.tread_lines[i]
            tl_b = cmd.tread_lines[i + 1]
            mid_a = Vec2Mm(
                xMm=(tl_a.from_mm.x_mm + tl_a.to_mm.x_mm) / 2,
                yMm=(tl_a.from_mm.y_mm + tl_a.to_mm.y_mm) / 2,
            )
            mid_b = Vec2Mm(
                xMm=(tl_b.from_mm.x_mm + tl_b.to_mm.x_mm) / 2,
                yMm=(tl_b.from_mm.y_mm + tl_b.to_mm.y_mm) / 2,
            )
            runs.append(
                StairRun(
                    id=f"{stair_id}-run-{i + 1}",
                    start_mm=mid_a,
                    end_mm=mid_b,
                    width_mm=cmd.width_mm,
                    riser_count=1,
                )
            )

    return runs, landings


def _spiral_polyline(
    center: Vec2Mm,
    inner_r: float,
    outer_r: float,
    total_rot_deg: float,
    riser_count: int,
) -> list[Vec2Mm]:
    """Sample the spiral midline (between inner and outer radius) at riser_count+1 points."""

    import math

    midline_r = (inner_r + outer_r) * 0.5
    total_rot_rad = math.radians(total_rot_deg)
    out: list[Vec2Mm] = []
    for i in range(riser_count + 1):
        t = i / riser_count
        theta = total_rot_rad * t
        out.append(
            Vec2Mm(
                xMm=center.x_mm + midline_r * math.cos(theta),
                yMm=center.y_mm + midline_r * math.sin(theta),
            )
        )
    return out


def _auto_landing_for_gap(landing_id: str, a: StairRun, b: StairRun) -> StairLanding:
    """KRN-07: square landing centered on the join between runs `a` and `b`.

    Uses the larger of the two run widths so the landing always covers both treads.
    """

    cx = (a.end_mm.x_mm + b.start_mm.x_mm) * 0.5
    cy = (a.end_mm.y_mm + b.start_mm.y_mm) * 0.5
    half = max(a.width_mm, b.width_mm) * 0.5
    return StairLanding(
        id=landing_id,
        boundary_mm=[
            Vec2Mm(xMm=cx - half, yMm=cy - half),
            Vec2Mm(xMm=cx + half, yMm=cy - half),
            Vec2Mm(xMm=cx + half, yMm=cy + half),
            Vec2Mm(xMm=cx - half, yMm=cy + half),
        ],
    )


def _room_programme_field_updates(
    programme_code: str | None,
    department: str | None,
    function_label: str | None,
    finish_set: str | None,
    target_area_m2: float | None = None,
) -> dict[str, Any]:
    out: dict[str, Any] = {
        "programme_code": _stripped_optional_str(programme_code),
        "department": _stripped_optional_str(department),
        "function_label": _stripped_optional_str(function_label),
        "finish_set": _stripped_optional_str(finish_set),
    }
    if target_area_m2 is not None:
        if target_area_m2 <= 0:
            raise ValueError("targetAreaM2 must be positive when set")
        out["target_area_m2"] = float(target_area_m2)
    return out


def coerce_command(data: dict[str, Any]) -> Command:
    return command_adapter.validate_python(data)


def _validate_wall_edge_profile_run(
    host_wall: WallElem,
    host_edge: WallEdgeSpec,
    mode: str,
) -> None:
    if isinstance(host_edge, WallEdgeSpan):
        if host_edge.start_mm < 0:
            raise ValueError("WallEdgeSpan.startMm must be >= 0")
        if host_edge.start_mm >= host_edge.end_mm:
            raise ValueError("WallEdgeSpan.startMm must be < endMm")
        if host_edge.end_mm > host_wall.height_mm:
            raise ValueError(
                f"WallEdgeSpan.endMm ({host_edge.end_mm}) exceeds "
                f"wall height ({host_wall.height_mm})"
            )


def compute_wall_corner_mitre_angle(
    wall_a_direction_deg: float,
    wall_b_direction_deg: float,
) -> float:
    interior = abs(wall_b_direction_deg - wall_a_direction_deg) % 360
    if interior > 180:
        interior = 360 - interior
    return interior / 2.0


def _parse_wall_edge_spec(host_edge: Any) -> WallEdgeSpec | None:
    if isinstance(host_edge, (WallEdgeFixed, WallEdgeSpan)):
        return host_edge
    if isinstance(host_edge, dict):
        if "kind" in host_edge and host_edge["kind"] in ("top", "bottom"):
            return WallEdgeFixed(kind=host_edge["kind"])
        if "startMm" in host_edge and "endMm" in host_edge and "kind" not in host_edge:
            return WallEdgeSpan(startMm=host_edge["startMm"], endMm=host_edge["endMm"])
    return None


def _dormer_footprint_polygon_mm(
    host: RoofElem,
    position: Any,
    width_mm: float,
    depth_mm: float,
) -> list[tuple[float, float]]:
    """KRN-14: four-corner CCW polygon of the dormer footprint in plan mm.

    Mirrors the renderer convention: width runs along the host roof's ridge
    axis (longer plan span), depth runs across.
    """

    xs = [p.x_mm for p in host.footprint_mm]
    ys = [p.y_mm for p in host.footprint_mm]
    cx = (min(xs) + max(xs)) / 2
    cy = (min(ys) + max(ys)) / 2
    span_x = max(xs) - min(xs)
    span_y = max(ys) - min(ys)
    ridge_along_x = span_x >= span_y
    half_w = width_mm / 2
    half_d = depth_mm / 2
    if ridge_along_x:
        centre_x = cx + position.along_ridge_mm
        centre_y = cy + position.across_ridge_mm
        min_x, max_x = centre_x - half_w, centre_x + half_w
        min_y, max_y = centre_y - half_d, centre_y + half_d
    else:
        centre_x = cx + position.across_ridge_mm
        centre_y = cy + position.along_ridge_mm
        min_x, max_x = centre_x - half_d, centre_x + half_d
        min_y, max_y = centre_y - half_w, centre_y + half_w
    return [
        (min_x, min_y),
        (max_x, min_y),
        (max_x, max_y),
        (min_x, max_y),
    ]


def _resolve_dormer_host_floor(
    els: dict[str, Element],
    host: RoofElem,
    fp_vertices: list[tuple[float, float]],
) -> FloorElem | None:
    """KRN-14: pick the floor on the host roof's reference level whose
    boundary contains the dormer footprint centre. Returns None when the
    reference level has no floor; falls back to the first candidate when
    the centre check is inconclusive."""

    candidates = [
        f
        for f in els.values()
        if isinstance(f, FloorElem) and f.level_id == host.reference_level_id
    ]
    if not candidates:
        return None
    centre_x = sum(v[0] for v in fp_vertices) / len(fp_vertices)
    centre_y = sum(v[1] for v in fp_vertices) / len(fp_vertices)
    for fl in candidates:
        poly = [(p.x_mm, p.y_mm) for p in fl.boundary_mm]
        if _point_in_polygon_xy(centre_x, centre_y, poly):
            return fl
    return candidates[0]


def _point_in_polygon_xy(px: float, py: float, poly: list[tuple[float, float]]) -> bool:
    n = len(poly)
    if n < 3:
        return False
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if ((yi > py) != (yj > py)) and (px < (xj - xi) * (py - yi) / (yj - yi + 1e-12) + xi):
            inside = not inside
        j = i
    return inside


def _toposolid_elevation_at_centroid_mm(els: dict[str, Any], boundary: list[Any]) -> float | None:
    """TOP-V3-01: return toposolid surface elevation (mm) at the centroid of
    ``boundary`` if any toposolid's footprint contains that centroid, else None.

    Uses a simple average-of-samples interpolation for the flat/sparse case.
    """
    if not boundary:
        return None
    cx = sum(p.x_mm for p in boundary) / len(boundary)
    cy = sum(p.y_mm for p in boundary) / len(boundary)
    for el in els.values():
        if not isinstance(el, ToposolidElem):
            continue
        poly = [(p.x_mm, p.y_mm) for p in el.boundary_mm]
        if not _point_in_polygon_xy(cx, cy, poly):
            continue
        # Interpolate elevation: use weighted average of samples if available.
        from bim_ai.site.toposolid import samples_from_toposolid

        pts = samples_from_toposolid(el)
        if not pts:
            # Flat starter — use base_elevation_mm or 0.
            return el.base_elevation_mm or 0.0
        if len(pts) == 1:
            return pts[0][2]
        # Inverse-distance weighting (IDW) for sparse samples.
        total_weight = 0.0
        weighted_z = 0.0
        for sx, sy, sz in pts:
            d = math.hypot(cx - sx, cy - sy)
            if d < 1e-6:
                return sz
            w = 1.0 / d
            total_weight += w
            weighted_z += w * sz
        return weighted_z / total_weight if total_weight > 0 else 0.0
    return None


def _dump_elements(elements: dict[str, Element]) -> dict[str, Any]:
    return {k: v.model_dump(by_alias=True) for k, v in elements.items()}


def clone_document(doc: Document) -> Document:
    payload = {
        "revision": doc.revision,
        "elements": _dump_elements(doc.elements),
        "designOptionSets": [s.model_dump(by_alias=True) for s in doc.design_option_sets],
        # CHR-V3-08: carry sticky tool prefs forward on every clone.
        "toolPrefs": {tool: dict(prefs) for tool, prefs in doc.tool_prefs.items()},
    }
    return Document.model_validate(payload)


def ensure_internal_origin(doc: Document) -> Document:
    """KRN-06: ensure the singleton `internal_origin` element exists.

    Mutates `doc.elements` in place when missing and returns the same Document.
    Idempotent. Called on model creation and on first snapshot read so legacy
    models acquire one without requiring a migration.
    """
    if any(isinstance(e, InternalOriginElem) for e in doc.elements.values()):
        return doc
    doc.elements[INTERNAL_ORIGIN_ID] = InternalOriginElem(
        kind="internal_origin", id=INTERNAL_ORIGIN_ID
    )
    return doc


CARDINAL_ELEVATION_MARKER_GROUP_ID = "elevation-marker-cardinal"
CardinalElevationDirection = Literal["north", "south", "east", "west"]
CARDINAL_ELEVATION_VIEW_SPECS: tuple[
    tuple[str, str, CardinalElevationDirection],
    ...,
] = (
    ("elevation-north", "North Elevation", "north"),
    ("elevation-south", "South Elevation", "south"),
    ("elevation-east", "East Elevation", "east"),
    ("elevation-west", "West Elevation", "west"),
)


def ensure_cardinal_elevation_views(doc: Document) -> Document:
    """F-033: seed Revit-style N/S/E/W elevation views for new project documents.

    The helper is intentionally conservative: once any elevation view exists,
    it assumes the document has been customized and will not add another
    generated set.
    """

    if any(isinstance(e, ElevationViewElem) for e in doc.elements.values()):
        return doc

    for elev_id, name, direction in CARDINAL_ELEVATION_VIEW_SPECS:
        if elev_id in doc.elements:
            continue
        doc.elements[elev_id] = ElevationViewElem(
            kind="elevation_view",
            id=elev_id,
            name=name,
            direction=direction,
            marker_group_id=CARDINAL_ELEVATION_MARKER_GROUP_ID,
            marker_slot=direction,
        )
    return doc


def ensure_sun_settings(doc: Document) -> Document:
    """SUN-V3-01: ensure the singleton `sun_settings` element exists."""
    if any(isinstance(e, SunSettingsElem) for e in doc.elements.values()):
        return doc
    doc.elements[SUN_SETTINGS_ID] = SunSettingsElem(kind="sun_settings", id=SUN_SETTINGS_ID)
    return doc


_SEED_HATCHES: list[dict] = [
    {
        "id": "brick_45",
        "name": "Brick",
        "paperMmRepeat": 73,
        "rotationDeg": 45,
        "strokeWidthMm": 0.18,
        "patternKind": "lines",
    },
    {
        "id": "concrete_dot",
        "name": "Concrete",
        "paperMmRepeat": 5,
        "rotationDeg": 0,
        "strokeWidthMm": 0.13,
        "patternKind": "dots",
    },
    {
        "id": "insulation",
        "name": "Insulation",
        "paperMmRepeat": 100,
        "rotationDeg": 0,
        "strokeWidthMm": 0.25,
        "patternKind": "curve",
    },
    {
        "id": "plaster",
        "name": "Plaster",
        "paperMmRepeat": 8,
        "rotationDeg": 45,
        "strokeWidthMm": 0.13,
        "patternKind": "crosshatch",
    },
    {
        "id": "timber_grain",
        "name": "Timber",
        "paperMmRepeat": 12,
        "rotationDeg": 0,
        "strokeWidthMm": 0.18,
        "patternKind": "lines",
    },
    {
        "id": "gypsum",
        "name": "Gypsum",
        "paperMmRepeat": 4,
        "rotationDeg": 45,
        "strokeWidthMm": 0.10,
        "patternKind": "dots",
    },
    {
        "id": "stone",
        "name": "Stone",
        "paperMmRepeat": 60,
        "rotationDeg": 0,
        "strokeWidthMm": 0.18,
        "patternKind": "lines",
    },
]


def ensure_seed_hatches(doc: Document) -> Document:
    """CAN-V3-02: ensure the 7 canonical hatch patterns exist in the document.

    Idempotent — already-present hatches are skipped. Read-only built-ins.
    """
    existing_ids = {e.id for e in doc.elements.values() if isinstance(e, HatchPatternDefElem)}
    for row in _SEED_HATCHES:
        if row["id"] not in existing_ids:
            doc.elements[row["id"]] = HatchPatternDefElem.model_validate(row)
    return doc


def _wall_elevation_mm(els: dict[str, Element], level_id: str) -> float:
    lv = els.get(level_id)
    if isinstance(lv, LevelElem):
        return float(lv.elevation_mm)
    return 0.0


def _resolve_wall_height_mm(cmd: CreateWallCmd, els: dict[str, Element]) -> float:
    if cmd.base_constraint_level_id and cmd.top_constraint_level_id:
        b = _wall_elevation_mm(els, cmd.base_constraint_level_id) + cmd.base_constraint_offset_mm
        t = _wall_elevation_mm(els, cmd.top_constraint_level_id) + cmd.top_constraint_offset_mm
        return max(100.0, t - b)
    return cmd.height_mm


def _basis_line(val: str) -> WallBasisLine:
    choices: tuple[WallBasisLine, ...] = ("center", "face_interior", "face_exterior")
    lowered = val.strip().lower()
    if lowered in choices:
        return cast(WallBasisLine, lowered)
    return "center"


def _recompute_constrained_wall_heights(els: dict[str, Element]) -> None:
    for wid, el in list(els.items()):
        if not isinstance(el, WallElem):
            continue
        if not (el.base_constraint_level_id and el.top_constraint_level_id):
            continue
        b = _wall_elevation_mm(els, el.base_constraint_level_id) + el.base_constraint_offset_mm
        t = _wall_elevation_mm(els, el.top_constraint_level_id) + el.top_constraint_offset_mm
        nh = max(100.0, t - b)
        if abs(nh - el.height_mm) > 1e-3:
            els[wid] = el.model_copy(update={"height_mm": nh})


def _wall_thickness_from_type(
    els: dict[str, Element], wall_type_id: str | None, fallback: float
) -> float:
    if not wall_type_id:
        return fallback
    wt = els.get(wall_type_id)
    if not isinstance(wt, WallTypeElem) or not wt.layers:
        return fallback
    return float(sum(lyr.thickness_mm for lyr in wt.layers)) or fallback


def _validate_wall_stack(components: list, wall_height_mm: float) -> None:
    """Validate stacked-wall components: prefix Σ heightMm must be < wall heightMm."""
    if not components:
        raise ValueError("wall stack must have at least one component")
    prefix_sum = sum(c.height_mm for c in components[:-1])
    if prefix_sum >= wall_height_mm:
        raise ValueError(
            f"wall stack prefix Σ heightMm ({prefix_sum} mm) must be < "
            f"wall heightMm ({wall_height_mm} mm)"
        )


def _validate_wall_lean_taper(
    lean_mm: Vec2Mm | None,
    taper_ratio: float | None,
    wall_height_mm: float,
) -> None:
    if lean_mm is not None:
        magnitude = math.sqrt(lean_mm.x_mm**2 + lean_mm.y_mm**2)
        max_lean = wall_height_mm * math.tan(math.radians(60))
        if magnitude > max_lean:
            raise ValueError(
                f"leanMm magnitude ({magnitude:.1f} mm) exceeds "
                f"wall height × tan(60°) ({max_lean:.1f} mm)"
            )
    if taper_ratio is not None:
        if not (0.1 < taper_ratio < 10.0):
            raise ValueError(f"taperRatio ({taper_ratio}) must be in open interval (0.1, 10)")


def _floor_dims_from_type(
    els: dict[str, Element], floor_type_id: str | None
) -> tuple[float, float, float] | None:
    if not floor_type_id:
        return None
    ft = els.get(floor_type_id)
    if not isinstance(ft, FloorTypeElem) or not ft.layers:
        return None
    layers = ft.layers
    total = float(sum(lyr.thickness_mm for lyr in layers))
    structure = float(
        sum(lyr.thickness_mm for lyr in layers if lyr.layer_function in ("structure", "insulation"))
    )
    finish = float(sum(lyr.thickness_mm for lyr in layers if lyr.layer_function == "finish"))
    return (total, structure, finish)


def _propagate_wall_thickness_for_type(els: dict[str, Element], wall_type_id: str) -> None:
    wt = els.get(wall_type_id)
    if not isinstance(wt, WallTypeElem) or not wt.layers:
        return
    thick = float(sum(lyr.thickness_mm for lyr in wt.layers))
    for eid, el in list(els.items()):
        if isinstance(el, WallElem) and el.wall_type_id == wall_type_id:
            els[eid] = el.model_copy(update={"thickness_mm": thick})


def _propagate_floor_dims_for_type(els: dict[str, Element], floor_type_id: str) -> None:
    dims = _floor_dims_from_type(els, floor_type_id)
    if dims is None:
        return
    t_mm, s_mm, f_mm = dims
    for eid, el in list(els.items()):
        if isinstance(el, FloorElem) and el.floor_type_id == floor_type_id:
            els[eid] = el.model_copy(
                update={
                    "thickness_mm": t_mm,
                    "structure_thickness_mm": s_mm,
                    "finish_thickness_mm": f_mm,
                }
            )


def _canonical_room_scheme_rows(rows: list[RoomColorSchemeRow]) -> list[RoomColorSchemeRow]:
    keyed: dict[tuple[str, str], RoomColorSchemeRow] = {}
    for row in rows:
        prog = (row.programme_code or "").strip()
        dept = (row.department or "").strip()
        keyed[(prog.lower(), dept.lower())] = row
    out_keys = sorted(keyed.keys(), key=lambda x: (x[0], x[1]))
    return [keyed[k] for k in out_keys]


def _polygon_signed_area_xy_mm(pts: list[tuple[float, float]]) -> float:
    n = len(pts)
    if n < 3:
        return 0.0
    s = 0.0
    for i in range(n):
        x1, y1 = pts[i]
        x2, y2 = pts[(i + 1) % n]
        s += x1 * y2 - x2 * y1
    return 0.5 * s


def _site_boundary_turn_cross_products_xy_mm(pts: list[tuple[float, float]]) -> list[float]:
    """Cross of successive edge vectors at each vertex; strictly convex CCW ⇒ all > 0."""
    n = len(pts)
    out: list[float] = []
    for i in range(n):
        p0 = pts[(i - 1) % n]
        p1 = pts[i]
        p2 = pts[(i + 1) % n]
        ax, ay = p1[0] - p0[0], p1[1] - p0[1]
        bx, by = p2[0] - p1[0], p2[1] - p1[1]
        out.append(ax * by - ay * bx)
    return out


def _canonical_site_boundary_mm(raw: list[Vec2Mm]) -> list[Vec2Mm]:
    """Dedupe consecutive points, enforce CCW, rotate lexicographically smallest vertex first."""

    tuples = [(round(float(p.x_mm), 6), round(float(p.y_mm), 6)) for p in raw]
    cleaned: list[tuple[float, float]] = []
    for t in tuples:
        if cleaned and cleaned[-1] == t:
            continue
        cleaned.append(t)
    if len(cleaned) >= 2 and cleaned[0] == cleaned[-1]:
        cleaned.pop()
    if len(cleaned) < 3:
        raise ValueError("site.boundaryMm requires ≥3 distinct vertices")
    idx_min = min(range(len(cleaned)), key=lambda i: (cleaned[i][0], cleaned[i][1]))
    rotated = cleaned[idx_min:] + cleaned[:idx_min]
    area = _polygon_signed_area_xy_mm(rotated)
    if area < 0:
        rotated = list(reversed(rotated))
        idx_min = min(range(len(rotated)), key=lambda i: (rotated[i][0], rotated[i][1]))
        rotated = rotated[idx_min:] + rotated[:idx_min]
        area = _polygon_signed_area_xy_mm(rotated)
    if area <= 0:
        raise ValueError("site.boundaryMm must form a non-degenerate CCW polygon")
    crosses = _site_boundary_turn_cross_products_xy_mm(rotated)
    if not all(c > 1e-9 for c in crosses):
        raise ValueError(
            "site.boundaryMm must be strictly convex CCW (no collinear or concave vertices)"
        )
    return [Vec2Mm(xMm=a[0], yMm=a[1]) for a in rotated]


def _canonical_site_context_rows(rows: list[SiteContextObjectRow]) -> list[SiteContextObjectRow]:
    by_id = {r.id: r for r in rows}
    if len(by_id) != len(rows):
        raise ValueError("site.contextObjects must have unique ids")
    return [by_id[k] for k in sorted(by_id.keys())]


_PIN_BLOCKED_TARGETS: dict[type, str] = {
    MoveWallDeltaCmd: "wall_id",
    MoveWallEndpointsCmd: "wall_id",
    MoveGridLineEndpointsCmd: "grid_line_id",
    MoveLevelElevationCmd: "level_id",
    UpdateElementPropertyCmd: "element_id",
    DeleteElementCmd: "element_id",
    MoveAssetDeltaCmd: "element_id",
    MoveColumnDeltaCmd: "element_id",
    SetWallJoinDisallowCmd: "wall_id",
}


LINKED_ID_SEPARATOR = "::"


def _is_linked_id(value: Any) -> bool:
    return isinstance(value, str) and LINKED_ID_SEPARATOR in value


# Commands that mutate an existing element are blocked when their target id is
# a linked-element id (one carrying the ``<link_id>::<source_element_id>``
# prefix). FED-01 commands (createLinkModel etc.) are exempt — they target the
# host's link rows, not the source's elements. The list mirrors
# ``_PIN_BLOCKED_TARGETS`` plus a few more direct-id commands so renamed walls
# inside a link can't be moved either.
_LINKED_READONLY_SCALAR_FIELDS: dict[type, tuple[str, ...]] = {
    MoveWallDeltaCmd: ("wall_id",),
    MoveWallEndpointsCmd: ("wall_id",),
    MoveGridLineEndpointsCmd: ("grid_line_id",),
    MoveLevelElevationCmd: ("level_id",),
    UpdateElementPropertyCmd: ("element_id",),
    DeleteElementCmd: ("element_id",),
    PinElementCmd: ("element_id",),
    UnpinElementCmd: ("element_id",),
    SetCurtainPanelOverrideCmd: ("wall_id",),
    UpdateLinkModelCmd: (),
    DeleteLinkModelCmd: (),
    UpdateLinkDxfCmd: (),
    UpdateExternalLinkCmd: (),
    DeleteExternalLinkCmd: (),
    MoveAssetDeltaCmd: ("element_id",),
    MoveColumnDeltaCmd: ("element_id",),
}
_LINKED_READONLY_LIST_FIELDS: dict[type, tuple[str, ...]] = {
    DeleteElementsCmd: ("element_ids",),
    MirrorElementsCmd: ("element_ids",),
    RotateElementsCmd: ("element_ids",),
    MoveElementsDeltaCmd: ("element_ids",),
}


def _enforce_linked_readonly(cmd: Command) -> None:
    """FED-01: refuse mutating commands whose target id is a linked-element id.

    Linked element ids carry the ``<link_id>::<source_element_id>`` prefix; the
    source's elements live in a different model row and are read-only from the
    host's perspective.
    """

    scalars = _LINKED_READONLY_SCALAR_FIELDS.get(type(cmd), ())
    for attr in scalars:
        val = getattr(cmd, attr, None)
        if _is_linked_id(val):
            raise ValueError(
                f"linked_element_readonly: '{val}' is owned by a linked model and "
                "cannot be edited from the host — open the source model to edit"
            )
    lists = _LINKED_READONLY_LIST_FIELDS.get(type(cmd), ())
    for attr in lists:
        seq = getattr(cmd, attr, None)
        if not isinstance(seq, list):
            continue
        for v in seq:
            if _is_linked_id(v):
                raise ValueError(
                    f"linked_element_readonly: '{v}' is owned by a linked model and "
                    "cannot be edited from the host — open the source model to edit"
                )


def _enforce_pin_block(els: dict[str, Element], cmd: Command) -> None:
    """VIE-07: refuse mutating commands targeting a pinned element.

    Caller can opt out per call by setting `forcePinOverride=true`. Pin/unpin
    themselves are exempt (they always need to be runnable).
    """

    target_attr = _PIN_BLOCKED_TARGETS.get(type(cmd))
    if target_attr is None:
        return
    if getattr(cmd, "force_pin_override", False):
        return
    target_id = getattr(cmd, target_attr, None)
    if not isinstance(target_id, str):
        return
    target = els.get(target_id)
    if is_element_pinned(target):
        raise ValueError(
            f"pinned_element_blocked: '{target_id}' is pinned; "
            "set forcePinOverride=true or unpin first"
        )


def _validate_baluster_pattern(pattern: BalusterPattern) -> None:
    if pattern.rule == "regular" and (pattern.spacing_mm is None or pattern.spacing_mm <= 0):
        raise ValueError("balusterPattern.rule='regular' requires spacingMm > 0")


def _validate_handrail_supports(
    supports: list[HandrailSupport],
    els: dict,
) -> None:
    for i, support in enumerate(supports):
        if not support.bracket_family_id:
            raise ValueError(f"handrailSupports[{i}].bracketFamilyId must be non-empty")
        host = els.get(support.host_wall_id)
        if not isinstance(host, WallElem):
            raise ValueError(
                f"handrailSupports[{i}].hostWallId '{support.host_wall_id}' must reference a Wall"
            )


def compute_baluster_positions(
    path_length_mm: float,
    spacing_mm: float,
) -> list[float]:
    """Return t-values (offsets in mm from path start) for a 'regular' baluster pattern.

    First baluster at spacing_mm / 2; last at path_length_mm - spacing_mm / 2.
    Returns empty list if path_length_mm < spacing_mm or spacing_mm <= 0.
    """
    if path_length_mm < spacing_mm or spacing_mm <= 0:
        return []
    positions = []
    t = spacing_mm / 2.0
    while t <= path_length_mm - spacing_mm / 2.0:
        positions.append(t)
        t += spacing_mm
    return positions


def _no_source_provider(_uuid: str, _rev: int | None) -> None:
    """FED-02: default source provider used when no DB-backed resolver was
    threaded through (unit tests, intra-host operations). Returns ``None`` so
    cross-link operations gracefully fall back to host-only behaviour.
    """
    return None


def _validate_baluster_pattern(pattern: BalusterPattern) -> None:
    if pattern.rule == "regular" and (pattern.spacing_mm is None or pattern.spacing_mm <= 0):
        raise ValueError("balusterPattern.rule='regular' requires spacingMm > 0")


def _validate_handrail_supports(
    supports: list[HandrailSupport],
    els: dict,
) -> None:
    for i, support in enumerate(supports):
        if not support.bracket_family_id:
            raise ValueError(f"handrailSupports[{i}].bracketFamilyId must be non-empty")
        host = els.get(support.host_wall_id)
        if not isinstance(host, WallElem):
            raise ValueError(
                f"handrailSupports[{i}].hostWallId '{support.host_wall_id}' must reference a Wall"
            )
