"""Stable schedule column ordering + UI metadata hooks (WP-D01–D04).

Server keeps schedule rows keyed by camelCase identifiers; CSV and API consumers can follow
``columns`` order (registry first, then any extra keys sorted).
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

ColumnMeta = dict[str, Any]

# Preferred column order per derived category (stable field keys).
SCHEDULE_COLUMN_ORDER: dict[str, tuple[str, ...]] = {
    "room": (
        "elementId",
        "name",
        "levelId",
        "level",
        "areaM2",
        "perimeterM",
        "targetAreaM2",
        "areaDeltaM2",
        "programmeCode",
        "department",
        "programmeGroup",
        "isBoundaryOpen",
        "functionLabel",
        "finishSet",
        "finishState",
        "legendLabel",
        "levelPeerFinishSet",
        "peerSuggestedFinishSet",
        "familyTypeId",
    ),
    "finish": (
        "elementId",
        "name",
        "levelId",
        "level",
        "department",
        "programmeCode",
        "finishSet",
        "finishState",
        "legendLabel",
        "levelPeerFinishSet",
        "peerSuggestedFinishSet",
        "areaM2",
        "perimeterM",
        "familyTypeId",
    ),
    "door": (
        "elementId",
        "name",
        "wallId",
        "hostWallTypeId",
        "hostWallTypeDisplay",
        "hostWallTypeName",
        "levelId",
        "level",
        "widthMm",
        "hostHeightMm",
        "roughOpeningWidthMm",
        "roughOpeningHeightMm",
        "roughOpeningAreaM2",
        "familyTypeId",
        "familyTypeDisplay",
        "materialKey",
        "materialDisplay",
        "materialClass",
        "materialSurfacePattern",
        "materialCutPattern",
        "materialAppearanceStatus",
        "materialTextureScale",
        "materialDensityKgPerM3",
        "materialThermalConductivityWPerMK",
    ),
    "window": (
        "elementId",
        "name",
        "wallId",
        "hostWallTypeId",
        "hostWallTypeDisplay",
        "hostWallTypeName",
        "levelId",
        "level",
        "widthMm",
        "heightMm",
        "sillMm",
        "roughOpeningWidthMm",
        "roughOpeningHeightMm",
        "roughOpeningAreaM2",
        "openingAreaM2",
        "aspectRatio",
        "headHeightMm",
        "familyTypeId",
        "familyTypeDisplay",
        "materialKey",
        "materialDisplay",
        "materialClass",
        "materialSurfacePattern",
        "materialCutPattern",
        "materialAppearanceStatus",
        "materialTextureScale",
        "materialDensityKgPerM3",
        "materialThermalConductivityWPerMK",
    ),
    "floor": (
        "elementId",
        "name",
        "levelId",
        "level",
        "floorTypeId",
        "typeName",
        "thicknessMm",
        "materialAssemblyLayers",
        "materialKey",
        "materialDisplay",
        "effectiveMaterialSource",
        "materialClass",
        "materialSurfacePattern",
        "materialCutPattern",
        "materialAppearanceStatus",
        "materialTextureScale",
        "materialDensityKgPerM3",
        "materialThermalConductivityWPerMK",
        "totalThicknessMm",
        "areaM2",
        "perimeterM",
        "familyTypeId",
    ),
    "roof": (
        "elementId",
        "name",
        "referenceLevelId",
        "referenceLevel",
        "roofTypeId",
        "typeName",
        "assemblyTotalThicknessMm",
        "materialAssemblyLayers",
        "materialKey",
        "materialDisplay",
        "effectiveMaterialSource",
        "materialClass",
        "materialSurfacePattern",
        "materialCutPattern",
        "materialAppearanceStatus",
        "materialTextureScale",
        "materialDensityKgPerM3",
        "materialThermalConductivityWPerMK",
        "overhangMm",
        "slopeDeg",
        "pitchDeg",
        "footprintAreaM2",
        "footprintPerimeterM",
        "familyTypeId",
    ),
    "stair": (
        "elementId",
        "name",
        "baseLevelId",
        "topLevelId",
        "baseLevel",
        "topLevel",
        "riseMm",
        "runMm",
        "widthMm",
        "riserCount",
        "treadCount",
        "riserHeightMm",
        "treadDepthMm",
        "totalRiseMm",
        "totalRunMm",
        "landingCount",
        "landingFootprintBoundsMm",
        "guardrailPlaceholderSideTokens",
        "stairPlanSectionDocumentationLabel",
        "stairQuantityDerivationStatus",
        "baseLevelResolves",
        "topLevelResolves",
        "stairScheduleCorrelationToken",
        "familyTypeId",
    ),
    "sheet": (
        "elementId",
        "name",
        "titleBlock",
        "viewportCount",
        "planViewNames",
        "familyTypeId",
    ),
    "plan_view": (
        "elementId",
        "name",
        "levelId",
        "level",
        "planPresentation",
        "discipline",
        "viewSubdiscipline",
        "planViewSubtype",
        "areaScheme",
        "sheetId",
        "sheetName",
        "familyTypeId",
    ),
    "planview": (
        "elementId",
        "name",
        "levelId",
        "level",
        "planPresentation",
        "discipline",
        "viewSubdiscipline",
        "planViewSubtype",
        "areaScheme",
        "sheetId",
        "sheetName",
        "familyTypeId",
    ),
    "view": (
        "elementId",
        "name",
        "viewKind",
        "viewType",
        "levelId",
        "level",
        "discipline",
        "viewTemplateId",
        "defaultLens",
        "cropEnabled",
        "cropDepthMm",
        "scale",
        "sheetId",
        "sheetName",
        "familyTypeId",
    ),
    "section_cut": ("elementId", "name", "cropDepthMm", "familyTypeId"),
    "sectioncut": ("elementId", "name", "cropDepthMm", "familyTypeId"),
    "material_assembly": (
        "elementId",
        "name",
        "hostElementId",
        "hostKind",
        "assemblyTypeId",
        "catalogAuditStatus",
        "assemblyMaterialKeysDigest",
        "layerPropagationStatus",
        "assemblyTotalThicknessMm",
        "layerOffsetFromExteriorMm",
        "layerIndex",
        "layerFunction",
        "materialKey",
        "materialDisplay",
        "materialClass",
        "materialSurfacePattern",
        "materialCutPattern",
        "materialAppearanceStatus",
        "materialTextureScale",
        "materialDensityKgPerM3",
        "materialThermalConductivityWPerMK",
        "thicknessMm",
        "grossAreaM2",
        "grossVolumeM3",
        "levelId",
        "level",
        "familyTypeId",
    ),
    "quantity_takeoff": (
        "elementId",
        "name",
        "elementKind",
        "typeId",
        "levelId",
        "level",
        "scenarioId",
        "costGroup",
        "workPackage",
        "trade",
        "unit",
        "lengthM",
        "areaM2",
        "grossAreaM2",
        "netAreaM2",
        "grossOpeningAreaM2",
        "netOpeningAreaM2",
        "openingCount",
        "grossVolumeM3",
        "netVolumeM3",
        "count",
        "layerQuantityCount",
        "quantityDerivation",
        "traceability",
    ),
    "cost_estimate": (
        "rowId",
        "elementId",
        "name",
        "elementKind",
        "typeId",
        "scenarioId",
        "costGroup",
        "workPackage",
        "trade",
        "unit",
        "quantity",
        "unitRate",
        "currency",
        "totalCost",
        "costSource",
        "estimateConfidence",
        "costDataStatus",
        "traceability",
    ),
    "element_cost_group": (
        "rowId",
        "elementId",
        "name",
        "elementKind",
        "typeId",
        "level",
        "scenarioId",
        "costGroup",
        "workPackage",
        "trade",
        "unit",
        "quantity",
        "unitRate",
        "currency",
        "totalCost",
        "costSource",
        "costDataStatus",
        "traceability",
    ),
    "scenario_delta": (
        "elementId",
        "scenarioId",
        "baselineScenarioId",
        "costGroup",
        "workPackage",
        "trade",
        "scenarioCost",
        "baselineCost",
        "deltaCost",
        "rowCount",
        "sourceElementIds",
        "traceability",
    ),
    "fire_compartment": (
        "elementId",
        "compartmentId",
        "name",
        "level",
        "roomCount",
        "roomNames",
        "areaM2",
        "volumeM3",
        "fireResistanceRequirement",
        "smokeCompartmentIds",
        "boundaryClosureStatus",
        "areaCheckStatus",
        "volumeCheckStatus",
        "reviewStatus",
    ),
    "rated_element": (
        "elementId",
        "name",
        "category",
        "levelId",
        "level",
        "hostElementId",
        "fireRating",
        "smokeControlRating",
        "selfClosingRequired",
        "shaftEnclosureRating",
        "penetrationFirestopStatus",
        "reviewStatus",
    ),
    "fire_door": (
        "elementId",
        "name",
        "category",
        "levelId",
        "level",
        "hostElementId",
        "fireRating",
        "smokeControlRating",
        "selfClosingRequired",
        "reviewStatus",
    ),
    "escape_route": (
        "elementId",
        "routeId",
        "name",
        "category",
        "levelId",
        "level",
        "travelDistanceM",
        "exitWidthMm",
        "doorSwingCompliant",
        "stairClassification",
        "corridorClassification",
        "assemblyPointNote",
        "reviewStatus",
    ),
    "firestop_penetration": (
        "elementId",
        "name",
        "category",
        "hostElementId",
        "ratedAssemblyId",
        "firestopStatus",
        "approvalStatus",
        "responsibleTrade",
        "inspectionEvidence",
    ),
    "smoke_control_equipment": (
        "elementId",
        "name",
        "category",
        "equipmentType",
        "systemId",
        "controlZone",
        "smokeControlRating",
        "status",
        "inspectionEvidence",
    ),
    "energy_envelope": (
        "elementId",
        "name",
        "hostKind",
        "typeId",
        "typeName",
        "levelId",
        "level",
        "wallId",
        "thermalClassification",
        "classificationSource",
        "surfaceAreaM2",
        "uValueWPerM2K",
        "gValue",
        "frameFraction",
        "annualShadingFactorEstimate",
        "missingMaterialKeys",
        "sourceReferences",
        "scenarioId",
        "familyTypeId",
    ),
    "energy_thermal_materials": (
        "elementId",
        "materialKey",
        "materialDisplay",
        "lambdaWPerMK",
        "rhoKgPerM3",
        "specificHeatJPerKgK",
        "mu",
        "sourceReference",
        "thermalDataStatus",
        "familyTypeId",
    ),
    "energy_u_value_summary": (
        "elementId",
        "typeId",
        "typeName",
        "hostKind",
        "uValueWPerM2K",
        "rTotalM2KPerW",
        "layerCount",
        "missingMaterialKeys",
        "sourceReferences",
        "calculationScope",
        "familyTypeId",
    ),
    "energy_windows_solar_gains": (
        "elementId",
        "name",
        "wallId",
        "hostWallTypeId",
        "widthMm",
        "heightMm",
        "openingAreaM2",
        "uValueWPerM2K",
        "gValue",
        "frameFraction",
        "shadingDevice",
        "annualShadingFactorEstimate",
        "installationThermalBridgeNote",
        "familyTypeId",
    ),
    "energy_thermal_bridges": (
        "elementId",
        "name",
        "markerType",
        "hostElementIds",
        "description",
        "suggestedMitigation",
        "handoffNote",
        "psiValueReference",
        "familyTypeId",
    ),
    "energy_thermal_zones": (
        "elementId",
        "name",
        "levelId",
        "level",
        "heatingStatus",
        "usageProfile",
        "setpointC",
        "airChangeRate",
        "zoneId",
        "conditionedVolumeIncluded",
        "familyTypeId",
    ),
    "energy_building_services": (
        "elementId",
        "name",
        "scenarioId",
        "heatingGeneratorType",
        "energyCarrier",
        "distributionType",
        "domesticHotWaterSystem",
        "ventilationSystem",
        "renewableEnergyNotes",
        "knownSystemAge",
        "measureCandidateNotes",
        "handoffNote",
        "familyTypeId",
    ),
    "energy_renovation_measures": (
        "elementId",
        "scenarioId",
        "scenarioName",
        "scenarioStatus",
        "measureId",
        "measureName",
        "measureNotes",
        "costPlaceholder",
        "systemsNotes",
        "familyTypeId",
    ),
    "energy_export_qa": (
        "elementId",
        "issueCode",
        "severity",
        "message",
        "missingMaterialKeys",
        "familyTypeId",
    ),
    "construction_package": (
        "elementId",
        "name",
        "code",
        "phaseId",
        "plannedStart",
        "plannedEnd",
        "actualStart",
        "actualEnd",
        "responsibleCompany",
        "dependencies",
    ),
    "phase": (
        "elementId",
        "name",
        "ord",
        "createdCount",
        "demolishedCount",
        "packageCount",
    ),
    "progress": (
        "elementId",
        "name",
        "kind",
        "phaseCreated",
        "phaseDemolished",
        "constructionPackageId",
        "plannedStart",
        "plannedEnd",
        "actualStart",
        "actualEnd",
        "installationSequence",
        "dependencies",
        "progressStatus",
        "responsibleCompany",
        "evidenceCount",
        "issueCount",
        "punchItemCount",
        "checklistItemCount",
    ),
    "punch": (
        "elementId",
        "title",
        "status",
        "elementIds",
        "viewpointId",
        "evidenceCount",
        "issueKind",
    ),
    "site_logistics": (
        "elementId",
        "name",
        "logisticsKind",
        "phaseId",
        "constructionPackageId",
        "plannedStart",
        "plannedEnd",
        "actualStart",
        "actualEnd",
        "progressStatus",
        "responsibleCompany",
        "boundaryPointCount",
        "pathPointCount",
        "evidenceCount",
        "issueCount",
    ),
    "qa_checklist": (
        "elementId",
        "name",
        "targetElementIds",
        "constructionPackageId",
        "phaseId",
        "responsibleCompany",
        "progressStatus",
        "checklistItemCount",
        "passedCount",
        "failedCount",
        "openCount",
        "evidenceCount",
        "issueCount",
    ),
    "structural_element": (
        "elementId",
        "name",
        "category",
        "levelId",
        "level",
        "loadBearing",
        "structuralRole",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
        "discipline",
    ),
    "structural_wall": (
        "elementId",
        "name",
        "wallTypeId",
        "levelId",
        "level",
        "heightMm",
        "loadBearing",
        "structuralRole",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
    ),
    "column": (
        "elementId",
        "name",
        "levelId",
        "level",
        "bMm",
        "hMm",
        "heightMm",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
    ),
    "beam": (
        "elementId",
        "name",
        "levelId",
        "level",
        "widthMm",
        "heightMm",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
    ),
    "foundation": (
        "elementId",
        "name",
        "category",
        "levelId",
        "level",
        "structuralRole",
        "structuralMaterial",
        "analysisStatus",
    ),
    "opening_load_bearing_wall": (
        "elementId",
        "name",
        "category",
        "wallId",
        "wallName",
        "levelId",
        "level",
        "openingWidthMm",
        "hostLoadBearing",
        "reviewStatus",
    ),
    "structural_elements": (
        "elementId",
        "name",
        "category",
        "levelId",
        "level",
        "loadBearing",
        "structuralRole",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
        "discipline",
    ),
    "structure": (
        "elementId",
        "name",
        "category",
        "levelId",
        "level",
        "loadBearing",
        "structuralRole",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
        "discipline",
    ),
    "structural_walls": (
        "elementId",
        "name",
        "wallTypeId",
        "levelId",
        "level",
        "heightMm",
        "loadBearing",
        "structuralRole",
        "structuralMaterial",
        "analysisStatus",
        "fireResistanceRating",
    ),
    "opening_in_load_bearing_wall": (
        "elementId",
        "name",
        "category",
        "wallId",
        "wallName",
        "levelId",
        "level",
        "openingWidthMm",
        "hostLoadBearing",
        "reviewStatus",
    ),
}

_STRUCTURE_FIELD_METADATA: dict[str, ColumnMeta] = {
    "elementId": {"label": "Element Id", "role": "id"},
    "name": {"label": "Name", "role": "text"},
    "category": {"label": "Category", "role": "text"},
    "levelId": {"label": "Level id", "role": "identity"},
    "level": {"label": "Level", "role": "text"},
    "wallTypeId": {"label": "Wall type", "role": "identity"},
    "floorTypeId": {"label": "Floor type", "role": "identity"},
    "roofTypeId": {"label": "Roof type", "role": "identity"},
    "loadBearing": {"label": "Load bearing", "role": "text"},
    "structuralRole": {"label": "Structural role", "role": "text"},
    "structuralMaterial": {"label": "Structural material", "role": "text"},
    "analysisStatus": {"label": "Analysis status", "role": "text"},
    "fireResistanceRating": {"label": "Fire rating", "role": "text"},
    "discipline": {"label": "Discipline", "role": "text"},
    "heightMm": {"label": "Height (mm)", "role": "number"},
    "widthMm": {"label": "Width (mm)", "role": "number"},
    "thicknessMm": {"label": "Thickness (mm)", "role": "number"},
    "bMm": {"label": "b (mm)", "role": "number"},
    "hMm": {"label": "h (mm)", "role": "number"},
    "wallId": {"label": "Host wall", "role": "identity"},
    "wallName": {"label": "Host wall name", "role": "text"},
    "openingWidthMm": {"label": "Opening width (mm)", "role": "number"},
    "hostLoadBearing": {"label": "Host load bearing", "role": "text"},
    "reviewStatus": {"label": "Review status", "role": "text"},
}

SCHEDULE_COLUMN_METADATA: dict[str, dict[str, ColumnMeta]] = {
    "room": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "areaM2": {"label": "Area (m²)", "role": "number"},
        "perimeterM": {"label": "Perimeter (m)", "role": "number"},
        "targetAreaM2": {"label": "Target area (m²)", "role": "number"},
        "areaDeltaM2": {"label": "Area vs target (m²)", "role": "number"},
        "programmeCode": {"label": "Programme", "role": "text"},
        "department": {"label": "Department", "role": "text"},
        "functionLabel": {"label": "Function", "role": "text"},
        "finishSet": {"label": "Finish set", "role": "text"},
        "finishState": {
            "label": "Finish metadata state",
            "role": "text",
            "help": "complete, not_required, missing, or peer_suggested (aligned with advisor).",
        },
        "legendLabel": {
            "label": "Legend label",
            "role": "text",
            "help": "Key aligned with plan room colour legend (programme/dept precedence).",
        },
        "levelPeerFinishSet": {
            "label": "Level peer finish",
            "role": "text",
            "help": "First non-empty finish on level (sorted room ids); correlation only.",
        },
        "peerSuggestedFinishSet": {
            "label": "Peer-suggested finish",
            "role": "text",
            "help": "Set when finishState is peer_suggested (matches quick-fix source).",
        },
    },
    "finish": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Room", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "department": {"label": "Department", "role": "text"},
        "programmeCode": {"label": "Programme", "role": "text"},
        "finishSet": {"label": "Finish set", "role": "text"},
        "finishState": {
            "label": "Finish metadata state",
            "role": "text",
            "help": "complete, not_required, missing, or peer_suggested (aligned with advisor).",
        },
        "legendLabel": {"label": "Legend label", "role": "text"},
        "levelPeerFinishSet": {"label": "Level peer finish", "role": "text"},
        "peerSuggestedFinishSet": {"label": "Peer-suggested finish", "role": "text"},
        "areaM2": {"label": "Area (m²)", "role": "number"},
        "perimeterM": {"label": "Perimeter (m)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "door": {
        "hostWallTypeId": {"label": "Host wall type", "role": "identity"},
        "hostWallTypeDisplay": {"label": "Host wall type name", "role": "text"},
        "hostWallTypeName": {"label": "Host wall type name (resolved)", "role": "text"},
        "widthMm": {"label": "Width (mm)", "role": "integer"},
        "hostHeightMm": {"label": "Host height (mm)", "role": "integer"},
        "roughOpeningWidthMm": {"label": "Rough opening width (mm)", "role": "integer"},
        "roughOpeningHeightMm": {"label": "Rough opening height (mm)", "role": "integer"},
        "roughOpeningAreaM2": {"label": "Rough opening (m²)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
        "familyTypeDisplay": {"label": "Type name", "role": "text"},
        "materialKey": {"label": "Finish / material", "role": "text"},
        "materialDisplay": {"label": "Material (catalog)", "role": "text"},
        "materialClass": {"label": "Material class", "role": "text"},
        "materialSurfacePattern": {"label": "Surface pattern", "role": "text"},
        "materialCutPattern": {"label": "Cut pattern", "role": "text"},
        "materialAppearanceStatus": {"label": "Appearance status", "role": "text"},
        "materialTextureScale": {"label": "Texture scale", "role": "text"},
        "materialDensityKgPerM3": {"label": "Density kg/m³", "role": "number"},
        "materialThermalConductivityWPerMK": {"label": "Conductivity W/mK", "role": "number"},
    },
    "window": {
        "hostWallTypeId": {"label": "Host wall type", "role": "identity"},
        "hostWallTypeDisplay": {"label": "Host wall type name", "role": "text"},
        "hostWallTypeName": {"label": "Host wall type name (resolved)", "role": "text"},
        "widthMm": {"label": "Width (mm)", "role": "integer"},
        "heightMm": {"label": "Height (mm)", "role": "integer"},
        "sillMm": {"label": "Sill (mm)", "role": "integer"},
        "roughOpeningWidthMm": {"label": "Rough opening width (mm)", "role": "integer"},
        "roughOpeningHeightMm": {"label": "Rough opening height (mm)", "role": "integer"},
        "roughOpeningAreaM2": {
            "label": "Rough opening (m²)",
            "role": "number",
            "help": "Wall opening area using width plus interior reveal (when set), times sash height.",
        },
        "openingAreaM2": {"label": "Glazing area (m²)", "role": "number"},
        "aspectRatio": {"label": "Aspect ratio (W/H)", "role": "number"},
        "headHeightMm": {"label": "Head height (mm)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
        "familyTypeDisplay": {"label": "Type name", "role": "text"},
        "materialKey": {"label": "Finish / material", "role": "text"},
        "materialDisplay": {"label": "Material (catalog)", "role": "text"},
        "materialClass": {"label": "Material class", "role": "text"},
        "materialSurfacePattern": {"label": "Surface pattern", "role": "text"},
        "materialCutPattern": {"label": "Cut pattern", "role": "text"},
        "materialAppearanceStatus": {"label": "Appearance status", "role": "text"},
        "materialTextureScale": {"label": "Texture scale", "role": "text"},
        "materialDensityKgPerM3": {"label": "Density kg/m³", "role": "number"},
        "materialThermalConductivityWPerMK": {"label": "Conductivity W/mK", "role": "number"},
    },
    "floor": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "floorTypeId": {"label": "Floor type", "role": "identity"},
        "typeName": {"label": "Type name", "role": "text"},
        "thicknessMm": {"label": "Thickness (mm)", "role": "number"},
        "materialAssemblyLayers": {"label": "Assembly layers", "role": "integer"},
        "materialKey": {"label": "Top material key", "role": "text"},
        "materialDisplay": {"label": "Top material", "role": "text"},
        "effectiveMaterialSource": {"label": "Material source", "role": "text"},
        "materialClass": {"label": "Material class", "role": "text"},
        "materialSurfacePattern": {"label": "Surface pattern", "role": "text"},
        "materialCutPattern": {"label": "Cut pattern", "role": "text"},
        "materialAppearanceStatus": {"label": "Appearance status", "role": "text"},
        "materialTextureScale": {"label": "Texture scale", "role": "text"},
        "materialDensityKgPerM3": {"label": "Density kg/m³", "role": "number"},
        "materialThermalConductivityWPerMK": {"label": "Conductivity W/mK", "role": "number"},
        "totalThicknessMm": {"label": "Assembly thickness (mm)", "role": "number"},
        "areaM2": {"label": "Area (m²)", "role": "number"},
        "perimeterM": {"label": "Perimeter (m)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "roof": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "referenceLevel": {"label": "Ref. level", "role": "text"},
        "roofTypeId": {"label": "Roof type", "role": "identity"},
        "typeName": {"label": "Type name", "role": "text"},
        "assemblyTotalThicknessMm": {"label": "Assembly thickness (mm)", "role": "number"},
        "materialAssemblyLayers": {"label": "Assembly layers", "role": "integer"},
        "materialKey": {"label": "Top material key", "role": "text"},
        "materialDisplay": {"label": "Top material", "role": "text"},
        "effectiveMaterialSource": {"label": "Material source", "role": "text"},
        "materialClass": {"label": "Material class", "role": "text"},
        "materialSurfacePattern": {"label": "Surface pattern", "role": "text"},
        "materialCutPattern": {"label": "Cut pattern", "role": "text"},
        "materialAppearanceStatus": {"label": "Appearance status", "role": "text"},
        "materialTextureScale": {"label": "Texture scale", "role": "text"},
        "materialDensityKgPerM3": {"label": "Density kg/m³", "role": "number"},
        "materialThermalConductivityWPerMK": {"label": "Conductivity W/mK", "role": "number"},
        "overhangMm": {"label": "Overhang (mm)", "role": "number"},
        "slopeDeg": {"label": "Slope (°)", "role": "number"},
        "pitchDeg": {
            "label": "Pitch (°)",
            "role": "number",
            "help": "Architectural pitch in degrees; mirrors slopeDeg for parity.",
        },
        "footprintAreaM2": {"label": "Footprint (m²)", "role": "number"},
        "footprintPerimeterM": {"label": "Footprint perimeter (m)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "stair": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "baseLevel": {"label": "Base level", "role": "text"},
        "topLevel": {"label": "Top level", "role": "text"},
        "riseMm": {"label": "Rise (mm)", "role": "number"},
        "runMm": {"label": "Run (mm)", "role": "number"},
        "widthMm": {"label": "Width (mm)", "role": "number"},
        "riserCount": {"label": "Risers (readback)", "role": "integer"},
        "treadCount": {"label": "Treads (readback)", "role": "integer"},
        "riserHeightMm": {"label": "Riser height (mm)", "role": "number"},
        "treadDepthMm": {"label": "Tread depth (mm)", "role": "number"},
        "totalRiseMm": {
            "label": "Total rise (mm)",
            "role": "number",
            "help": "Story height when base/top levels resolve; omitted when unavailable.",
        },
        "totalRunMm": {
            "label": "Total run (mm)",
            "role": "number",
            "help": "Modeled run length when non-degenerate.",
        },
        "landingCount": {"label": "Landings (doc proxy)", "role": "integer"},
        "landingFootprintBoundsMm": {
            "label": "Landing footprint bounds",
            "role": "text",
            "help": "Axis-aligned bounds for combined straight-run landing placeholder hull.",
        },
        "guardrailPlaceholderSideTokens": {
            "label": "Guardrail placeholder sides",
            "role": "text",
            "help": "Deterministic side tokens mirrored from documentation placeholders.",
        },
        "stairPlanSectionDocumentationLabel": {
            "label": "Stair doc label",
            "role": "text",
        },
        "stairQuantityDerivationStatus": {
            "label": "Quantity derivation",
            "role": "text",
            "help": "Closed-set readback quality for schedule quantities and guardrail fields.",
        },
        "baseLevelResolves": {"label": "Base level resolves", "role": "text"},
        "topLevelResolves": {"label": "Top level resolves", "role": "text"},
        "stairScheduleCorrelationToken": {
            "label": "Schedule correlation token",
            "role": "identity",
            "help": "Stable token shared with plan, section, and manifest stair evidence.",
        },
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "sheet": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "titleBlock": {"label": "Title block", "role": "text"},
        "viewportCount": {"label": "Viewports", "role": "integer"},
        "planViewNames": {"label": "Plan views", "role": "text"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "plan_view": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "planPresentation": {"label": "Presentation", "role": "text"},
        "discipline": {"label": "Discipline", "role": "text"},
        "viewSubdiscipline": {"label": "Sub-discipline", "role": "text"},
        "planViewSubtype": {"label": "View type", "role": "text"},
        "areaScheme": {"label": "Area scheme", "role": "text"},
        "sheetId": {"label": "Sheet id", "role": "identity"},
        "sheetName": {"label": "Sheet name", "role": "text"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "planview": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "planPresentation": {"label": "Presentation", "role": "text"},
        "discipline": {"label": "Discipline", "role": "text"},
        "viewSubdiscipline": {"label": "Sub-discipline", "role": "text"},
        "planViewSubtype": {"label": "View type", "role": "text"},
        "areaScheme": {"label": "Area scheme", "role": "text"},
        "sheetId": {"label": "Sheet id", "role": "identity"},
        "sheetName": {"label": "Sheet name", "role": "text"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "view": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "View name", "role": "text"},
        "viewKind": {"label": "View kind", "role": "text"},
        "viewType": {"label": "View type", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "discipline": {"label": "Discipline", "role": "text"},
        "viewTemplateId": {"label": "View template", "role": "identity"},
        "defaultLens": {"label": "Default lens", "role": "text"},
        "cropEnabled": {"label": "Crop enabled", "role": "text"},
        "cropDepthMm": {"label": "Crop depth (mm)", "role": "number"},
        "scale": {"label": "Scale", "role": "text"},
        "sheetId": {"label": "Sheet id", "role": "identity"},
        "sheetName": {"label": "Sheet name", "role": "text"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "section_cut": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "cropDepthMm": {"label": "Crop depth (mm)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "sectioncut": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "cropDepthMm": {"label": "Crop depth (mm)", "role": "number"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "material_assembly": {
        "elementId": {"label": "Assembly row id", "role": "id"},
        "hostElementId": {"label": "Host element", "role": "identity"},
        "hostKind": {"label": "Host kind", "role": "text"},
        "assemblyTypeId": {"label": "Assembly type", "role": "identity"},
        "catalogAuditStatus": {
            "label": "Catalog audit",
            "role": "text",
            "help": "Per-host classifier from material_catalog_audit_evidence_v0 (repeated on each layer row).",
        },
        "assemblyMaterialKeysDigest": {
            "label": "Assembly material keys digest",
            "role": "identity",
            "help": "SHA-256 hex of ordered layer material keys for evidence correlation.",
        },
        "layerPropagationStatus": {
            "label": "Layer propagation",
            "role": "text",
            "help": "Mirrors catalog audit vocabulary (clean vs mismatch/stale/etc.).",
        },
        "assemblyTotalThicknessMm": {"label": "Assembly thickness (mm)", "role": "number"},
        "layerOffsetFromExteriorMm": {"label": "Layer offset from exterior (mm)", "role": "number"},
        "layerIndex": {"label": "Layer", "role": "integer"},
        "layerFunction": {"label": "Layer function", "role": "text"},
        "materialKey": {"label": "Material key", "role": "text"},
        "materialDisplay": {"label": "Material", "role": "text"},
        "materialClass": {"label": "Material class", "role": "text"},
        "materialSurfacePattern": {"label": "Surface pattern", "role": "text"},
        "materialCutPattern": {"label": "Cut pattern", "role": "text"},
        "materialAppearanceStatus": {"label": "Appearance status", "role": "text"},
        "materialTextureScale": {"label": "Texture scale", "role": "text"},
        "materialDensityKgPerM3": {"label": "Density kg/m³", "role": "number"},
        "materialThermalConductivityWPerMK": {"label": "Conductivity W/mK", "role": "number"},
        "thicknessMm": {"label": "Thickness (mm)", "role": "number"},
        "grossAreaM2": {"label": "Gross area (m²)", "role": "number"},
        "grossVolumeM3": {"label": "Gross volume (m³)", "role": "number"},
        "level": {"label": "Level", "role": "text"},
        "familyTypeId": {"label": "Family / type", "role": "identity"},
    },
    "quantity_takeoff": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "elementKind": {"label": "Element kind", "role": "text"},
        "typeId": {"label": "Type Id", "role": "identity"},
        "level": {"label": "Level", "role": "text"},
        "scenarioId": {"label": "Scenario", "role": "identity"},
        "costGroup": {"label": "Cost group", "role": "text"},
        "workPackage": {"label": "Work package", "role": "text"},
        "trade": {"label": "Trade", "role": "text"},
        "unit": {"label": "Cost unit", "role": "text"},
        "lengthM": {"label": "Length (m)", "role": "number"},
        "areaM2": {"label": "Area (m²)", "role": "number"},
        "grossAreaM2": {"label": "Gross area (m²)", "role": "number"},
        "netAreaM2": {"label": "Net area (m²)", "role": "number"},
        "grossOpeningAreaM2": {"label": "Gross openings (m²)", "role": "number"},
        "netOpeningAreaM2": {"label": "Net openings (m²)", "role": "number"},
        "openingCount": {"label": "Openings", "role": "integer"},
        "grossVolumeM3": {"label": "Gross volume (m³)", "role": "number"},
        "netVolumeM3": {"label": "Net volume (m³)", "role": "number"},
        "count": {"label": "Count", "role": "integer"},
        "layerQuantityCount": {"label": "Layers", "role": "integer"},
        "quantityDerivation": {"label": "Quantity derivation", "role": "text"},
        "traceability": {"label": "Traceability", "role": "text"},
    },
    "cost_estimate": {
        "rowId": {"label": "Cost row", "role": "id"},
        "elementId": {"label": "Element Id", "role": "identity"},
        "name": {"label": "Name", "role": "text"},
        "elementKind": {"label": "Element kind", "role": "text"},
        "typeId": {"label": "Type Id", "role": "identity"},
        "scenarioId": {"label": "Scenario", "role": "identity"},
        "costGroup": {"label": "Cost group", "role": "text"},
        "workPackage": {"label": "Work package", "role": "text"},
        "trade": {"label": "Trade", "role": "text"},
        "unit": {"label": "Unit", "role": "text"},
        "quantity": {"label": "Quantity", "role": "number"},
        "unitRate": {"label": "Unit rate", "role": "number"},
        "currency": {"label": "Currency", "role": "text"},
        "totalCost": {"label": "Total cost", "role": "number"},
        "costSource": {"label": "Source/reference", "role": "text"},
        "estimateConfidence": {"label": "Confidence", "role": "number"},
        "costDataStatus": {
            "label": "Cost data status",
            "role": "status",
            "help": "Unit rates without source references are retained but not totaled.",
        },
        "traceability": {"label": "Traceability", "role": "text"},
    },
    "element_cost_group": {
        "rowId": {"label": "Cost row", "role": "id"},
        "elementId": {"label": "Element Id", "role": "identity"},
        "name": {"label": "Name", "role": "text"},
        "elementKind": {"label": "Element kind", "role": "text"},
        "typeId": {"label": "Type Id", "role": "identity"},
        "level": {"label": "Level", "role": "text"},
        "scenarioId": {"label": "Scenario", "role": "identity"},
        "costGroup": {"label": "Cost group", "role": "text"},
        "workPackage": {"label": "Work package", "role": "text"},
        "trade": {"label": "Trade", "role": "text"},
        "unit": {"label": "Unit", "role": "text"},
        "quantity": {"label": "Quantity", "role": "number"},
        "unitRate": {"label": "Unit rate", "role": "number"},
        "currency": {"label": "Currency", "role": "text"},
        "totalCost": {"label": "Total cost", "role": "number"},
        "costSource": {"label": "Source/reference", "role": "text"},
        "costDataStatus": {"label": "Cost data status", "role": "status"},
        "traceability": {"label": "Traceability", "role": "text"},
    },
    "scenario_delta": {
        "elementId": {"label": "Delta row", "role": "id"},
        "scenarioId": {"label": "Scenario", "role": "identity"},
        "baselineScenarioId": {"label": "Baseline scenario", "role": "identity"},
        "costGroup": {"label": "Cost group", "role": "text"},
        "workPackage": {"label": "Work package", "role": "text"},
        "trade": {"label": "Trade", "role": "text"},
        "scenarioCost": {"label": "Scenario cost", "role": "number"},
        "baselineCost": {"label": "Baseline cost", "role": "number"},
        "deltaCost": {"label": "Delta cost", "role": "number"},
        "rowCount": {"label": "Rows", "role": "integer"},
        "sourceElementIds": {"label": "Source elements", "role": "identity"},
        "traceability": {"label": "Traceability", "role": "text"},
    },
    "fire_compartment": {
        "elementId": {"label": "Element Id", "role": "id"},
        "compartmentId": {"label": "Compartment", "role": "identity"},
        "name": {"label": "Name", "role": "text"},
        "level": {"label": "Level", "role": "text"},
        "roomCount": {"label": "Rooms", "role": "integer"},
        "roomNames": {"label": "Room names", "role": "text"},
        "areaM2": {"label": "Area (m2)", "role": "number"},
        "volumeM3": {"label": "Volume (m3)", "role": "number"},
        "fireResistanceRequirement": {"label": "Fire-resistance requirement", "role": "text"},
        "smokeCompartmentIds": {"label": "Smoke compartments", "role": "text"},
        "boundaryClosureStatus": {"label": "Boundary closure", "role": "status"},
        "areaCheckStatus": {"label": "Area check", "role": "status"},
        "volumeCheckStatus": {"label": "Volume check", "role": "status"},
        "reviewStatus": {"label": "Review status", "role": "status"},
    },
    "rated_element": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "category": {"label": "Category", "role": "text"},
        "levelId": {"label": "Level Id", "role": "identity"},
        "level": {"label": "Level", "role": "text"},
        "hostElementId": {"label": "Host element", "role": "identity"},
        "fireRating": {"label": "Fire rating", "role": "text"},
        "smokeControlRating": {"label": "Smoke-control rating", "role": "text"},
        "selfClosingRequired": {"label": "Self-closing required", "role": "boolean"},
        "shaftEnclosureRating": {"label": "Shaft enclosure rating", "role": "text"},
        "penetrationFirestopStatus": {"label": "Penetration firestop", "role": "status"},
        "reviewStatus": {"label": "Review status", "role": "status"},
    },
    "fire_door": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "category": {"label": "Category", "role": "text"},
        "levelId": {"label": "Level Id", "role": "identity"},
        "level": {"label": "Level", "role": "text"},
        "hostElementId": {"label": "Host wall", "role": "identity"},
        "fireRating": {"label": "Door fire rating", "role": "text"},
        "smokeControlRating": {"label": "Door smoke-control rating", "role": "text"},
        "selfClosingRequired": {"label": "Self-closing required", "role": "boolean"},
        "reviewStatus": {"label": "Review status", "role": "status"},
    },
    "escape_route": {
        "elementId": {"label": "Element Id", "role": "id"},
        "routeId": {"label": "Route", "role": "identity"},
        "name": {"label": "Name", "role": "text"},
        "category": {"label": "Category", "role": "text"},
        "levelId": {"label": "Level Id", "role": "identity"},
        "level": {"label": "Level", "role": "text"},
        "travelDistanceM": {"label": "Travel distance (m)", "role": "number"},
        "exitWidthMm": {"label": "Exit width (mm)", "role": "number"},
        "doorSwingCompliant": {"label": "Door swing compliant", "role": "boolean"},
        "stairClassification": {"label": "Stair classification", "role": "text"},
        "corridorClassification": {"label": "Corridor classification", "role": "text"},
        "assemblyPointNote": {"label": "Assembly point note", "role": "text"},
        "reviewStatus": {"label": "Review status", "role": "status"},
    },
    "firestop_penetration": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "category": {"label": "Category", "role": "text"},
        "hostElementId": {"label": "Host element", "role": "identity"},
        "ratedAssemblyId": {"label": "Rated assembly", "role": "identity"},
        "firestopStatus": {"label": "Firestop status", "role": "status"},
        "approvalStatus": {"label": "Approval status", "role": "status"},
        "responsibleTrade": {"label": "Responsible trade", "role": "text"},
        "inspectionEvidence": {"label": "Inspection evidence", "role": "text"},
    },
    "smoke_control_equipment": {
        "elementId": {"label": "Element Id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "category": {"label": "Category", "role": "text"},
        "equipmentType": {"label": "Equipment type", "role": "text"},
        "systemId": {"label": "System", "role": "identity"},
        "controlZone": {"label": "Control zone", "role": "text"},
        "smokeControlRating": {"label": "Smoke-control rating", "role": "text"},
        "status": {"label": "Status", "role": "status"},
        "inspectionEvidence": {"label": "Inspection evidence", "role": "text"},
    },
    "energy_envelope": {
        "elementId": {"label": "Element Id", "role": "id"},
        "hostKind": {"label": "Envelope kind", "role": "text"},
        "thermalClassification": {"label": "Thermal classification", "role": "text"},
        "surfaceAreaM2": {"label": "Surface area (m²)", "role": "number"},
        "uValueWPerM2K": {"label": "U-value W/(m²K)", "role": "number"},
        "missingMaterialKeys": {"label": "Missing thermal material keys", "role": "text"},
        "sourceReferences": {"label": "Source references", "role": "text"},
    },
    "energy_thermal_materials": {
        "materialKey": {"label": "Material key", "role": "identity"},
        "materialDisplay": {"label": "Material", "role": "text"},
        "lambdaWPerMK": {"label": "Lambda W/(mK)", "role": "number"},
        "rhoKgPerM3": {"label": "Density kg/m³", "role": "number"},
        "specificHeatJPerKgK": {"label": "Specific heat J/(kgK)", "role": "number"},
        "mu": {"label": "Water vapour mu", "role": "number"},
        "sourceReference": {"label": "Source reference", "role": "text"},
        "thermalDataStatus": {"label": "Thermal data status", "role": "text"},
    },
    "energy_u_value_summary": {
        "typeId": {"label": "Type id", "role": "identity"},
        "typeName": {"label": "Type name", "role": "text"},
        "hostKind": {"label": "Host kind", "role": "text"},
        "uValueWPerM2K": {"label": "U-value W/(m²K)", "role": "number"},
        "rTotalM2KPerW": {"label": "R total (m²K/W)", "role": "number"},
        "calculationScope": {"label": "Calculation scope", "role": "text"},
    },
    "energy_windows_solar_gains": {
        "openingAreaM2": {"label": "Glazed/opening area (m²)", "role": "number"},
        "uValueWPerM2K": {"label": "U-value W/(m²K)", "role": "number"},
        "gValue": {"label": "g-value", "role": "number"},
        "frameFraction": {"label": "Frame fraction", "role": "number"},
        "annualShadingFactorEstimate": {
            "label": "Annual shading factor estimate",
            "role": "number",
        },
        "shadingDevice": {"label": "Shading device", "role": "text"},
    },
    "energy_thermal_bridges": {
        "markerType": {"label": "Bridge type", "role": "text"},
        "hostElementIds": {"label": "Host elements", "role": "identity"},
        "suggestedMitigation": {"label": "Suggested mitigation", "role": "text"},
        "psiValueReference": {"label": "Psi-value reference", "role": "text"},
    },
    "energy_thermal_zones": {
        "heatingStatus": {"label": "Heating status", "role": "text"},
        "usageProfile": {"label": "Usage profile", "role": "text"},
        "setpointC": {"label": "Setpoint °C", "role": "number"},
        "airChangeRate": {"label": "Air change rate", "role": "number"},
        "zoneId": {"label": "Thermal zone", "role": "identity"},
    },
    "energy_building_services": {
        "heatingGeneratorType": {"label": "Heating generator", "role": "text"},
        "energyCarrier": {"label": "Energy carrier", "role": "text"},
        "ventilationSystem": {"label": "Ventilation system", "role": "text"},
        "measureCandidateNotes": {"label": "iSFP/BEG measure notes", "role": "text"},
    },
    "energy_renovation_measures": {
        "scenarioName": {"label": "Scenario", "role": "text"},
        "scenarioStatus": {"label": "Scenario status", "role": "text"},
        "measureName": {"label": "Measure", "role": "text"},
        "costPlaceholder": {"label": "Cost placeholder", "role": "number"},
    },
    "energy_export_qa": {
        "issueCode": {"label": "Issue code", "role": "identity"},
        "severity": {"label": "Severity", "role": "text"},
        "message": {"label": "Message", "role": "text"},
        "missingMaterialKeys": {"label": "Missing material keys", "role": "text"},
    },
    "construction_package": {
        "elementId": {"label": "Package id", "role": "id"},
        "name": {"label": "Package", "role": "text"},
        "code": {"label": "Code", "role": "text"},
        "phaseId": {"label": "Phase", "role": "identity"},
        "plannedStart": {"label": "Planned start", "role": "date"},
        "plannedEnd": {"label": "Planned end", "role": "date"},
        "actualStart": {"label": "Actual start", "role": "date"},
        "actualEnd": {"label": "Actual end", "role": "date"},
        "responsibleCompany": {"label": "Responsible company", "role": "text"},
        "dependencies": {"label": "Dependencies", "role": "text"},
    },
    "phase": {
        "elementId": {"label": "Phase id", "role": "id"},
        "name": {"label": "Phase", "role": "text"},
        "ord": {"label": "Order", "role": "integer"},
        "createdCount": {"label": "Created elements", "role": "integer"},
        "demolishedCount": {"label": "Demolished elements", "role": "integer"},
        "packageCount": {"label": "Packages", "role": "integer"},
    },
    "progress": {
        "elementId": {"label": "Element id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "kind": {"label": "Kind", "role": "text"},
        "phaseCreated": {"label": "Phase created", "role": "identity"},
        "phaseDemolished": {"label": "Phase demolished", "role": "identity"},
        "constructionPackageId": {"label": "Package", "role": "identity"},
        "plannedStart": {"label": "Planned start", "role": "date"},
        "plannedEnd": {"label": "Planned end", "role": "date"},
        "actualStart": {"label": "Actual start", "role": "date"},
        "actualEnd": {"label": "Actual end", "role": "date"},
        "installationSequence": {"label": "Sequence", "role": "integer"},
        "dependencies": {"label": "Dependencies", "role": "text"},
        "progressStatus": {"label": "Progress status", "role": "text"},
        "responsibleCompany": {"label": "Responsible company", "role": "text"},
        "evidenceCount": {"label": "Evidence", "role": "integer"},
        "issueCount": {"label": "Issues", "role": "integer"},
        "punchItemCount": {"label": "Punch items", "role": "integer"},
        "checklistItemCount": {"label": "Checklist items", "role": "integer"},
    },
    "punch": {
        "elementId": {"label": "Issue id", "role": "id"},
        "title": {"label": "Punch item", "role": "text"},
        "status": {"label": "Status", "role": "text"},
        "elementIds": {"label": "Elements", "role": "text"},
        "viewpointId": {"label": "Viewpoint", "role": "identity"},
        "evidenceCount": {"label": "Evidence", "role": "integer"},
        "issueKind": {"label": "Issue kind", "role": "text"},
    },
    "site_logistics": {
        "elementId": {"label": "Element id", "role": "id"},
        "name": {"label": "Name", "role": "text"},
        "logisticsKind": {"label": "Logistics kind", "role": "text"},
        "phaseId": {"label": "Phase", "role": "identity"},
        "constructionPackageId": {"label": "Package", "role": "identity"},
        "plannedStart": {"label": "Planned start", "role": "date"},
        "plannedEnd": {"label": "Planned end", "role": "date"},
        "actualStart": {"label": "Actual start", "role": "date"},
        "actualEnd": {"label": "Actual end", "role": "date"},
        "progressStatus": {"label": "Progress", "role": "text"},
        "responsibleCompany": {"label": "Responsible company", "role": "text"},
        "boundaryPointCount": {"label": "Boundary points", "role": "integer"},
        "pathPointCount": {"label": "Path points", "role": "integer"},
        "evidenceCount": {"label": "Evidence", "role": "integer"},
        "issueCount": {"label": "Issues", "role": "integer"},
    },
    "qa_checklist": {
        "elementId": {"label": "Checklist id", "role": "id"},
        "name": {"label": "Checklist", "role": "text"},
        "targetElementIds": {"label": "Targets", "role": "text"},
        "constructionPackageId": {"label": "Package", "role": "identity"},
        "phaseId": {"label": "Phase", "role": "identity"},
        "responsibleCompany": {"label": "Responsible company", "role": "text"},
        "progressStatus": {"label": "Progress", "role": "text"},
        "checklistItemCount": {"label": "Items", "role": "integer"},
        "passedCount": {"label": "Passed", "role": "integer"},
        "failedCount": {"label": "Failed", "role": "integer"},
        "openCount": {"label": "Open", "role": "integer"},
        "evidenceCount": {"label": "Evidence", "role": "integer"},
        "issueCount": {"label": "Issues", "role": "integer"},
    },
    "structural_element": _STRUCTURE_FIELD_METADATA,
    "structural_elements": _STRUCTURE_FIELD_METADATA,
    "structure": _STRUCTURE_FIELD_METADATA,
    "structural_wall": _STRUCTURE_FIELD_METADATA,
    "structural_walls": _STRUCTURE_FIELD_METADATA,
    "column": _STRUCTURE_FIELD_METADATA,
    "beam": _STRUCTURE_FIELD_METADATA,
    "foundation": _STRUCTURE_FIELD_METADATA,
    "opening_load_bearing_wall": _STRUCTURE_FIELD_METADATA,
    "opening_in_load_bearing_wall": _STRUCTURE_FIELD_METADATA,
}


def stable_column_keys(category: str, observed_keys: Iterable[str]) -> list[str]:
    """Return registry order first; append unrecognized keys deterministically."""

    cat = category.lower().strip()
    pref = SCHEDULE_COLUMN_ORDER.get(cat, ())
    seen: set[str] = set(pref)
    out: list[str] = []

    for k in pref:
        if k in observed_keys:
            out.append(k)
    extras = sorted(k for k in observed_keys if k not in seen)
    out.extend(extras)

    return out


def column_metadata_bundle(category: str) -> dict[str, Any]:
    """UI metadata for known fields (omit unknown extras — clients fall back to field key)."""

    cat = category.lower().strip()
    cols = SCHEDULE_COLUMN_METADATA.get(cat)
    return {
        "category": cat,
        "fields": cols or {},
    }


def scheduleFieldRegistryCoverageEvidence_v1() -> dict[str, Any]:
    """Per-category dict of registered fields vs metadata-covered fields with coverage %."""

    categories: dict[str, Any] = {}
    for cat, order in SCHEDULE_COLUMN_ORDER.items():
        registered = list(order)
        registered_set = set(registered)
        meta_fields = set(SCHEDULE_COLUMN_METADATA.get(cat, {}).keys())
        covered = sorted(registered_set & meta_fields)
        uncovered = sorted(registered_set - meta_fields)
        pct = round(len(covered) / max(len(registered_set), 1) * 100, 1)
        categories[cat] = {
            "category": cat,
            "registeredFieldCount": len(registered_set),
            "metadataCoveredCount": len(covered),
            "coveragePct": pct,
            "coveredFields": covered,
            "uncoveredFields": uncovered,
        }
    return {
        "format": "scheduleFieldRegistryCoverageEvidence_v1",
        "categories": categories,
    }
