"""BRT-22 barrel regression test.

When ``app/bim_ai/commands.py`` (a single ~3,000 LOC module) was split into
``app/bim_ai/commands/`` (a per-domain subpackage), every command class the
original module exposed had to remain importable from ``bim_ai.commands`` and
the ``Command`` discriminated union had to remain byte-identical on the wire.

This test pins both invariants. If a future refactor moves a class to a new
submodule, that's fine — but the barrel must keep re-exporting it, and
``Command`` must keep including it.
"""

from __future__ import annotations

from types import UnionType
from typing import Annotated, Union, get_args, get_origin

from pydantic import BaseModel

import bim_ai.commands as cmd_barrel
from bim_ai.commands import Command

# Every class name the legacy ``commands.py`` module exposed. Sourced from the
# pre-BRT-22 file (262 Command-union members plus helper / non-discriminated
# classes referenced by the union and by external callers). If you add a new
# command class to the barrel, append it here too — the test will catch any
# accidental removals.
_LEGACY_BARREL_EXPORTS: tuple[str, ...] = (
    # ---- discriminated commands (262 in the union) ----
    "AddOptionCmd",
    "AddViewBreakCmd",
    "AlignElementToReferenceCmd",
    "ApplyPlanViewTemplateCmd",
    "ApplyViewTemplateCmd",
    "AssignElementToOptionCmd",
    "AssignOpeningFamilyCmd",
    "AssignWallDatumConstraintsCmd",
    "AttachWallTopCmd",
    "AttachWallTopToRoofCmd",
    "BumpMonitoredRevisionsCmd",
    "ClearAutoGeneratedAnnotationsCmd",
    "CommitConceptSeedCmd",
    "ConsumeConceptSeedCmd",
    "CreateAgentAssumptionCmd",
    "CreateAgentDeviationCmd",
    "CreateAngularDimensionCmd",
    "CreateAnnotationSymbolCmd",
    "CreateArcLengthDimensionCmd",
    "CreateAreaCmd",
    "CreateBalconyCmd",
    "CreateBcfTopicCmd",
    "CreateBeamCmd",
    "CreateBrandTemplateCmd",
    "CreateCableTrayCmd",
    "CreateCalloutCmd",
    "CreateCeilingCmd",
    "CreateColorFillLegendCmd",
    "CreateColumnCmd",
    "CreateConceptSeedCmd",
    "CreateConstraintCmd",
    "CreateConstructionLogisticsCmd",
    "CreateConstructionPackageCmd",
    "CreateDecalCmd",
    "CreateDetailComponentCmd",
    "CreateDetailGroupCmd",
    "CreateDetailLineCmd",
    "CreateDetailRegionCmd",
    "CreateDiameterDimensionCmd",
    "CreateDimensionCmd",
    "CreateDormerCmd",
    "CreateDraftingViewCmd",
    "CreateDuctCmd",
    "CreateDuctLegendCmd",
    "CreateEdgeProfileRunCmd",
    "CreateElevationViewCmd",
    "CreateExternalLinkCmd",
    "CreateFixtureCmd",
    "CreateFloorCmd",
    "CreateFrameCmd",
    "CreateGradedRegionCmd",
    "CreateGridLineCmd",
    "CreateInsulationAnnotationCmd",
    "CreateIssueFromViolationCmd",
    "CreateJoinGeometryCmd",
    "CreateKeynoteCmd",
    "CreateLevelCmd",
    "CreateLinkDxfCmd",
    "CreateLinkModelCmd",
    "CreateMaskingRegionCmd",
    "CreateMassCmd",
    "CreateMaterialTagCmd",
    "CreateMepEquipmentCmd",
    "CreateMepOpeningRequestCmd",
    "CreateMepTerminalCmd",
    "CreateMultiCategoryTagCmd",
    "CreateOptionSetCmd",
    "CreatePhaseCmd",
    "CreatePipeCmd",
    "CreatePipeLegendCmd",
    "CreatePlanRegionCmd",
    "CreatePresentationCanvasCmd",
    "CreateProjectBasePointCmd",
    "CreatePropertyDefinitionCmd",
    "CreatePropertyLineCmd",
    "CreateRadialDimensionCmd",
    "CreateRailingCmd",
    "CreateReferencePlaneCmd",
    "CreateRepeatingDetailCmd",
    "CreateRevisionCloudCmd",
    "CreateRoofCmd",
    "CreateRoofJoinCmd",
    "CreateRoofOpeningCmd",
    "CreateRoomOutlineCmd",
    "CreateRoomPolyCmd",
    "CreateRoomRectangleCmd",
    "CreateRoomSeparationCmd",
    "CreateSavedViewCmd",
    "CreateScheduleViewCmd",
    "CreateSectionCutCmd",
    "CreateSheetCmd",
    "CreateSlabOpeningCmd",
    "CreateSoffitCmd",
    "CreateSpanDirectionCmd",
    "CreateSpotCoordinateCmd",
    "CreateSpotElevationCmd",
    "CreateSpotSlopeCmd",
    "CreateStairCmd",
    "CreateSunSettingsCmd",
    "CreateSurveyPointCmd",
    "CreateSweepCmd",
    "CreateText3dCmd",
    "CreateTextNoteCmd",
    "CreateToposolidCmd",
    "CreateToposolidExcavationCmd",
    "CreateToposolidSubdivisionCmd",
    "CreateTreadNumberCmd",
    "CreateViewCalloutCmd",
    "CreateViewTemplateCmd",
    "CreateVoidCutCmd",
    "CreateWallChainCmd",
    "CreateWallCmd",
    "CreateWallOpeningCmd",
    "CreateWallTypeCmd",
    "CreateWindowLegendViewCmd",
    "DeleteAreaCmd",
    "DeleteBrandTemplateCmd",
    "DeleteElementCmd",
    "DeleteElementsCmd",
    "DeleteExternalLinkCmd",
    "DeleteFrameCmd",
    "DeleteGradedRegionCmd",
    "DeleteImageUnderlayCmd",
    "DeleteLinkModelCmd",
    "DeleteMaskingRegionCmd",
    "DeletePhaseCmd",
    "DeletePlanRegionCmd",
    "DeletePropertyLineCmd",
    "DeleteReferencePlaneCmd",
    "DeleteSavedViewCmd",
    "DeleteToposolidCmd",
    "DeleteToposolidExcavationCmd",
    "DeleteToposolidSubdivisionCmd",
    "DeleteViewTemplateCmd",
    "DetachWallTopCmd",
    "DrawDetailRegionCmd",
    "ExtendFloorInsulationCmd",
    "HideElementInViewCmd",
    "ImportImageUnderlayCmd",
    "IndexAssetCmd",
    "InsertDoorOnWallCmd",
    "InsertWindowOnWallCmd",
    "MaterializeMassToWallsCmd",
    "MirrorElementsCmd",
    "MoveAssetDeltaCmd",
    "MoveBeamEndpointsCmd",
    "MoveColumnDeltaCmd",
    "MoveElementCmd",
    "MoveElementsDeltaCmd",
    "MoveGridLineEndpointsCmd",
    "MoveImageUnderlayCmd",
    "MoveLevelElevationCmd",
    "MoveProjectBasePointCmd",
    "MoveSurveyPointCmd",
    "MoveViewOnSheetCmd",
    "MoveWallDeltaCmd",
    "MoveWallEndpointsCmd",
    "PinElementCmd",
    "PlaceAssetCmd",
    "PlaceFamilyInstanceCmd",
    "PlaceKitCmd",
    "PlaceRoomAtPointCmd",
    "PlaceTagCmd",
    "PlaceViewOnSheetCmd",
    "ReconcileMonitoredElementCmd",
    "RemoveOptionCmd",
    "RemoveViewBreakCmd",
    "RemoveViewFromSheetCmd",
    "RenamePhaseCmd",
    "ReorderFrameCmd",
    "ReorderPhaseCmd",
    "ReorderViewCmd",
    "RestoreElementCmd",
    "RotateElementsCmd",
    "RotateImageUnderlayCmd",
    "RotateProjectBasePointCmd",
    "RunClashTestCmd",
    "SaveViewpointCmd",
    "ScaleImageUnderlayCmd",
    "SetCurtainPanelOverrideCmd",
    "SetEdgeProfileRunModeCmd",
    "SetElementConstructionCmd",
    "SetElementDisciplineCmd",
    "SetElementOverrideCmd",
    "SetElementPhaseCmd",
    "SetElementPropCmd",
    "SetPrimaryOptionCmd",
    "SetRailingBalusterPatternCmd",
    "SetRailingHandrailSupportsCmd",
    "SetSheetTitleblockCmd",
    "SetStairSubKindCmd",
    "SetToolPrefCmd",
    "SetViewLensCmd",
    "SetViewOptionLockCmd",
    "SetViewPhaseCmd",
    "SetViewPhaseFilterCmd",
    "SetWallJoinDisallowCmd",
    "SetWallJoinVariantCmd",
    "SetWallLeanTaperCmd",
    "SetWallRecessZonesCmd",
    "SetWallStackCmd",
    "SplitWallAtCmd",
    "TrimElementToReferenceCmd",
    "TrimExtendToCornerCmd",
    "UnbindViewTemplateCmd",
    "UnhideElementInViewCmd",
    "UnpinElementCmd",
    "UpdateAreaCmd",
    "UpdateBrandTemplateCmd",
    "UpdateColumnCmd",
    "UpdateDetailRegionCmd",
    "UpdateDoorCmd",
    "UpdateElementPropertyCmd",
    "UpdateExternalLinkCmd",
    "UpdateFrameCmd",
    "UpdateGradedRegionCmd",
    "UpdateIssueStatusCmd",
    "UpdateKitComponentCmd",
    "UpdateLinkDxfCmd",
    "UpdateLinkModelCmd",
    "UpdateMaskingRegionCmd",
    "UpdateMaterialPbrCmd",
    "UpdateOpeningCleanroomCmd",
    "UpdatePlanRegionCmd",
    "UpdatePlanViewCropCmd",
    "UpdatePlanViewRangeCmd",
    "UpdatePresentationCanvasCmd",
    "UpdatePropertyLineCmd",
    "UpdateReferencePlaneCmd",
    "UpdateSavedViewCmd",
    "UpdateSheetMetadataCmd",
    "UpdateStairTreadsCmd",
    "UpdateSunSettingsCmd",
    "UpdateToposolidCmd",
    "UpdateToposolidExcavationCmd",
    "UpdateToposolidSubdivisionCmd",
    "UpdateViewTemplateCmd",
    "UpdateWallCmd",
    "UpdateWallOpeningCmd",
    "UpdateWindowCmd",
    "UpsertClashTestCmd",
    "UpsertConstructionQaChecklistCmd",
    "UpsertFamilyTypeCmd",
    "UpsertFloorTypeCmd",
    "UpsertPlanTagStyleCmd",
    "UpsertPlanViewCmd",
    "UpsertPlanViewTemplateCmd",
    "UpsertProjectSettingsCmd",
    "UpsertRoofTypeCmd",
    "UpsertRoomColorSchemeCmd",
    "UpsertRoomVolumeCmd",
    "UpsertScheduleCmd",
    "UpsertScheduleFiltersCmd",
    "UpsertSelectionSetCmd",
    "UpsertSheetCmd",
    "UpsertSheetViewportsCmd",
    "UpsertSiteCmd",
    "UpsertSourceViewEvidenceCmd",
    "UpsertTagDefinitionCmd",
    "UpsertValidationRuleCmd",
    "UpsertViewTemplateCmd",
    "UpsertWallTypeCmd",
    # ---- non-discriminated helper classes ----
    "ConstructionMetadata",
    "FamilyCatalogSourceCmd",
    "MirrorAxis",
    "SelectionSetRuleCmd",
    "WallChainSegment",
    "WallStackComponentCmd",
    # ---- literal aliases referenced by callers ----
    "AreaRuleSetCmd",
    "AreaSchemeCmd",
    "MepSystemCmdType",
    "PlanViewSubtypeCmd",
    "PropertyLineClassificationCmd",
    "ToposolidExcavationCutMode",
    "WallJoinVariant",
)


def _union_members(annotated: object) -> tuple[type[BaseModel], ...]:
    if get_origin(annotated) is not Annotated:
        raise AssertionError("Command must be an Annotated discriminated union.")
    inner = get_args(annotated)[0]
    if get_origin(inner) not in {UnionType, Union}:
        raise AssertionError("Command's inner type must be a Union.")
    return get_args(inner)


def test_every_legacy_symbol_still_imports_from_bim_ai_commands() -> None:
    """Every class the pre-split barrel exposed must remain importable.

    This catches accidental removals during future refactors that touch the
    per-domain submodules.
    """

    missing = [name for name in _LEGACY_BARREL_EXPORTS if not hasattr(cmd_barrel, name)]
    assert not missing, f"barrel lost {len(missing)} legacy export(s): {missing[:8]}…"


def test_command_union_includes_every_discriminated_class() -> None:
    """The ``Command`` discriminated union must contain every Cmd class that
    used to participate in it.

    Helper classes (``WallChainSegment``, ``MirrorAxis``, ``ConstructionMetadata``)
    and literal aliases never participated and are filtered out here.
    """

    members = _union_members(Command)
    member_names = {m.__name__ for m in members}
    # The non-discriminated helpers + literal aliases we exclude:
    non_union_names = {
        "ConstructionMetadata",
        "FamilyCatalogSourceCmd",
        "MirrorAxis",
        "SelectionSetRuleCmd",
        "WallChainSegment",
        "WallStackComponentCmd",
        "AreaRuleSetCmd",
        "AreaSchemeCmd",
        "MepSystemCmdType",
        "PlanViewSubtypeCmd",
        "PropertyLineClassificationCmd",
        "ToposolidExcavationCutMode",
        "WallJoinVariant",
    }
    expected_union = [n for n in _LEGACY_BARREL_EXPORTS if n not in non_union_names]

    missing_from_union = sorted(set(expected_union) - member_names)
    assert not missing_from_union, (
        f"Command union is missing {len(missing_from_union)} member(s): {missing_from_union}"
    )


def test_command_union_member_count_matches_legacy_baseline() -> None:
    """262 discriminated members is the pre-split baseline; if it changes,
    update ``EXPECTED_COMMAND_COUNT`` in ``test_command_schemas.py`` too.
    """

    members = _union_members(Command)
    # Issue #102 — added CreateFacadeBayCmd (Erker / facade_bay element).
    # Issue #114 — added CreateWintergartenCmd (glazed conservatory).
    # Issue #113 — added CreateStructuralFacadeGridCmd (Huf-Haus Pfosten-Riegel grid).
    # Together these bump the discriminated-union member count from 262 → 265.
    assert len(members) == 265


def test_barrel_resolves_to_package_init() -> None:
    """``bim_ai.commands`` should now resolve to the per-domain subpackage's
    ``__init__.py`` — not to a sibling ``commands.py`` (which would race the
    package and break the barrel contract)."""

    assert cmd_barrel.__file__ is not None
    assert cmd_barrel.__file__.endswith("commands/__init__.py"), cmd_barrel.__file__
