"""PLN-01 / ANN-01 — placeTag, clearAutoGeneratedAnnotations, and detail
component commands (createDetailLine / createDetailRegion / createTextNote).
"""

import pytest

from bim_ai.commands import (
    ClearAutoGeneratedAnnotationsCmd,
    CreateDetailLineCmd,
    CreateDetailRegionCmd,
    CreateDimensionCmd,
    CreateTextNoteCmd,
    PlaceTagCmd,
)
from bim_ai.document import Document
from bim_ai.elements import (
    DetailLineElem,
    DetailRegionElem,
    DimensionElem,
    DoorElem,
    LevelElem,
    PlacedTagElem,
    PlanViewElem,
    RoomElem,
    TextNoteElem,
    Vec2Mm,
    WallElem,
)
from bim_ai.engine import apply_inplace


def _seed() -> Document:
    return Document(
        revision=1,
        elements={
            "lv": LevelElem(kind="level", id="lv", name="EG", elevationMm=0),
            "pv": PlanViewElem(kind="plan_view", id="pv", name="GF", levelId="lv"),
            "w-1": WallElem(
                kind="wall",
                id="w-1",
                name="W",
                levelId="lv",
                start=Vec2Mm(xMm=0, yMm=0),
                end=Vec2Mm(xMm=4000, yMm=0),
                thicknessMm=200,
                heightMm=2800,
            ),
            "door-1": DoorElem(
                kind="door",
                id="door-1",
                name="Door",
                wallId="w-1",
                alongT=0.5,
                widthMm=900,
            ),
            "room-1": RoomElem(
                kind="room",
                id="room-1",
                name="Living",
                levelId="lv",
                outlineMm=[
                    Vec2Mm(xMm=0, yMm=0),
                    Vec2Mm(xMm=4000, yMm=0),
                    Vec2Mm(xMm=4000, yMm=3000),
                    Vec2Mm(xMm=0, yMm=3000),
                ],
            ),
        },
    )


def test_place_tag_room_door_window_only() -> None:
    doc = _seed()
    apply_inplace(
        doc,
        PlaceTagCmd(
            id="t-1",
            hostElementId="room-1",
            hostViewId="pv",
            positionMm=Vec2Mm(xMm=2000, yMm=1500),
            autoGenerated=True,
        ),
    )
    apply_inplace(
        doc,
        PlaceTagCmd(
            id="t-2",
            hostElementId="door-1",
            hostViewId="pv",
            positionMm=Vec2Mm(xMm=2000, yMm=0),
        ),
    )
    el1 = doc.elements["t-1"]
    el2 = doc.elements["t-2"]
    assert isinstance(el1, PlacedTagElem)
    assert el1.auto_generated is True
    assert isinstance(el2, PlacedTagElem)
    assert el2.host_element_id == "door-1"

    # Reject hosts that aren't room/door/window.
    with pytest.raises(ValueError):
        apply_inplace(
            doc,
            PlaceTagCmd(
                id="t-3",
                hostElementId="w-1",
                hostViewId="pv",
                positionMm=Vec2Mm(xMm=0, yMm=0),
            ),
        )


def test_clear_auto_generated_annotations() -> None:
    doc = _seed()
    apply_inplace(
        doc,
        CreateDimensionCmd(
            id="dim-auto",
            levelId="lv",
            aMm=Vec2Mm(xMm=0, yMm=0),
            bMm=Vec2Mm(xMm=4000, yMm=0),
            offsetMm=Vec2Mm(xMm=0, yMm=-800),
            autoGenerated=True,
        ),
    )
    apply_inplace(
        doc,
        CreateDimensionCmd(
            id="dim-manual",
            levelId="lv",
            aMm=Vec2Mm(xMm=0, yMm=3000),
            bMm=Vec2Mm(xMm=4000, yMm=3000),
            offsetMm=Vec2Mm(xMm=0, yMm=800),
        ),
    )
    apply_inplace(
        doc,
        PlaceTagCmd(
            id="t-auto",
            hostElementId="room-1",
            hostViewId="pv",
            positionMm=Vec2Mm(xMm=2000, yMm=1500),
            autoGenerated=True,
        ),
    )
    apply_inplace(
        doc,
        PlaceTagCmd(
            id="t-manual",
            hostElementId="door-1",
            hostViewId="pv",
            positionMm=Vec2Mm(xMm=2000, yMm=0),
        ),
    )

    # Clear scope=both wipes auto rows from both kinds.
    apply_inplace(doc, ClearAutoGeneratedAnnotationsCmd(hostViewId="pv", scope="both"))
    assert "dim-auto" not in doc.elements
    assert "t-auto" not in doc.elements
    # Manual rows remain untouched.
    assert isinstance(doc.elements["dim-manual"], DimensionElem)
    assert isinstance(doc.elements["t-manual"], PlacedTagElem)


def test_create_detail_line_region_text_note() -> None:
    doc = _seed()
    apply_inplace(
        doc,
        CreateDetailLineCmd(
            id="dl",
            hostViewId="pv",
            pointsMm=[Vec2Mm(xMm=0, yMm=0), Vec2Mm(xMm=1000, yMm=0)],
            strokeMm=2.0,
            style="dashed",
        ),
    )
    apply_inplace(
        doc,
        CreateDetailRegionCmd(
            id="dr",
            hostViewId="pv",
            boundaryMm=[
                Vec2Mm(xMm=0, yMm=0),
                Vec2Mm(xMm=1000, yMm=0),
                Vec2Mm(xMm=1000, yMm=1000),
            ],
            fillPattern="hatch_45",
        ),
    )
    apply_inplace(
        doc,
        CreateTextNoteCmd(
            id="tn",
            hostViewId="pv",
            positionMm=Vec2Mm(xMm=500, yMm=500),
            text="Hello",
            fontSizeMm=200,
            anchor="c",
        ),
    )
    dl = doc.elements["dl"]
    dr = doc.elements["dr"]
    tn = doc.elements["tn"]
    assert isinstance(dl, DetailLineElem)
    assert dl.style == "dashed"
    assert dl.host_view_id == "pv"
    assert isinstance(dr, DetailRegionElem)
    assert dr.fill_pattern == "hatch_45"
    assert isinstance(tn, TextNoteElem)
    assert tn.text == "Hello"
    assert tn.anchor == "c"


def test_detail_components_validate_view_and_geometry() -> None:
    doc = _seed()
    with pytest.raises(ValueError):
        apply_inplace(
            doc,
            CreateDetailLineCmd(
                id="dl",
                hostViewId="missing-view",
                pointsMm=[Vec2Mm(xMm=0, yMm=0), Vec2Mm(xMm=1000, yMm=0)],
            ),
        )
    with pytest.raises(ValueError):
        apply_inplace(
            doc,
            CreateDetailLineCmd(
                id="dl",
                hostViewId="pv",
                pointsMm=[Vec2Mm(xMm=0, yMm=0)],
            ),
        )
    with pytest.raises(ValueError):
        apply_inplace(
            doc,
            CreateDetailRegionCmd(
                id="dr",
                hostViewId="pv",
                boundaryMm=[Vec2Mm(xMm=0, yMm=0), Vec2Mm(xMm=1, yMm=0)],
            ),
        )
    with pytest.raises(ValueError):
        apply_inplace(
            doc,
            CreateTextNoteCmd(
                id="tn",
                hostViewId="pv",
                positionMm=Vec2Mm(xMm=0, yMm=0),
                text="",
                fontSizeMm=100,
            ),
        )
